### ISSUE TITLE
Create a README for new Kraken 2 Repo

### ISSUE THREAD

**Issue by cwazy1** [samsung-cnct/k2#1]
This functions as a test ticket as well as a task item to create a new README with updated paths and config management.

**Comment by cwazy1** [comment]
Adding a comment through zube integration

**Comment by cwazy1** [comment]
test comment. planning for release 9/31

**Comment by venezia** [comment]
First iteration is OK

**Comment by maratoid** [comment]
Need to change front page README.md

**Comment by alejandroEsc** [comment]
Since i will be learning k2 in the next few days, would you guys mind me giving this a go?
