### ISSUE TITLE
Created ssh_config Has Container's Path for the Identity File

### ISSUE THREAD

**Issue by mikeln** [samsung-cnct/k2#102]
The create ssh_config has the container's path for the Identity File. e.g. /root/.ssh/id_rsa.
Fine if you run from another container with the same mount points.

Won't work from your laptop directly (which is probably the more useful case)...
e.g. should be $HOME/.ssh/id_rsa

**Comment by mikeln** [comment]
That is... IF you brought up the system via a container in the first place.

**Comment by coffeepac** [comment]
https://github.com/samsung-cnct/k2/issues/69 is the dupe.  its a limitation of building the ssh config inside the container.  the container doesn't have any knowledge of the host system layout.

k2cli will perform the replacement for you, you can do it by hand or specify the ssh key manually.  or we could add an ssh client to the k2 image and have you run a docker container to ssh over.  that seems a bit odd to me though.

**Comment by coffeepac** [comment]
resolved by correcting how paths get mounted into the running k2 container
