### ISSUE TITLE
Java Client HTTPS Issue

### ISSUE THREAD

**Issue by mikeln** [samsung-cnct/k2#104]
A common Java https implementation that communicates with a Kubernetes Master (APIServer) commonly includes:

`SSLContext ctx = SSLContext.getInstance("SSL");`

This will fail the TLS handshake on a protocol_error in a K2 cluster.

It has to be:

`SSLContext ctx = SSLContext.getInstance("TLSv1.2");`

Not sure if this is a valid requirement to place on app developers, or apps converted to run in Kubernetes.

**Comment by coffeepac** [comment]
this doesn't seem like something we should be forcing.  do you know if this is a k8s wide issue or something k2 specific?

**Comment by coffeepac** [comment]
won't fix.  is secure this way.
