### ISSUE TITLE
Pod DNS Query Requires FQDN

### ISSUE THREAD

**Issue by mikeln** [samsung-cnct/k2#107]
Running a cassandra deployment in a K2 cluster.   Service cassandra (namespace cassandra) available.

An app running in the cluster used to be able to resolve the service via name:  cassandra.cassandra.

Now it appears to only be resolvable via: cassandra.cassanda.svc.cluster.local.

This is even though /etc/resolv.conf in that pod shows:

     root@dataschema:/twissandra# cat /etc/resolv.conf
     search cassandra.svc.cluster.local svc.cluster.local cluster.local mikeln-k2.internal
     nameserver 10.32.0.2
     options ndots:5

**Comment by mikeln** [comment]
However....  dig does not seem to use resolv.conf.  nslookup does work correctly.

**Comment by mikeln** [comment]
ping cassandra.cassandra does resolve correctly.

looks like isolated to dig and python

**Comment by mikeln** [comment]
as pointed out.  dig +search cassandra.cassandra does resolve correctly.

**Comment by mikeln** [comment]
running python by hand socket.gethostbyname("cassandra.cassandra") does resolve correctly.

this could be a non-issue.

**Comment by coffeepac** [comment]
as determined working on this issue it was a non-issue.
