### ISSUE TITLE
update user's default kubectl with cluster context

### ISSUE THREAD

**Issue by maratoid** [samsung-cnct/k2#109]
Currently we create a separate kubeconfig file for each cluster under cluster's folder, along with a bunch of other cluster state stuff. It would be most convenient for users of kubectl and helm to have that information (optionally) exported into their default kubectl unde ~/.kube/config

This might be more easily accomplished in https://github.com/samsung-cnct/k2cli

**Comment by coffeepac** [comment]
@maratoid I would lean towards this type of activity being pushed into k2cli.  I'm not sure we want to have people running the docker container manually.  It opens us up to a lot of different support requests/management issues.

**Comment by maratoid** [comment]
I was referring to where the code for this is going to live. You could do this with ansible (probably) or in k2cli's go code.

**Comment by coffeepac** [comment]
that's what I was talking about as well.

**Comment by coffeepac** [comment]
going to let k2cli handle this
