### ISSUE TITLE
aws provider - credentialsFile doesn't work

### ISSUE THREAD

**Issue by coffeepac** [samsung-cnct/k2#128]
using the credentialsFile for authentication doesn't seem to work.

to repro:  supply credentialsFile and credentialsProfile under authentication and attempt to bring up a cluster.  

I am currently getting 

> failed: [localhost] (item={u'count': 6, u'name': u'clusterNodes', u'providerConfig': {u'subnet': [u'uwseast1b', u'uwseast1c', u'uwseast1d'], u'tags': [{u'value': u'Cluster plain nodes', u'key': u'comments'}], u'storage': [{u'type': u'ebs_block_device', u'opts': {u'encrypted': False, u'volume_type': u'gp2', u'device_name': u'sdf', u'volume_size': 100, u'snapshot_id': None, u'delete_on_termination': True}}, {u'type': u'ebs_block_device', u'opts': {u'encrypted': False, u'volume_type': u'gp2', u'device_name': u'sdg', u'volume_size': 100, u'snapshot_id': None, u'delete_on_termination': True}}], u'type': u'm4.large'}, u'kubeConfig': {u'containerConfig': {u'version': u'1.12.0', u'name': u'dockerconfig', u'runtime': u'docker'}, u'hyperkubeLocation': u'quay.io/coreos/hyperkube', u'version': u'v1.4.5_coreos.0', u'name': u'krakenKubeConfig'}, u'keypair': {u'privatekeyFile': u'/Users/pat/.ssh/id_rsa', u'name': u'krakenKey', u'publickeyFile': u'/Users/pat/.ssh/id_rsa.pub'}, u'coreos': {u'version': u'current', u'name': u'allNodes', u'rebootStrategy': False, u'channel': u'stable'}, u'mounts': [{u'device': u'sdf', u'path': u'/var/lib/docker', u'forceFormat': True}, {u'device': u'sdg', u'path': u'/ephemeral/ceph', u'forceFormat': False}]}) => {"failed": true, "item": {"coreos": {"channel": "stable", "name": "allNodes", "rebootStrategy": false, "version": "current"}, "count": 6, "keypair": {"name": "krakenKey", "privatekeyFile": "/Users/pat/.ssh/id_rsa", "publickeyFile": "/Users/pat/.ssh/id_rsa.pub"}, "kubeConfig": {"containerConfig": {"name": "dockerconfig", "runtime": "docker", "version": "1.12.0"}, "hyperkubeLocation": "quay.io/coreos/hyperkube", "name": "krakenKubeConfig", "version": "v1.4.5_coreos.0"}, "mounts": [{"device": "sdf", "forceFormat": true, "path": "/var/lib/docker"}, {"device": "sdg", "forceFormat": false, "path": "/ephemeral/ceph"}], "name": "clusterNodes", "providerConfig": {"storage": [{"opts": {"delete_on_termination": true, "device_name": "sdf", "encrypted": false, "snapshot_id": null, "volume_size": 100, "volume_type": "gp2"}, "type": "ebs_block_device"}, {"opts": {"delete_on_termination": true, "device_name": "sdg", "encrypted": false, "snapshot_id": null, "volume_size": 100, "volume_type": "gp2"}, "type": "ebs_block_device"}], "subnet": ["uwseast1b", "uwseast1c", "uwseast1d"], "tags": [{"key": "comments", "value": "Cluster plain nodes"}], "type": "m4.large"}}, "msg": "No handler was ready to authenticate. 1 handlers were checked. ['HmacAuthV4Handler'] Check your credentials"}

repeatedly.

**Comment by joejulian** [comment]
Tried setting `credentialsFile` to an absolute path which won't work because that file will not exist at that absolute path within the docker container.

I then set it to `${HOME}/.aws/credentials` which resolves correctly in k2 with the documented `-v ~/:/root`.

**Comment by joejulian** [comment]
Looks like I missed a spot.
