### ISSUE TITLE
[K2 under CI ASAP] Decide which tests we should be running to verify a k2 cluster

### ISSUE THREAD

**Issue by cwazy1** [samsung-cnct/k2#13]

**Comment by cwazy1** [comment]
Subtasks will describe what exactly will be required. Should be linked with issues that are blocking us from doing this immediately (missing tools/containers?)

We should get K2 under CI control as soon as we have something that performs any kind of functionality - even if it just creates the terraform infra and doesn't do anything else.

CI jobs should evolve with the project, as it gets more filled out.

**Comment by maratoid** [comment]
Currently on pre-merge will will do some basic grep checks on which pods started up
On post merge we are running conformance test suite.
