### ISSUE TITLE
Redo Kraken-services as helm charts

### ISSUE THREAD

**Issue by cwazy1** [samsung-cnct/k2#14]

**Comment by cwazy1** [comment]
aaron Aaron Crickenberger added a comment - 23/Jun/16 4:33 PM
Opened
https://github.com/kubernetes/helm/issues/880 since this restricts us to building helm docker images on systems w/ docker 1.9.1

**Comment by maratoid** [comment]
helm repo is at http://atlas.cnct.io

chart PRs are linted on open, and repo is rebuilt on merge
