### ISSUE TITLE
Determine plan for K8S core compatability

### ISSUE THREAD

**Issue by venezia** [samsung-cnct/k2#152]
As K2 uses a larger breadth of options for kubelet, apiserver, etc., compatability across versions of kubernetes can become problematic.

For example, in 1.6, `--register-schedulable` is deprecated in favor of taints (see https://github.com/kubernetes/kubernetes/pull/31647 ) - so how we register our nodes, and use taints (see #151 ) will change in 1.6 that is not compatible with 1.5 and below

What is our plan?  Do we identify that some features (like taints) are incompatible with the version of K8S you want to run; do we keep versions of templates based on the minor version of K8S that will be run.  And how do we handle upgrades (going from K8S 1.5 to 1.6 - new ASG with new launchconfig in AWS? for example)

**Comment by spiffxp** [comment]
I would suggest we follow the k8s version support policy, the docs for which I can't find at the moment, but the gist of which, I think, is:
- alpha features can change in breaking ways between releases
- beta features should go through a deprecation cycle, I forget if that's 1 year or N releases
- GA features same thing as beta, but I think the deprecation cycle is major releases

Ideally for regular k2 functionality we shouldn't need any alpha features of k8s.  Are we using any today?  For things that use alpha features (eg: StatefulSets vs. PetSets) we should use CI to gate us to a "supported" version, and use CI tests of alpha/beta builds to get a heads up on when breaking changes are coming our way

**Comment by coffeepac** [comment]
@spiffxp the kubernetes version support policy will tell us how long kubernetes features are available but what do we do when we've upgraded k2 to use taints instead of --register-schedulable and someone tries to launch a pre v1.6 kubernetes cluster with the latest k2?  Do we simply reject the attempt, do we have a pre v1.6 deploy template laying around, do we do something else?

**Comment by spiffxp** [comment]
I guess the question boils down to, do you aim for lowest common denominator or do you use specific features that will only work with a given version of kubernetes?  I'm not sure what specific requirements would drive us toward the latter.

My read of https://github.com/kubernetes/community/blob/854e9518703851ec79e26a47d46a0c70d829fe37/contributors/design-proposals/versioning.md#supported-releases-and-component-skew is that "lowest common denominator" implies something that is known to exist for the current release, the two prior releases, and potentially the upcoming release.

However https://github.com/kubernetes/community/blob/854e9518703851ec79e26a47d46a0c70d829fe37/contributors/design-proposals/versioning.md#upgrades recommends not upgrading more than two minor releases at a time, so maybe lowest common denominator is just whatever works with the current release, one prior release, and the upcoming release.

To me, the cost of having permutations of configs for each version of k8s is something that we should pay only when we need to.  If we think those sorts of requirements are coming down the pipeline, then multiple templates makes sense; that's effectively what upgrading is like with `kube-up` et al

**Comment by l337ch** [comment]
@coffeepac Will there be versioned releases of k2? If a user wants to use k8s 1.4 and that isn't support in k2 2.0 but is in < k2 1.9. That user can use k2 1.9 and have a functioning k8s 1.4 cluster. Versioned k2 releases may simplify the backwards compatibility problem.

**Comment by coffeepac** [comment]
@l337ch we are going to be moving to versioned releases of k2.  this helps with creating/managing a cluster within a given minor release but leaves open the question how to handle migrations between minor releases.  

we would also need to have a support life for old versions of k2.  I'm not porting bug fixes back forever

**Comment by maratoid** [comment]
AFAIK, we don't actually use '--register-schedulable' anywhere. But this is still a valid concern.

**Comment by coffeepac** [comment]
@l337ch what version of k8s are you running at zonar?  is it 1.4?

I ask because helm 2.1.3 is not backwards compatible with kubernetes 1.4 BUT helm 2.1.3 is required for kubernetes 1.5.  This isn't to force you into anything but it may be a concrete, client driven need to bring this question to a resolution.

**Comment by l337ch** [comment]
@coffeepac we're using k8s 1.5.1

**Comment by coffeepac** [comment]
thanks @l337ch

**Comment by coffeepac** [comment]
we are going to start working on node management next sprint.  specifically we will be working on upgrading and downgrading the version of kubernetes running on either the cluster pools (kubelet and proxy) or master pools (controller, api server, proxy, scheduler).   

my current inclination is to see how much effort is required to support a template per minor version as that seems to be a reasonable target.  if its a major effort then maybe backoff but this seems like where we need to go eventually so why not go there now?

thoughts?  opinions?  our next sprint starts next Wednesday (2/15) so chime in quickly.

**Comment by venezia** [comment]
I think its fine to have different templates based on K8S minor versions (1.5 vs 1.6, etc.) - however hopefully we can continue to use the same configuration.

This way we can allow users to migrate to a new K8S cluster easier.  To do that though we should have a configuration check that is run before anything else is done.  
 - It would run through the given input and look to see if any option that are being used are no longer available.  
 - If configuration options are being deprecated, it should warn us about this too.  
 - It should tell us about any missing options

With that information set, we should create forks of our templates based off of the K8S version that is being used.  Something either like 

```
/v1.4/master/apiserver.yaml.tmpl
/v1.4/master/kubelet.yaml.tmpl
/v1.4/common/something.else.yaml.tmpl
```

or

```
/master/v1.4/apiserver.yaml.template
/master/v1.4/kubelet.yaml.template
/common/v1.4/something.else.yaml.template
```

Both have advantages and disadvantages - though I think I like the former.

**Comment by coffeepac** [comment]
I also like the former layout.  Makes it easy to remove configs when we stop supporting older versions of k8s.

**Comment by coffeepac** [comment]
@venezia for the version checking tool you're talking about, would it be running against the k2cli config?  

I think that's the right spot because that's our interface with the cluster operator.  Also means the cluster operators doesn't need to know what options, exactly, Samsung things should be used.

**Comment by coffeepac** [comment]
resolved by #222 going to move this to review and hope it auto-closes when 222 does.

**Comment by leahnp** [comment]
LGTM - 222 seems to scope out the work/concerns discussed in this ticket.

**Comment by coffeepac** [comment]
waiting on #222 to finish up again.

**Comment by coffeepac** [comment]
#222 has finished again.  this has expanded and is fine.
