### ISSUE TITLE
Look into CoreRoller for managing CoreOS based installs

### ISSUE THREAD

**Issue by venezia** [samsung-cnct/k2#155]
CoreRoller ( https://github.com/coreroller/coreroller ) is a project that will allow you to manage the packages installed on a CoreOS machine as well as what version of CoreOS (ContainerLinux) is deployed where.

This service could be deployed to a kubernetes cluster (in a self-hosted sort of way) to help manage nodes that the cluster are running.  Could also be used to keep a specific version of docker running on the fleet

**Comment by coffeepac** [comment]
this would help us with maintain or set a specific version of docker (ie ours)

**Comment by coffeepac** [comment]
we will not update running nodes, we will nuke them and start over.
