### ISSUE TITLE
k2 e2e fails with kubernetes 1.5.1

### ISSUE THREAD

**Issue by spiffxp** [samsung-cnct/k2#159]
I suspect the tests need to be rewritten to account for the fact that client/server binaries aren't included in the main kubernetes.tar.gz release artifact anymore.

eg: https://pipelet.kubeme.io/job/k2-e2e-aws-k8s-conformance/104/console
```
15:47:55 + go run hack/e2e.go --v --test '--test_args=--ginkgo.v=true --ginkgo.noColor=true --ginkgo.focus=\[Conformance\] --ginkgo.skip=\[Serial\] --e2e-output-dir=/var/jenkins_home/jobs/k2-e2e-aws-k8s-conformance/workspace/output/artifacts --report-dir=/var/jenkins_home/jobs/k2-e2e-aws-k8s-conformance/workspace/output/artifacts' --check_version_skew=false
15:47:56 2017/01/06 23:47:56 e2e.go:722: Running: kubectl version
15:47:56 2017/01/06 23:47:56 e2e.go:724: Step 'kubectl version' finished in 273.874µs
15:47:56 2017/01/06 23:47:56 e2e.go:722: Running: get status
15:47:56 ./hack/e2e-internal/e2e-status.sh: line 28: ./hack/e2e-internal/../../cluster/kube-util.sh: No such file or directory
15:47:56 2017/01/06 23:47:56 e2e.go:724: Step 'get status' finished in 2.90292ms
15:47:56 2017/01/06 23:47:56 e2e.go:180: Something went wrong: encountered 2 errors: [error running kubectl version: fork/exec ./cluster/kubectl.sh: no such file or directory error running get status: exit status 1]
15:47:56 exit status 1
```

**Comment by spiffxp** [comment]
1.5.x e2e tests run now; they're still failing, unclear whether that's flakes or a change in expected behavior

https://pipelet.kubeme.io/job/k2-e2e-aws-k8s-conformance/108/ and https://pipelet.kubeme.io/job/k2-e2e-aws-k8s-conformance/109/ have the same e2e failures, but without a few more runs that's not saying much

**Comment by spiffxp** [comment]
Consistently seeing failures of the following e2e tests
```
Kubernetes e2e suite.[k8s.io] Networking [k8s.io] Granular Checks: Pods should function for node-pod communication: http [Conformance]
Kubernetes e2e suite.[k8s.io] Networking [k8s.io] Granular Checks: Pods should function for node-pod communication: udp [Conformance]
Kubernetes e2e suite.[k8s.io] Networking [k8s.io] Granular Checks: Pods should function for intra-pod communication: udp [Conformance]
Kubernetes e2e suite.[k8s.io] Networking [k8s.io] Granular Checks: Pods should function for intra-pod communication: http [Conformance]
```

Maybe something about k2's networking setup needs to be revisited to support these new tests.  1.4 didn't have separate cases for http vs udp

**Comment by coffeepac** [comment]
This is (probably) not a networking issue.  Seems to be a scheduling issue.

> It] should function for intra-pod communication: udp [Conformance]
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/common/networking.go:45
STEP: Performing setup for networking test in namespace e2e-tests-pod-network-test-0l73t
STEP: creating a selector
STEP: Creating the service pods in kubernetes
Jan 17 15:10:10.681: INFO: Waiting up to 10m0s for all (but 0) nodes to be schedulable
Jan 17 15:11:11.557: INFO: Unexpected error occurred: timed out waiting for the condition
[AfterEach] [k8s.io] Networking
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:142
STEP: Collecting events from namespace "e2e-tests-pod-network-test-0l73t".
STEP: Found 6 events.
Jan 17 15:11:12.080: INFO: At 2017-01-17 15:10:11 -0800 PST - event for netserver-0: {default-scheduler } FailedScheduling: pod (netserver-0) failed to fit in any node
fit failure summary on nodes : MatchNodeSelector (6)
Jan 17 15:11:12.080: INFO: At 2017-01-17 15:10:11 -0800 PST - event for netserver-1: {default-scheduler } FailedScheduling: pod (netserver-1) failed to fit in any node
fit failure summary on nodes : MatchNodeSelector (6)
Jan 17 15:11:12.080: INFO: At 2017-01-17 15:10:11 -0800 PST - event for netserver-2: {default-scheduler } FailedScheduling: pod (netserver-2) failed to fit in any node
fit failure summary on nodes : MatchNodeSelector (6)
Jan 17 15:11:12.080: INFO: At 2017-01-17 15:10:11 -0800 PST - event for netserver-3: {default-scheduler } FailedScheduling: pod (netserver-3) failed to fit in any node
fit failure summary on nodes : MatchNodeSelector (6)
Jan 17 15:11:12.080: INFO: At 2017-01-17 15:10:11 -0800 PST - event for netserver-4: {default-scheduler } FailedScheduling: pod (netserver-4) failed to fit in any node
fit failure summary on nodes : MatchNodeSelector (6)
Jan 17 15:11:12.080: INFO: At 2017-01-17 15:10:11 -0800 PST - event for netserver-5: {default-scheduler } FailedScheduling: pod (netserver-5) failed to fit in any node

Trying to find the resource (or node label) that is failing to let this run.

**Comment by coffeepac** [comment]
this is happening because of how we name our nodes vs how we tag the hostname.  observe
`NAME                           STATUS                     AGE       LABELS
ip-10-0-113-11.ec2.internal    Ready                      5h        beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=c4.xlarge,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=us-east-1,failure-domain.beta.kubernetes.io/zone=us-east-1c,kubernetes.io/hostname=10.0.113.11`

That is the first line of a 'get nodes --show-labels' command.  You'll notice the Name column is 'ip-10-...' and yet the value of kubernets.io/hostname (last key/value pair in the labels list' is 10.0.113.11.

These four tests assign pods to nodes based on those two values agreeing (ie, the test does a lookup of all nodes by Name, chooses some, and creates pod specs with a nodeSelector against the label'. 

I will go see how these values are being assigned and why they are different.

**Comment by coffeepac** [comment]
kubernetes.io/hostname is assigned by kubernetes.  I have a vague suspicion we forced hostname to be the DNS name instead of IP address for a Reason.  Hunting it down now.

**Comment by coffeepac** [comment]
the hostname (from a random cluster node) is:  ip-10-0-66-42.pac-bag.internal 

sure.

**Comment by coffeepac** [comment]
manual test:  updated the labels (kubernetes.io/hostname) to agree with the 'NAME' value from get nodes output.  all tests passed.  so our actual kubernetes configuration is fine but we have some labeling issue.

**Comment by coffeepac** [comment]
I see the following line in the template for kubelet:

>       --hostname-override=${DEFAULT_IPV4} \

Same line appears in the resolved file on disk.  Its an environment variable but it appears to be unset.  going to go find out what the environment looks like when this starts.

**Comment by coffeepac** [comment]
kubernetes seems to be ignoring the --hostname-override setting and is only reporting the internal DNS name.  the internal DNS was the hostname at one point but it isn't anymore.  buh.

**Comment by coffeepac** [comment]
kubelet seems to only read the --hostname-override setting on node creation.  I removed the setting and am now seeing this:

> ip-10-0-96-112.ec2.internal    Ready                      17m       beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=c4.xlarge,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=us-east-1,failure-domain.beta.kubernetes.io/zone=us-east-1c,kubernetes.io/hostname=ip-10-0-96-112.pac-bag.internal

Which means the cli flag is for altering the label and not the top level key.  Its also possible that the cli doesn't operate in label overwrite mode so any changes after creation are ignored.  

I don't know where the first column is coming from though.  I'm not sure how to set that either.

**Comment by coffeepac** [comment]
removing the --hostname-override flag sets the tag to be only the first segment of the private DNS (ie ip-10-0-33-190 or something) and not something routeable (ie ip-10-0-33-190.ec2.internal).  Tiller uses the tag for host lookup, probably why we were overriding the flag to be the ip address in the first place.

seems like something in the creation of the cluster is saving off these useless dns fragments as I can't get kubedns to install now.

**Comment by coffeepac** [comment]
gotta run now, but tomorrow:  check to see if updating the NETWORK config file to include the private DNS FQDN of the aws node works to make this jibberish run.  because it smells like the aws provider is forcing the node's name in `get nodes` to be the private DNS entry:  https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/aws/aws.go#L3224

which is implying that all node name lookups occur against the AWS ec2 api based on privateDNS name.  if so, this is a bug with the AWS provider and I would like to see how they manage to pass conformance tests.

**Comment by coffeepac** [comment]
seems like the answer is the following:
- stop using the cluster name as part of the VPC domain
- don't override the hostname

We should be able to do both of these things and still be able to pass conformance tests.  alas, poor yorrick, we cannot.

**Comment by coffeepac** [comment]
Gotten  the same two failures in row (new):

> Fail] [k8s.io] Secrets [It] should be consumable from pods in volume as non-root with defaultMode and fsGroup set [Conformance]
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/util.go:2167

[Fail] ThirdParty resources [Flaky] [Disruptive] Simple Third Party [It] creating/deleting thirdparty objects works [Conformance]
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/third-party.go:173

Going to go investigate these now.

**Comment by coffeepac** [comment]
this looks good.  going to push a run through pipelet.  if that works I'll flip the official version over.

**Comment by coffeepac** [comment]
having trouble with tiller coming up in time again.  I'll sort this out tonight or tomorrow.

**Comment by coffeepac** [comment]
the trouble is that I have failed to pick up all of the settings that make this work.  I still have a functioning image but I no longer seem to have the change to build it.  nuts.

**Comment by coffeepac** [comment]
This is a us-west-2 flake.  Sure.

**Comment by coffeepac** [comment]
got a [good run](https://pipelet.kubeme.io/job/k2-e2e-aws-k8s-conformance/150/) using us-east-1.  pure flail there.  once a default run goes through I'll send this off for review.

**Comment by coffeepac** [comment]
[default run](https://pipelet.kubeme.io/job/k2-e2e-aws-k8s-conformance/155/) has gone through.  

@spiffxp can you please take a look at the linked job and make sure its good to go?  There are still intermittent failures getting a run to succeed so if you do re-run it you gotta give it a few shots.  we are working on that.
