### ISSUE TITLE
create production K2 common tools cluster

### ISSUE THREAD

**Issue by coffeepac** [samsung-cnct/k2#173]
create a k2 cluster using k2cli that we (common tools team) will operate as our production cluster.  This cluster should use our e2e conformance config as a base and be scaled up to fit the following charts:
- central-logging
- kube-dashboard
- authorization plugins as described in the internal wiki

**Comment by coffeepac** [comment]
cluster is up and running.  will push configs up to S3 tonight so there is some access for others.

will be working on getting @keyolk 's authorization work integrated.  going to use dex + github ids for authorization.  woo.

**Comment by coffeepac** [comment]
tearing the cluster down.  there are several API server flags required for this that have to be present at cluster creation.

**Comment by coffeepac** [comment]
brought up a cluster with github OIDC and rbac.  didn't provide a username for the rbac super user.  whoops.  trying again with admin as the rbac super user.  

behavior seen:  
- kubectl logged in as admin was unable to access any resources in the cluster
- api and master nodes had logs full of 'unable to talk to master node, EOF, connection reset'

**Comment by coffeepac** [comment]
allllmost there.  tracked down another bug (will submit a PR for this all at once) but now I've got a bad referrer uri set somewhere.  going to try a cluster down and up to see if its just a leftover from some of my thrashing.

**Comment by coffeepac** [comment]
its GitHub not Github.  helm is case sensitive.

I've got the correct values going through to helm and the dex chart now but the secret is being created with the raw data instead of the base64 value.  this is a problem because the pod will attempt to decode the string which generates a bunch of non-printable chars and is wrong.

**Comment by coffeepac** [comment]
great success!  now using the correctly configured samsung github auth integration.  now have a valid token and will start setting up RBAC rules.

**Comment by coffeepac** [comment]
default action for a github user is admin rights.  huh.

**Comment by coffeepac** [comment]
ToReview:
- reviewers should follow the steps in the listed wiki page to access the production cluster

**Comment by coffeepac** [comment]
@leahnp to review

**Comment by leahnp** [comment]
Did you want me to try and log into the cluster again? @coffeepac

**Comment by coffeepac** [comment]
nope, I haven't had time for this in awhile.  Should probably go back to in progress.  In fact, I shall move it now.

**Comment by coffeepac** [comment]
due to work that happened in #290 I trashed the etcd clusters.  this means we've lost the state of the kubernetes cluster.  We don't have a way of bringing it back up right now so I'm destroying the cluster and we'll bring it back later.

this does suggest the following items:
- building a --dry-run for 'cluster up'
- *not* using 'cluster up' to upgrade the cloud-configs but creating a special purpose tag that is part of any upgrade tag

**Comment by coffeepac** [comment]
cluster is back up.  in the same state as it was before:
- single user (me) works just fine
- all other users (including other test accounts from  me) don't work

possible problems
- account needs a certain level of authority in the github org (would be nice!)
- something odd is hardcoded to my email address (possible, but been looking and unable to find it)

**Comment by coffeepac** [comment]
okay!  directions updated.  should be good to go.

ToReview:
- follow instructions [here](https://hanjin.atlassian.net/wiki/display/CoT/Production+Kubernetes+Cluster) to create an account on the production cluster

**Comment by leahnp** [comment]
<img width="623" alt="screen shot 2017-04-07 at 8 13 27 am" src="https://cloud.githubusercontent.com/assets/13352646/24799614/2ba74862-1b6a-11e7-892b-dfab255c230c.png">
Boom! 
Just added one more comment to the confluence page, otherwise seems to be working, nice job!

**Comment by coffeepac** [comment]
Positive review, second user is coming on board now.  Any further work against the production cluster should have a fresh issue.
