### ISSUE TITLE
Document kraken_config variable expansion

### ISSUE THREAD

**Issue by davidewatson** [samsung-cnct/k2#179]
The ansible playbook (ansible/roles/kraken.config/tasks/main.yml) which sets facts derived from the k2 config file (e.g. ~/.kraken/config.yaml) should be better documented. In particular the expand_config filter (cf. ansible/roles/kraken.config/filter_plugins/expand_config.py) should be explained. This will reduce the bar of entry to k2 development. While there is currently some documentation in the Documentation directory, with rare exception, the README's in the source directory are stubs which need to be either fleshed out or removed.

**Comment by coffeepac** [comment]
closed as part of k2recon
