### ISSUE TITLE
$HOME no longer works at all in config.yaml

### ISSUE THREAD

**Issue by joejulian** [samsung-cnct/k2#181]
Part of preventing writing to the user's home directory was to make k2 use a tempdir for $HOME for applications that don't allow configuration changes by any means.

This breaks config.yaml references that use $HOME.

**Comment by joejulian** [comment]
I have considered creating a new environment variable, `K2HOME`, which would work in config.yaml whether k2 is running in docker, or running locally for development.

@davidewatson has argued that this will just add confusion and I tend to agree with him.

I think, and @davidewatson seems to agree, the best solution here is to revert #170 and instead only bind mount the actual files we need into the container instead of all of `$HOME`.

**Comment by coffeepac** [comment]
@joejulian This is probably the best route.  If we're pushing people to use k2cli we can only bind mount in the three dirs we need.

**Comment by joejulian** [comment]
Or, even better, only the files actually needed. An end user doesn't necessarily want to trust our docker container with their entire .ssh directory. This allows they to put their own rsa keys and aws configs in even a single directory and we'll still put them where K2 needs them.
