### ISSUE TITLE
K2 rbac configuration

### ISSUE THREAD

**Issue by coffeepac** [samsung-cnct/k2#184]
We are currently using the following in our API-server-manifest:

`    - --authorization-rbac-super-user={{ kraken_config.kubeAuth.authz.rbac.super_user }}`

This is being [removed in v1.6](https://kubernetes.io/docs/admin/authorization/).  We need to switch to using the user bootstrapping method

**Comment by leahnp** [comment]
I am not able to bring up a cluster with security enabled, I am running into this error:

 `"DexApp": {"RedirectUri": "http://common-tools.kubeme.io:30080/callback"}}, "version": "0.1.0"}, "msg": "RepresenterError: cannot represent an object: Dex"}`

I believe I might be hitting this bug: https://github.com/openshift/openshift-ansible/issues/3111

But when I try to roll back my ansible version to test it, I hit another big with ELB 'none types'. 

Can we punt this until ansible releases their next stable version or until we are upgrading to K8s 1.6?

**Comment by coffeepac** [comment]
@leahnp its concerning that we currently can't bring up a new kubernetes cluster with our security enabled.  however, this isn't part of our e2e tests or our generated configuration.  I'm okay with punting on this for a bit.  feel free to un-assign and move back to ToDo

**Comment by coffeepac** [comment]
this should be resolved in ansible with the design spec as laid out here: https://github.com/samsung-cnct/k2/issues/222#issuecomment-284583580

there should be folders created for 1.4 and 1.5 to contain the current template.

**Comment by coffeepac** [comment]
DexApp install error fixed with: https://github.com/samsung-cnct/k2-tools/pull/32

**Comment by DStorck** [comment]
When this gets completed, please update kubeauth.md  in k2/documentation/kraken-configs

**Comment by mikeln** [comment]
v1alpha1 --> v1beta1  in 1.6

**Comment by mikeln** [comment]
working through stuff

**Comment by mikeln** [comment]
k2/ansible/roles/kraken.readiness/filter_plugins/expected_masters.py  has issues...
mainly it references `total_masters` when it should be `total_nodes`.

**Comment by mikeln** [comment]
Separating RBAC and Cert Gen out of kraken.readiness role  into its own role.

**Comment by mikeln** [comment]
The 1.6 cluster will come up ok with the default rbac (which is how it should be).
the main issue is getting the correct initial rbac permssions for kubectl so it can install our rbac specifications, and allow it to control the system.

The default user for kubectl has very very limited access.  It is a little unclear the correct way to get it to use the `system:masters`  (default cluster-admin) role.   Some examples use --token=<user>/<rbac role> in kubectl, but we do not currently use token authorization.  We use basic_auth <user/pw> and it is unclear how to associate the default rbac with that.   Perhaps it is as easy as using whatever the default system user defined for that role...though we don't know the password.

**Comment by mikeln** [comment]
liggitt [10:39 AM] 
You'd want to give your bootstrap superuser (whatever authentication method you use... passwordfile, x509 cert, etc) the `system:masters` group

[10:40] 
Then let them delegate out permissions to lesser users (if you have lesser users) by creating the appropriate rolebindings

**Comment by mikeln** [comment]
added system:masters to basic_auth CSV user...
got "kraken-ca" not authorized.
added 0=system:masters to csr CA and end user cert
got "system:anonymous" not authorized, and the frabric didn't come up.

**Comment by mikeln** [comment]
fixed CSR org correctly.   success accessing things but now the nodes have issues:
```
I0515 23:41:44.601043       1 wrap.go:75] GET /api/v1/services?resourceVersion=0: (266.829µs) 403 [[hyperkube/v1.6.2 (linux/amd64) kubernetes/477efc3] 10.0.244.127:3978]
I0515 23:41:44.602211       1 rbac.go:87] RBAC DENY: user "kube-worker" groups [system:authenticated] cannot "list" resource "pods" cluster-wide
```

**Comment by mikeln** [comment]
hmm, may have to install the new rbac (via kubectl) before all the Node comes up.

**Comment by mikeln** [comment]
Seems to work. Installing our rbac as soon as as kubectl can.

**Comment by mikeln** [comment]
getting DNS service running:
```
mikeln-bender:.kraken Mikel_Nelson$ kubectl --kubeconfig=/Users/mikel_nelson/dev/cloud/k2new/myconfig/.kraken/mikeln-rb1/admin.kubeconfig --namespace=kube-system get events
LASTSEEN   FIRSTSEEN   COUNT     NAME                  KIND         SUBOBJECT   TYPE      REASON              SOURCE                  MESSAGE
3m         6m          16        kube-dns-3064739190   ReplicaSet               Warning   FailedCreate        replicaset-controller   Error creating: pods "kube-dns-3064739190-" is forbidden: service account kube-system/kube-dns was not found, retry after the service account is created
24s        1m          15        kube-dns-3064739190   ReplicaSet               Warning   FailedCreate        replicaset-controller   Error creating: pods "kube-dns-3064739190-" is forbidden: service account kube-system/kube-dns was not found, retry after the service account is created
6m         6m          1         kube-dns              Deployment               Normal    ScalingReplicaSet   deployment-controller   Scaled up replica set kube-dns-3064739190 to 1
2m         2m          1         kube-dns              Deployment               Normal    ScalingReplicaSet   deployment-controller   Scaled down replica set kube-dns-3064739190 to 0
1m         1m          1         kube-dns              Deployment               Normal    ScalingReplicaSet   deployment-controller   Scaled up replica set kube-dns-3064739190 to 1
```

**Comment by mikeln** [comment]
wierd error after fixing above (had to add namespace to the service account creation)

 ```
1m		1m		1	default-scheduler							Normal		Scheduled	Successfully assigned kube-dns-3064739190-55d5f to ip-10-0-78-24.us-west-2.compute.internal
  1m		1m		1	kubelet, ip-10-0-78-24.us-west-2.compute.internal			Warning		FailedSync	Error syncing pod, skipping: failed to "CreatePodSandbox" for "kube-dns-3064739190-55d5f_kube-system(d8a1437b-3a83-11e7-ba49-0660efccf048)" with CreatePodSandboxError: "CreatePodSandbox for pod \"kube-dns-3064739190-55d5f_kube-system(d8a1437b-3a83-11e7-ba49-0660efccf048)\" failed: rpc error: code = 2 desc = NetworkPlugin cni failed to set up pod \"kube-dns-3064739190-55d5f_kube-system\" network: failed to find plugin \"loopback\" in path [/opt/loopback/bin /etc/cni/net.d]"

  1m	3s	6	kubelet, ip-10-0-78-24.us-west-2.compute.internal		Normal	SandboxChanged	Pod sandbox changed, it will be killed and re-created.
  1m	3s	6	kubelet, ip-10-0-78-24.us-west-2.compute.internal		Warning	FailedSync	Error syncing pod, skipping: failed to "KillPodSandbox" for "d8a1437b-3a83-11e7-ba49-0660efccf048" with KillPodSandboxError: "rpc error: code = 2 desc = NetworkPlugin cni failed to teardown pod \"kube-dns-3064739190-55d5f_kube-system\" network: failed to find plugin \"flannel\" in path [/etc/cni/net.d /opt/flannel/bin]"
```

**Comment by mikeln** [comment]
https://github.com/kubernetes/kubernetes/issues/43014

**Comment by mikeln** [comment]
Fabric needed some changes for 1.6.  This was causing issues with KubeDNS.

**Comment by mikeln** [comment]
Running tests using Cassandra deployed via Helm.  Comes up and runs ok!
However, deleting the helm chart failed...left the cassandra pods there (2 unknown, 2 running)
and the statefulset.   Attempting to delete the statefulset...appears to be the problem.  Doing it by hand via kubectl (the helm chart was already gone, so impossible to use helm to retry the delete):
```
mikeln-bender:k2 Mikel_Nelson$ kubectl --kubeconfig=/Users/mikel_nelson/dev/cloud/k2new/myconfig/.kraken/mikeln-rb1/admin.kubeconfig --namespace=cassandra delete statefulsets/cassandra-wanton-turk
error: timed out waiting for "cassandra-wanton-turk" to be synced
```
The statefulset also seemed to think there were only 2 pods associated still (vs the 4):
```
NAMESPACE   NAME                                 DESIRED   CURRENT   AGE
cassandra   statefulsets/cassandra-wanton-turk   0         2         59m
```
```
NAMESPACE         NAME                                                                   READY     STATUS     RESTARTS   AGE
cassandra         po/cassandra-wanton-turk-0                                             1/1       Unknown    0          25m
cassandra         po/cassandra-wanton-turk-1                                             1/1       Running    0          57m
cassandra         po/cassandra-wanton-turk-2                                             1/1       Running    0          55m
cassandra         po/cassandra-wanton-turk-3                                             1/1       Unknown    0          24m
```

Deleted the pods by hand first, then the statefulset by hand.  That cleaned it up.

**Comment by mikeln** [comment]
Initial Integration PR #469

**Comment by coffeepac** [comment]
looks good, several green runs from master with 1.6 and rbac
