### ISSUE TITLE
create jenkins-ci project plan

### ISSUE THREAD

**Issue by coffeepac** [samsung-cnct/k2#189]
our current jenkins CI system (kraken-ci) is unmaintained, based on jenkins v1 and the instructions to rebuild no longer work.  we are going to abandon this project in favor of using a kubernetes-based jenkins build system built on jenkins v2.

this ticket will cover the basic planning and initial tickets for the new ci system

**Comment by coffeepac** [comment]
This should use the new CI system as being developed by the zonar client engagement team.  it should start with importing the following repos:
 - zonar-pipeline
 - zonar-pipeline-library
 - zonar-jenkins-base

will be important to scrub zonar specific items.  as a first pass don't worry about making it fully generic, just get it running.  we will make it generic later.

**Comment by coffeepac** [comment]
it seems like I should be able to deploy jenkins using jenkins-base, then futz with the new -pipeline repo (zonar-repo -> k2-repo(?)) to add some tester jobs.

open question:  what about CI jobs that shouldn't end with a helm chart?

**Comment by coffeepac** [comment]
there is a bunch of gke/google cloud information hardcoded into this setup.  it makes sense for zonar but this may be a slightly larger disentanglement project then I expected.

**Comment by coffeepac** [comment]
this is a very large and fluid project right now.  it also doesn't support what we (common tools) need from a CI system.  In my current cough medicine haze I may try and futz with some other things but until the zonar team ships this I'm not interested in plowing much effort into it.

**Comment by coffeepac** [comment]
going to take a look at:
- travis CI on prem
- bamboo
- concourse CI

**Comment by coffeepac** [comment]
travis CI doesn't seem to have an freely available self hosted vesion.  bamboo also doesn't seem to be free. 

concourse install was a snap.  going to try and get K2 building there tomorrow morning.  if it works, might just keep going with it.  need to sort out how the builds are run, ie:  if concourse is making docker calls directly or if it is creating pods or jobs or something for the builds.

**Comment by coffeepac** [comment]
after some poking and prodding I should have a usable k2 pipeline running in concourse this afternoon.  this looks like its going to be dumb easy so I'm tentatively going to say 'we're using this' and I'm going to go plan out some other projects instead for now.

**Comment by coffeepac** [comment]
got k2 working just fine. it was all pebcak.

attempting to get the non-supported github PR resource working.  my first naive attempt is not succeeding but the basic model is that you specify the resource_type which includes either a docker image location or a source repo and you let concourse pull the plugin down.  that seems awesome if I can get it to work cleanly in k8s.

**Comment by coffeepac** [comment]
I have some background work to do before we go any further on this.  Need to make sure this project lines up with what we're all about and is a good chunk better then our current system.

**Comment by coffeepac** [comment]
background work complete.  first discussion complete.  should have another conversation next week.  we will get a strategy and at least a full medium term plan out of it

**Comment by coffeepac** [comment]
ToDo when issue complete:  go through k2, k2cli and careen p2-backlogs and start moving all CI related tickets to p1 or at least onto the board.

**Comment by coffeepac** [comment]
got a jenkins 2.0 version running locally in docker and it was fine.  I expect the zonar jenkins-base image will also work when I try that.

I was unable to get a job to fire off though.  I was hitting an issue with the first groovy class import.  The one from the jenkins example docs.  This does not fill me with a great amount of confidence in this tool.  

however, I believe I have created a useful sample project with a sample Jenkinsfile for later usage so this was a useful learning period.  I also learned a bit about jenkins management in general which is never a waste.  However, results remain inconclusive.

**Comment by coffeepac** [comment]
simple first pass is probably:
- jenkins-base from zonar team (will then be part of common-tools)
- hand rolled configs with as much of the job information stored in the code (ie:  have the jenkins job call a shell script in the repo)
- nginx ingress controller
- kube-lego for SSL certs
- profit

**Comment by coffeepac** [comment]
things completed today:
- nginx-ingress controller installed
- kube-lego installed
- both of the above configured to work with rbac

next things to complete:
- install jenkins-base (should be a helm chart somewhere)
- configure kube-lego secured ingress for jenkins-base
- configure jenkins-base to use jenkins kubernetes job launcher as kubernetes jobs
- configure sample job (in go)
- start porting pipelet jobs

There is probably two or three days of work left here.  Will then need to document as odds are high we are going to trash the production cluster a bunch as we learn what we're doing.

**Comment by coffeepac** [comment]
Need to figure out how to add worker jobs as build agents.  will try and do that tomorrow.

**Comment by coffeepac** [comment]
Where work is being done:
jenkins configs:  https://github.com/coffeepac/charts/pull/1
kube-lego/nginx-ingress:  https://github.com/coffeepac/kube-lego/pull/1

**Comment by coffeepac** [comment]
the parameters being passed into the slave jenkins pods are being duplicated.  Error message:

> two arguments required, but got [36e66654dab68a4e6de72b69380ec64635be8a7500a819b2ea495f6c47563ac1, kubernetes-f34eba4e5cd84baaa74bcd9f8880fd90-1c7299e3825f6, 36e66654dab68a4e6de72b69380ec64635be8a7500a819b2ea495f6c47563ac1, kubernetes-f34eba4e5cd84baaa74bcd9f8880fd90-1c7299e3825f6]

looks like the system should only be providing the first two and not doubling them up.

**Comment by coffeepac** [comment]
Was able to complete a job end to end!  The steps included are:
- checkout a go project
- build the go project
- test the go project
- a debugging step
- build a docker image for the project
- push the docker image to quay

the build, test, docker build and docker push steps were all accomplished via shell commands in a Jenkinsfile checked into the project.  This covers everything I was trying to do with concourse so woo.  

I am now ready to start porting jobs from pipelet over.  Almost, I still need to setup some webhooks to make sure things happen on commit pushes and PR merges but that, I think, is well understood.

**Comment by coffeepac** [comment]
oh, jenkins server:  https://common-jenkins.kubeme.io ask @coffeepac for credentials

**Comment by coffeepac** [comment]
PRs are being built, extraneous branches are not.  This is running on a stock job config.

Events aren't being sent from github->jenkins yet.  I think I need to setup a webhook but haven't found quite the right incantation yet.

**Comment by coffeepac** [comment]
@joejulian sorted out the needed webhook.  super easy.  the process to add a new job is:
- create a multibranch project in jenkins
  - need to use some auth
  - specify the owner/project
- add a Jenkinsfile to the project
- add a webhook to the project in github that points to https://common-jenkins.kubeme.io/github-webhook/

I'm mostly done porting over k2 now.  Need to sort out how to do different things on PR vs master commit, slack notifications and e2e tests.

**Comment by coffeepac** [comment]
this is good enough to demo.  Will demo tomorrow to team.

**Comment by coffeepac** [comment]
demo complete:  good to go!  going to add some productiony things:
 - robot users
 - samsung_cnct/k2
 - delete the sample projects
 - issues for any other projects we need to add (k2-charts, k2-tools, etc)

that's good enough to open a PR against master.  if I have time I'll open a PR against k2recon as well.

**Comment by coffeepac** [comment]
it seems it is not possible to run the e2e tests in the current k2-tools container.  e2e steps involve bringing in a specific version of ginkgo that we can't control (ie checked in binary).  this binary is using a lib loader that alpine doesn't have.  

options:
 - change the base container for k2-tools
 - step into a new container for the e2e tests that has this lib loader

drawbacks from one:
 - requires a fairly massive change to k2-tools and k2
 
drawbacks from two:
 - may not be possible inside of the try/catch block

I prefer option two so that's what I'll start hunting down, its least invasive to k2 as a whole.

**Comment by coffeepac** [comment]
option two worked.  woo!

need to create a repo for the e2e-tester image

**Comment by coffeepac** [comment]
two issues are cropping up right now:
1. e2e tests are failing without any interesting/useful error message.  I am debugging this by spinning the jenkins worker pod up manually so I can iterate without jenkins destroying my work surface
2. exiting from the e2etester container and returning to the main flow of the jenkinsfile is causing an issue and the destroy isn't firing.  I'm trying to embed a direct call back using the k2-tools container in the finally.  if that fails I dunno.

**Comment by coffeepac** [comment]
1. the e2etester image I created is missing aws.  This is a decent sized problem as installing aws requires pip, python2 and a bunch of dev libs.  I'm going to craft a new base image based on some large OS instead of a minimal thing.  
2. remains a problem!  unsure what to do about it.  could require some serious gymnastics or putting all container{} specifications at the same level.  we'll see!

**Comment by coffeepac** [comment]
and now I've lost outbound connectivity on pods in the common tools cluster.  huh.

**Comment by coffeepac** [comment]
had some cruft laying around that's not visible from the web console.  I think its a policy doc.  got around by using a new cluster name.  

got the e2e tests to run!  but now they're existing and providing no error message.  I'm not particularly enthused.  I'm going to take a quick look and see what the old execution environment is and see if I can use that instead.  this is getting ridiculous.

**Comment by coffeepac** [comment]
the canal pod has died on the node that is hosting my trial pod.  this is twice in a row.  I smell a problem.

**Comment by coffeepac** [comment]
we have a configuration problem in K2:  emptyDirs are being created in the root partition in the common-tools cluster.  this is causing the node to run out of disk and, I suspect, causes the daemonSets to exit.

**Comment by coffeepac** [comment]
Used the same image that jenkins used.  it worked. going to make sure it works in my tester pod then switch over to using that int he Jenkinsfile.  if *that* works (and by works I mean successfully run the e2e test) I'll push this as a PR

**Comment by coffeepac** [comment]
Got the image down to being based on an upstream debian-jessie scm buildpack.  should be fine.  there's still a bunch of guff being installed that I don't understand but we're not installing java8 or jennkins so good enough for now.  

once I get a valid e2e run, this goes to master and I'll clean up the current jenkins job list to not have the sample stuff.

**Comment by joejulian** [comment]
:trumpet:

**Comment by coffeepac** [comment]
whomp-whomp.  still can't get the e2e to start, there seems to be a gsutil issue.  probably because (i'm just realizing) I didn't change the tag so if the pod landed on the same physical node the image wouldn't get pulled again.

upside:  specifying the k2-tools container to wrap the destroy call is has cleared the directory creation areas.  so that's a positive.

**Comment by coffeepac** [comment]
I seem to have a functioning image for running e2etests and I've added it to the build-scripts directory in k2.  It probably needs its own CI job but we can discuss that later.  Right now its a manual build and says so.

next steps:
 - get a clean run using the built-from-k2 e2etester image
 - lay out the other issues needed for the rest of this plan
   - issues for which jobs to port
   - cleanup of this job
 - create new job based on samsung_cnct/k2 instead of my fork

**Comment by coffeepac** [comment]
ToReview:
 - there is a new CI system running in the common tools production cluster
    - verify by checking the following
        - https://common-jenkins.kubeme.io/ points to IPs in the common tools cluster running in aws in us-east-1
        - check that there is a jenkins pod running in the common-jenkins namespace
           -  see https://hanjin.atlassian.net/wiki/display/CoT/Production+Kubernetes+Cluster for access
  - there is a K2 job that executed e2e tests that ended in flakes
    - check https://common-jenkins.kubeme.io/job/k2-trial/job/jenkins-2.0/141/console and verify the error is from a conformance test and not conformance test setup
  - check that tickets exist to port k2-charts CI job
  - check that tickets exist to create k2-tools and k2cli CI jobs

**Comment by davidewatson** [comment]
I have done everything here except find a ticket to port k2-charts CI job.

**Comment by DStorck** [comment]
There are jenkins pods there, but they don't seem too happy: ```DStorck~/.kube$ kubectl get pods --all-namespaces
NAMESPACE         NAME                                                        READY     STATUS              RESTARTS   AGE
common-jenkins    common-hudson-jenkins-1549779338-c83x2                      1/1       Running             0          33d
common-jenkins    kubernetes-4bd0b92014f14e5db2099885414b8294-b78f49e3d0d44   3/4       Error               0          3d
common-jenkins    kubernetes-f915280a451445049566c384abc58967-b78644731e215   3/4       Error               0          3d```

**Comment by DStorck** [comment]
What am I looking for to be able to discern if the jenkins test is failing for conformance reasons and not from conformance test setup?

**Comment by leahnp** [comment]
I second the last 3 comments.

**Comment by DStorck** [comment]
Okay I'm going to guess that that the 'check that it failed from conformance test' is investigating why it failed, and seeing that it looks like (as per usual) there was some error on the way down trying to destroy the vpc. So we are happy that the test ran successfully and showed a failure, but it was an expected failure, and the test as expected?

**Comment by guineveresaenger** [comment]
Seein the same jenkins pods being unhappy.

**Comment by coffeepac** [comment]
K2 charts porting tickets.
Original:  https://github.com/samsung-cnct/k2/issues/395 (whoops)
Correct Repo: https://github.com/samsung-cnct/k2-charts/issues/85

**Comment by coffeepac** [comment]
Unhappy jenkins pods:  this is a bummer but the resolution is to destroy the pod.  I have.  We will need a maintenance job that periodically reaps error'd jenkins pods (#420)

**Comment by coffeepac** [comment]
'check if it failed from conformance test' is to take a look in the console log output, find the error and see what happened.  its a fairly labor intensive process and maybe signals that this system isn't quite ready yet.  I'm  going to spend a bit of time right now to see if I can get the test results to publish.  that should help.

**Comment by coffeepac** [comment]
it seems that GKE clusters can't have capital letters in their name.  need to verify this.  if true, I need to lowercase all letters in the cluster name setting script.

**Comment by coffeepac** [comment]
PR to fix naming of GKE clusters has been merged. 

there is a bug in the conformance test shell script.  the tests are, occasionally, passing.  need to go fix that bug now then we should be able to get passing conformance runs at the same rate as pipelet.

**Comment by coffeepac** [comment]
Jenkinsfile command 'checkout scm' is checking out the wrong version of code.  o.0

**Comment by coffeepac** [comment]
e2e tests are now running in the PR version.  There is a lower-case name requirement as part of GKE cluster creation.  I had missed updating the cluster name generation in a shell script.  its been updated now.  

the tests failed (flakes) but as soon as it works I'll link it here.

**Comment by coffeepac** [comment]
ToReview:
 - there is a new CI system running in the common tools production cluster
    - verify by checking the following
        - https://common-jenkins.kubeme.io/ points to IPs in the common tools cluster running in aws in us-east-1
        - check that there is a jenkins pod running in the common-jenkins namespace
           -  see https://hanjin.atlassian.net/wiki/display/CoT/Production+Kubernetes+Cluster for access
           - command:  `kubectl get pods --namespace common-jenkins`
  - there is a K2 job on the master branch that has passed
    - master job: https://common-jenkins.kubeme.io/job/K2/job/master/
      - specific successful job:  https://common-jenkins.kubeme.io/job/K2/job/master/9/
  - check that ticket exists to port k2-charts CI job
  - check that ticket exists to create k2-tools and k2cli CI jobs

**Comment by NathanZook** [comment]
LGTM
