### ISSUE TITLE
[Bare Metal Provider] Spec gathering task

### ISSUE THREAD

**Issue by cwazy1** [samsung-cnct/k2#19]
Gather user requirements and specs for bare metal. Reference Aaron for his bare metal work for Fidelity.

**Comment by coffeepac** [comment]
User Requirement:  create a k8s cluster that passes conformance tests as defined in the Jenkins job.  We are making a commitment to using MaaS for hardware control and identification which helps wipe away a bunch of the bootstrapping complexities.
