### ISSUE TITLE
tpc provider: terraform templates

### ISSUE THREAD

**Issue by joejulian** [samsung-cnct/k2#198]
Attempt to follow the design of the aws terraform templates (see `aws-template.yaml`) to build a template to terraform using the triton resources.

This is a tracking issue for the following:
- [ ] vpc #193
- [ ] keypair (= key) #194
- [ ] subnet (= fabric) #195
- [ ] cluster_secgroup (= firewall) #196
- [ ] etcd (= machine) #197
- [ ] master (= machine) #197
- [ ] node (= machine) #197

**Comment by coffeepac** [comment]
is blocked by #258
