### ISSUE TITLE
k2 should allow a custom version of docker to be installed

### ISSUE THREAD

**Issue by davidewatson** [samsung-cnct/k2#205]
Currently careen generates custom docker builds. k2 should be able to use these artifacts to run a custom version of docker.

**Comment by coffeepac** [comment]
ToReview:  have someone other then @davidewatson use the custom version of docker

**Comment by davidewatson** [comment]
To complete this:

1) Add

```
type: tgz
url: https://s3-us-west-2.amazonaws.com/samsung-cnct/artifacts/docker/v1.12.x/docker-1.12.6%2B7ab89465.tgz
```

to your containerConfig stanza in k2config.yaml and run k2 up.

2) Verify that you can create a kubernetes resource (pause pod will do).

Note that we really should be running conformance and (more importantly) density to test this and we plan to do so automatically once additional CI work is completed.

**Comment by coffeepac** [comment]
@joejulian slow hand raised to review this.

**Comment by joejulian** [comment]
:+1:
