### ISSUE TITLE
fix helm charts to delete EBS volumes when services are removed

### ISSUE THREAD

**Issue by joejulian** [samsung-cnct/k2#206]
Bringing down a cluster leaves behind ebs volumes with the aws provider.

**Comment by coffeepac** [comment]
default should be to delete the volume but we should expose a method for keeping volumes around explicitly.  This should be handled in the 'services' section of the k2 config.

**Comment by coffeepac** [comment]
will need to do something for helm charts that are installed outside of k2cli

**Comment by coffeepac** [comment]
if not done by next p2 scrub, make a p3

**Comment by coffeepac** [comment]
change default to delete and provide a config value to set to retain

**Comment by davidewatson** [comment]
The `"helm.sh/resource-policy": keep` [annotation](https://github.com/kubernetes/helm/blob/master/docs/charts_tips_and_tricks.md) may help here.

**Comment by coffeepac** [comment]
moved to: https://github.com/samsung-cnct/k2-charts/issues/123
