### ISSUE TITLE
create docker images that cleanly install ceph for kraken

### ISSUE THREAD

**Issue by cwazy1** [samsung-cnct/k2#21]
today's work focused on creating a dev environment for this as well as deciding on the exact tactics to use. I'd like to get this accepted into the ceph-docker project as both a good will gesture and to get other eyes on this.
to that end I am waffling between creating an official coreos release and a coreos-kubernetes release. I think the requirements are going to be different but I'm not sure.
I spent all of today trying to get this to work in the latest stable coreos version but nothing so far. I"ll poke it a bit tomorrow but if it keeps failing I"ll rebuild against the beta release stream.
EDIT: the kernel in stable CoreOS currently doesn't support exclusive locking of rbd images. This is required for a block store device. Kernce is 4.6.3. Going to try a beta stream build.

**Comment by cwazy1** [comment]
Things are looking pretty good right now! exclusive-lock is not supported by CoreOS stable or beta. I'm guessing that alpha won't either as this is a kernel issue and the kernel jump is only a .0 -> .1 step. The good part is that the original demo has this disabled so I was getting appropriate behavior when attempting to mount the rbd image in several pods, ie: the first mount attempt succeeded and the rest failed.
I have also determined the following:
'--net=host' is required for a clean exit from the rbd process
'--privileged=true' is not required for mounting the rbd image when not in a kubernetes pod. I will experiment more in a bit to see if its required from a kube pod.
EDIT: got a bit sidetracked today. Tomorrow I will fire up another cluster to see if the rbd docker container needs to run in privileged mode. If not, I can cut a PR to ceph-docker to update the install docker image. I'll also create a single docker file that lays down all of the utils, rbdmap, ceph-renamer and the udev rules. I don't know if I can do that through kubernetes but I'm willing to try!

**Comment by cwazy1** [comment]
A new dawn! A new day! Spinning up my old ceph cluster to test out docker parameters. Woo.
EDIT: this is unexpected: failing with a cluster of v1.3.6. Sure.
EDIT: the exact error is:
/sbin/ip
ERROR- it looks like we have not been able to discover the network settings
which comes from: https://github.com/ceph/ceph-docker/blob/master/ceph-releases/jewel/ubuntu/14.04/demo/entrypoint.sh but I don't know why the networking configs have changed. Possibly some kind of auto-update issue but shrug
EDIT: had a bunch of problems getting quay.io to accept my build or a tarball so I had to build a git repo to get my image to build. built it. the image has just the errorring portion of the entrypoint.sh file in it. it works. going to start adding in the env vars and the settings in the ceph full version but I'm pretty sure there's only one var so this may be fruitless.
EDIT: got everything up and running. Added the following block to the entrypoint.sh script:
            - name: CEPH_PUBLIC_NETWORK
              value: 10.244.0.0/16
There's a bug in the entrypoint.sh script. I don't know what the fix is, but the bug is that we either need to set CEPH_PUBLIC_NETWORK when an ipv6 address is found or not check for both the ipv6 address and the public network. Bug: https://github.com/ceph/ceph-docker/issues/369 For now I'll work around this and carry forward. I didn't get a chance to check if the rbd docker script needs --privileged=true so I'll do that on Tuesday. But no point in leaving the cluster up all weekend so I'll rebuild on Tuesday. Woo.

**Comment by cwazy1** [comment]
office move complete, have spun up a new cluster and doing the following different:
experiement	status	comments
not editing cloud provider status on apiserver and all kubelet nodes. these are being set to 'auto-detect' and I want to see if that works.		master was aws, nodes were auto-detect. didn't work. set nodes to aws and it worked. will wait for underlying ticket to be fully sorted out before trying again
not landing rbdmap as its not called from anywhere and I'm going for minimal cruft		 
do not include '--privileged=true' as part of updated rbd docker executable		there are some system calls to stat and du that need to be privileged
not editing cloud_provider status at all		the point is that we don't need any external services so who cares what cloud or bare metal system we're on
create a container that will alter a protected part of the host kubernetes node		hah, yeah, gonna make kubernetes install all of the ceph stuff on its own. mua-wahahaha

**Comment by cwazy1** [comment]
Daemonset as installer should work. Need to make sure the daemonset won't restart pods when they successfully complete.
EDIT: built a docker container that will perform the necessary ceph installs and it all should be working. However, its not. Going to sort out why the mds and the osds aren't starting tomorrow morning.
EDIT: problem seems to have been that KubeDNS was horked for Reasons. Destroyed cluster and recreated it for I am a God and it all works now.
EDIT: and the actual install works as well. Woot Woot. This is done. Time to go update docs and open up a PR.

**Comment by cwazy1** [comment]
Updated the internal wiki
Created an upstream PR: https://github.com/ceph/ceph-docker/pull/376
EDIT: its been merged. there was no discussion. I'm a maintainer now. Woo!

**Comment by cwazy1** [comment]
ToReview:
follow the instructions on this wiki page: ceph install and spin up a cluster that has ceph running
either use the sample app at https://github.com/coffeepac/sample-go or create your own app to exercise both cephfs and RBD volume types

**Comment by coffeepac** [comment]
there will be a new ticket for this.  its a lot easier now.
