### ISSUE TITLE
AWS kubelet kubernetes version change

### ISSUE THREAD

**Issue by coffeepac** [samsung-cnct/k2#218]
what is the manual process for rolling forward or rolling backwards the version of kubernetes running on an aws kubelet node?

this ticket should produce a set of command line steps to effect both up and down version changes.  that list of steps may also include a number of pauses to wait for nodes to go up and down.  I expect this to use 'drain' and then destroy the running node.

**Comment by guineveresaenger** [comment]
Manual steps to roll forward or backward Kubernetes version on AWS kubelet nodes

1. Change Kubernetes version in config file under deployment.kubeConfig.version
2. Run k2cli cluster up with new config file to overwrite
3. Run kubectl get nodes to obtain a list of all running nodes
4. Pipe the result into a text file for reference (all but master nodes)
5. The following steps describe how to update each individual node.
6. Run kubectl drain <YOUR_NODE_NAME> --force --ignore-daemonsets (The --force seems to be necessary as of this moment; unsure if there is a better way)
7. Delete the node from Kubernetes:
kubectl delete node <YOUR_NODE_NAME> 
8. Delete the node from AWS - first find the node’s instance ID:
aws ec2 describe-instances --filters "Name=private-dns-name,Values=<YOUR_NODE_NAME>" --query "Reservations[].Instances[][InstanceId]
9. Copy the resulting ID string and paste into the following command:
aws ec2 terminate-instances --instance-ids <YOUR_INSTANCE_ID>
10. Wait for AWS auto-scaling group to bring up a new node. This may take 5 minutes or so. The new node will have the updated Kubernetes version running on it. To check, run 
kubectl describe node <NEW_NODE_NAME> | grep Kube-Proxy
11. Repeat steps 6-10 for each node.

It is likely possible to run a bash loop to drain and then delete from Kubernetes a list of nodes read from a file; however, getting the instance id off of AWS is a little more involved, so we’re thinking that all these steps can be automated with the same tool…?

**Comment by yenicapotediaz** [comment]
**Commands for automating draining and deleting nodes with kubectl:**
**4.** `kubectl get nodes > nodes.txt`
_To grab all but master nodes:_ `cat nodes.txt | while read line; do if [[ $line == *“ Ready ”* ]]; then cut -f 1 -d " "; fi; done > newnodes.txt`
**6-7.** `cat newnodes.txt | while read line; do kubectl drain $line --force --ignore-daemonsets; kubectl delete node $line; done`

Note:
`drain` will not work unless `--force` is included.
We are now working on deleting the node from AWS with Golang.

**Comment by guineveresaenger** [comment]
AWS deletion with golang program:

`cat nodes.txt | while read line; do aws ec2 describe-instances --filters "Name=private-dns-name, Values=$line" > node.json; var=$(go run formatNode.go); aws ec2 terminate-instances --instance-ids $var; done`

Here's what the go file looks like:

```package main

import (
	"encoding/json"
	"fmt"
	"io/ioutil"
)

type Data struct {
	Reservations []struct {
		Instances []struct {
			InstanceId string `json:"InstanceId"`
		}
	}
}

func main() {
	var data Data
	content, err := ioutil.ReadFile("node.json")
	if err != nil {
		fmt.Print("Error: ", err)

	}

	err = json.Unmarshal(content, &data)
	if err != nil {
		fmt.Print("Unmarshal-error: ", err)
	}
	// get the instance id and log to stdout
	fmt.Println(data.Reservations[0].Instances[0].InstanceId)
}

**Comment by yenicapotediaz** [comment]
Another way to do it, using jq to parse json in bash:
`cat nodes.txt | while read line; do aws ec2 describe-instances --filters "Name=private-dns-name, Values=$line" > node.json; inst=$(cat nodes.json | jq -r '.Reservations[].Instances[].InstanceId'); aws ec2 terminate-instances --instance-ids $inst; done`

**Comment by guineveresaenger** [comment]
Here's a repo with sample cluster, golang program, and shell script to automate deleting all non-master nodes.
I would say the way we identify the nonmaster nodes (by selecting from output from ```kubectl get nodes``` ) is potentially unreliable.
https://github.com/guineveresaenger/aws-kubelet-node-kubernetes-upgrade

**Comment by coffeepac** [comment]
this looks good enough to close but with one note:
- there should be a pause in the process where after deleting a node from AWS the process waits for the new node to spin up and become ready for service before removing the next node.  this will allows kubernetes to gracefully shuffle the workload around in a hopefully transparent manner

and not mentioned anywhere, but should be done as part of the production process:
- all nodes kubelet nodes should be 'cordoned' immediately so that all new workload gets created on the newly created nodes.  this will prevent pods from being shuffled more than once.  it also means that we need to build a latch around this to be able to undo the cordon if there is an early exit.  I think that calls for bringing the default node pool labeling in as a dependency.
