### ISSUE TITLE
Allow method to alter k8s daemon service definition

### ISSUE THREAD

**Issue by cwazy1** [samsung-cnct/k2#22]
Currently in kraken there is no way to alter the general configuration of the k8s daemons.  My use case is that I would like to override the PATH value in the k8s pod.  My only way to do this right now is to edit the relevant k8s unit file on the launched node and add the setting.  This obviously doesn't scale.

**Comment by coffeepac** [comment]
This was my request.  We're running kubelet in a container now which makes the answer to this:  burn your own container.
