### ISSUE TITLE
kubernetes template versioning - spec

### ISSUE THREAD

**Issue by coffeepac** [samsung-cnct/k2#222]
the configuration templates for kubernetes will change over different versions.  we are now entering a stage where we will be supporting multiple (3) minor versions of kubernetes at a time.  we will need a way to store these templates (or diffs of templates) in k2.

**Comment by coffeepac** [comment]
a simple suggestion was laid out in #152 and leaves us with multiple copies of each template.  one directory per supported version.  this is my preferred version because it is clearly understood which template to use for each version (ie no complicated config template overriding logic) and may make #221 easier.

however, as a downside, it does mean that if there is a bug in the template there are potentially several (3 max) locations to update.

**Comment by joejulian** [comment]
We already do logic-based includes for providers. We should do the same thing for version differences to common templates.

**Comment by coffeepac** [comment]
@joejulian do you have an example of what you're referring to?  I don't totally understand what you're talking about.

**Comment by joejulian** [comment]
ansible/roles/kraken.provider/kraken.provider.selector/meta/main.yaml

**Comment by coffeepac** [comment]
@joejulian I see what you're saying now.  

pro:  we only need to fork kubernetes specific version pieces as we hit them
cons:  code becomes more complex as we can have kubernetes specific includes anywhere
           extra maintenance step to remove support for old versions,  ie:  need to search the entire code base for version based includes

**Comment by joejulian** [comment]
The code complexity may be offset by the ability to manage bugs better, otherwise a bug may have to be fixed in 3 places.

Searching the entire code base... git grep is easy. As long as we use a consistent method for version specific includes, that should be very easy.

**Comment by coffeepac** [comment]
in order to make this concrete I'm going to be using k2/#184 as the example for this problem. this is, actually, the precipitating issue so its a good idea in general

**Comment by coffeepac** [comment]
general comments:
 - the templates are in several roles
    system daemons: kraken.cluster_common, kraken.etcd, kraken.node, kraken.master
    kubernetes resources: kraken.fabric, kraken.readines
 - oh hey, nuts.  this is also versioned:
    kubernetes commands (kubectl, helm): kraken.services (task)

**Comment by coffeepac** [comment]
@joejulian we already have some copy/pasta issues with our templates so it may be more than 3 locations that need to be updated.  We can take a look at @davidewatson docker config PR where there the docker templates get replicated for each node type (etc, master, node).

Got me leaning towards logic based overrides.

**Comment by coffeepac** [comment]
@joejulian how 'bout this as a starting point:  merge the two ideas.  We have a common set of templates and the override is for the entire template and not just the affected section?  It still hits the 'many places to fix a bug' issue as its a fork but then we don't have to write any template merging code.

**Comment by joejulian** [comment]
Sounds like a good start.

**Comment by coffeepac** [comment]
spec written.  going to perform some tests to make sure it works.  :D

**Comment by coffeepac** [comment]
I have tested the below snippet and it works.  Would need some work to generate the 'kube_minor_version' fact but that's just a bit of config task.

----

Design Proposal - samsung-cnct/k2#222

Kubernetes Versioning Spec

We propose that for handling multiple versions of templates for Kubernetes we use
logic based overrides of entire files.  We assume that we will not need to update
templates within a single minor version. This means that we have a common set of 
default templates and if a version of Kubernetes requires a change, we determine 
the following:
- should this change be the default going forward?
- is this change scoped to a single minor release?

If the update to the template is the default going forward, we will copy the default
template into a sub-folder the template lives in named <Kubernetes-minor-version>/, 
e.g. '1.5/' for each prior version we still support.  We then make the modifications 
to the template in the default location and include the following code snippet into 
the anisble that chooses the template:

```
- name: template a file
  template: src={{ item }} dest=/etc/conf
  with_first_found:
    - files:
      - "{{ kube_minor_version }}/<template name>"
      - <template name>
```

If the modification required is only for a single version, we copy the template to
a subfolder as above for that version of Kubernetes and modify the template as
needed.

**Comment by joejulian** [comment]
:+1: That's a very common way to handle that with every CM tool.

**Comment by coffeepac** [comment]
the kubectl and helm cli tools can also get out sync.  we had to abandon kubernetes version 1.4 support due to helm version 2.0.3 only working with kubernetes v 1.5 and up.  I suspect we will need to install kubectl and helm into versioned directories in the k2-tools image now as well.  

proposal:  for each minor version of kubernetes we install an appropriate version of kubectl and helm to a versioned path in k2-tools.  this has the advantage of allowing us to use a functioning version of helm and kubectl at all times, doesn't fall prey to samsung-cnct having to fix the same bug in multiple locations and has the downside of bloat in the base image.

**Comment by davidewatson** [comment]
I like it.

Docker is currently being installed in /opt/cnct. Should kubectl, et al. also be installed there? I propose ```/opt/cnct/kubernetes/{{ kubeConfig.version }}/bin/kubectl``` where the version is not limited to the (not necessarily unique) minor version.

We should consider how would this generalize to other layers which may change? For example, osConfig, containerConfig, etc. In those cases the version number itself may not be enough, since the os distribution or container runtime could change as well.

**Comment by coffeepac** [comment]
I like using the path '/opt/cnct/kubernetes' as the root but I don't see a reason to include more than the latest patch release for a given minor kubernetes version.  The image is already quite large and we shouldn't be bloating it anymore then is absolutely required.  So I'd want to know why we would want to include multiple patch releases for a given minor release?

**Comment by coffeepac** [comment]
Generalizing this to other layers (os, container, etc) you are correct, the kubernetes version is insufficient.  We would either need to have several directories or a composite directory.  We should strive to be as agnostic as possible but there's no way for the docker configs to be the same as the rkt configs.  

I don't see OS as being an issue as we should be moving to OS agnostic cloud-config files and we don't have any near-term plans to support a container other than docker.

**Comment by davidewatson** [comment]
I wasn't proposing different kubectl's for each patch release, only noting that the minor version may not be unique. For example, suppose after k8s 2.1 is released, 3.0 and 3.1 are released? Since we support the 3 last minor versions, there would be a conflict.

I agree that we are unlikely to need a different patch version, but why not be verbose?

**Comment by davidewatson** [comment]
Also, in general kubectl should continue working even when there are minor version changes. I am uncertain about whether kubectl might need to change to take advantage of new features though.

**Comment by venezia** [comment]
Without trolling, but what about upgrading/downgrading a cluster.  With respect to helm being somewhat tightly bound to k8s minor version, do we just say we'll do a best effort?  (Typically upgrades are easier because people think about them, downgrades are usually more traumatic)

I do think you'll want to have a specific kubectl/helm binary for each version, but this can be solved somewhat with symbolic links within the tools container.

**Comment by coffeepac** [comment]
@davidewatson:
I don't see the conflict.  In your example the directory layout would be:
```
/opt/cnct/kubernetes/2.1
/opt/cnct/kubernetes/3.0
/opt/cnct/kubernetes/3.1
```

And why not be more verbose:  I do not see a need for it.  Any additional verbosity or complexity will cause future engineers more work to understand the system and will create additional places for the system to break.

**Comment by davidewatson** [comment]
Ah, so I misunderstood the meaning of minor_version above. I did not take it to include the major version. Looks good!

**Comment by coffeepac** [comment]
@venezia there is a [secondary proposal](https://github.com/samsung-cnct/k2/issues/222#issuecomment-284815900) in this ticket, and its possible I should have created a separate issue to handle kubectl/helm versions, that aims to handle using the correct version of kubectl and helm for a given version of kubernetes.  I am not inclined to have that problem be solved with symlinks because that would mean that k2 would have to:
- check that the default symlink is pointing to the correct versions at runtime
- update the symlink if it is incorrect

the included proposal side-steps that issue by having k2 call explicit versions of kubectl and helm.

**Comment by coffeepac** [comment]
I've seen no comments or critiques in a while so I'm going to assume this is acceptable and write up the implementation tickets.  Obviously, still time for review and discussion until the implementation tickets start being implemented.

**Comment by coffeepac** [comment]
To Review:
- there is a design for how k2 will handle kubernetes templates changing over time
- there is a design for how k2 will handle binary versions of external applications that are tied to kubernetes releases over time
- there are tickets to implement the above (all tickets should be linked into this one)

**Comment by leahnp** [comment]
LGTM - I see 2 designs and tickets to implement what is outlined in this conversation.

**Comment by coffeepac** [comment]
Back to InProgress due to Helm version drift.

The issue is that we use helm to configure our cluster in order to pass e2e tests.  This means we require a version of helm for every version of kubernetes that we want to use.  Unfortunately helm can lag kubernetes by (currently planned) 6 weeks.  This is unacceptable.

We need to decide how to handle this.  An initial set of options are:
- remove kubedns from being deployed with helm entirely
-- this means we'll need a statically defined dns yaml somewhere
- have kubedns deployed via not helm for any version of kubernetes that doesn't have a helm version
-- would allow us to use the chart version whenever helm is updated which means we wouldn't need to have a static definition for every version of kubernetes
-- would need a 'helm exists' check, which we'll need anyway to support `k2cli tool`
- create a nightly build of helm for any version of helm that we don't have an official release for
-- requires a CI system
-- requires a fair amount of tooling to support this

**Comment by davidewatson** [comment]
My vote is for option 3. Careen can be used while we fix our CI (as we do for docker now).

**Comment by leahnp** [comment]
Vote for #2, this should only be a few weeks of dealing with this, would rather take the path of least resistance.

**Comment by coffeepac** [comment]
Must do:
 - create a static yaml definition of DNS
 - determine the operational differences between 1 and 2
 - have further discussion about how to handle helm (client-go) lag

**Comment by coffeepac** [comment]
in an effort to streamline our efforts to ensure functional clusters I am going to remove our hard dependency on helm being up-to-date.  so we're going with option 1 for now and I'll create a ticket to handle shifting to nightly builds of helm where appropriate.

**Comment by coffeepac** [comment]
ToReview:
- check that the four last opened tickets cover handling helm not releasing at the same time as kubernetes

**Comment by leahnp** [comment]
LGTM - the last four tickets seem to cover the 4 action items, although I might need some clarification on this ticket: https://github.com/samsung-cnct/k2/issues/285
