### ISSUE TITLE
Node Management Doc updates

### ISSUE THREAD

**Issue by coffeepac** [samsung-cnct/k2#230]
As part of node management we are going to be creating new processes that our end users will need to follow.  These need to be documented.

**Comment by coffeepac** [comment]
this should include exactly how we are setting the kubernetes_minor_version fact, which is how we decide which version of kubernetes clients to use.
aws:  version of control plane
gke: last nodePool in the list

**Comment by guineveresaenger** [comment]
per chat with @coffeepac this should also warn the user that repeated up and update may break the etcd nodes in case a more recent version of coreOS has been released.

**Comment by guineveresaenger** [comment]
Question: We are still using the version of kubectl that lives in `/usr/bin/kubectl`. I'm assuming this will change - what should the README say in the meantime?

**Comment by coffeepac** [comment]
Make it reflect what we will be doing in a week when the outstanding `k2cli tool` issues get resolved.

**Comment by guineveresaenger** [comment]
PR: https://github.com/samsung-cnct/k2/pull/544
