### ISSUE TITLE
k2cli should allow for provider flag on generate

### ISSUE THREAD

**Issue by DStorck** [samsung-cnct/k2#233]
currently running ./k2cli generate ${HOME}/k2configs/  will create a config file that includes AWS defaults.  Reconfiguring this for Joyent/ GKE/ bare metal means going through line by line and determining what needs to be edited.   It would be great if when generating the initial config file, a provider could be given in the command to add the proper defaults

**Comment by joejulian** [comment]
:+1:

Though once the config recon is completed, it may be as simple as a one-line change. Even still, I would like to be able to pass not just the provider to generate, but also any other keys: cluster, credentials, etc.

**Comment by DStorck** [comment]
work for provider is done here: https://github.com/samsung-cnct/k2cli/pulls . it only includes a flag to change the default config based on provider. Right now, gke is the only reason you would use it, it currently defaults to aws.

**Comment by DStorck** [comment]
currently working on tests for this

**Comment by coffeepac** [comment]
PR Reviewed: https://github.com/samsung-cnct/k2cli/pull/73
