### ISSUE TITLE
samsung github page remodel to better reflect the purpose of the website

### ISSUE THREAD

**Issue by coffeepac** [samsung-cnct/k2#235]
Please create a PR with a new layout for the samsung github pages repo.  This new model should better reflect the reality of the documents that we are publishing to this page and should include a new section with a blog.

Our needs for this page are more geared towards marketing and group philosophy and less towards a technical or reference website.

**Comment by davidewatson** [comment]
Perhaps outside of the scope of your issue, but it would be great if the documentation of, for example, k2cli, pulled in the actual README.md. As it is, the pages page and README are bound to get out of date.

**Comment by iredwards** [comment]
The pages page and READMEs are already different. I'll start by getting them in sync (or finding any reasons why they shouldn't be the same). The pages pages _should_ pull from the k2* repos.

**Comment by coffeepac** [comment]
this will be part of the marketing plan but isn't something we're focusing on right now

**Comment by coffeepac** [comment]
dupe of #437
