### ISSUE TITLE
consistent references to helm cli in kraken.services

### ISSUE THREAD

**Issue by coffeepac** [samsung-cnct/k2#236]
depending on the task, sometimes helm is invoked directly as 'helm' and sometimes it is invoked through an ansible variable as '{{ helm_command }}' we should be consistent.

if we decide the ansible variable is the correct path we should open an issue to convert the raw 'kubectl' calls in this task

**Comment by coffeepac** [comment]
as part of #222 we are going to be building the string for each execution dynamically.  all invocations of the helm command should be built as follows:

```
/opt/cnct/kubernetes/{{ kubernetes_minor_version }}/bin/helm
```

where `kubernetes_minor_version` is a fact that will be created in the config role.

**Comment by coffeepac** [comment]
blocked by #248

**Comment by guineveresaenger** [comment]
We need to make a decision regarding whether to block all calls to helm if helm isn't supported in current k8s version, or to issue a warning.

**Comment by guineveresaenger** [comment]
Helm support will have to be manually updated every time something changes. Currently, there exists no helm option for kubernetes version 1.6.

*Options and concerns:*

- warning task that helm is not supported for minor version 1.6
- hard code k8s 1.6 to have a different helm version, with warning that it might be buggy
- block all calls to helm for k8s 1.6 (how?)

**Comment by coffeepac** [comment]
we're going to be hitting this issue of using a version of kubernetes without a version of helm often as we start testing beta and alpha versions of kubernetes.  it would be great if you could prototype some code in k2cli for handling this.  I think the best way would be:
- have k2cli check to see if there is a version of helm for the version of kubernetes specified in the config file
- have k2cli notify the user of this issue and offer to use the newest version of helm instead
- if the user of k2cli says 'yes!  use the newest version' then create an environment variable to pass into the k2 docker invocation named 'HELM_VERSION_OVERRIDE' which is set to the version of kubernetes of helm to use (that's not very clear but hopefully make sense)
- update k2 to prefer the version specified in HELM_VERSION_OVERRIDE if its available (this is globally binding, if someone just wants to override helm, let 'em)
- add a check in K2 that if there is no acceptable version of helm available then skip all helm commands

does that make sense?  it might not.  we can talk about it.

**Comment by guineveresaenger** [comment]
Closing and continuing this work on hte next ticket
