### ISSUE TITLE
Documentation should match code

### ISSUE THREAD

**Issue by davidewatson** [samsung-cnct/k2#238]
The current documentation is out of date and also includes features which have never been implemented. For example: https://github.com/samsung-cnct/k2/blob/master/Documentation/kraken-configs/kubelabels.md

We can fix this by reviewing the documentation, or depending on the results of #221, we can generate documentation from the config schema.

**Comment by DStorck** [comment]
Much of this will be covered by https://github.com/samsung-cnct/k2cli/issues/72 
Whoever grabs this ticket, check with me to make sure we are not duplicating work.

**Comment by davidewatson** [comment]
Dup of #261
