### ISSUE TITLE
Implement calico network functionality

### ISSUE THREAD

**Issue by cwazy1** [samsung-cnct/k2#25]

**Comment by sostheim** [comment]
There was an implementation of Calico networking for the previous [Kraken](https://github.com/sostheim/kraken) that was never merged to master, here: https://github.com/sostheim/kraken/tree/calico-via-tf - branch hasn't been deleted atm.  

There is a Calico Project guide for running Calico on CoreOS for AWS here: https://github.com/projectcalico/calico-containers/blob/master/docs/cni/kubernetes/AWS.md.

There is a [Kubernetes](https://kubernetes.io) documentation guide for running Calico on CoreOS for bare metal here: http://kubernetes.io/docs/getting-started-guides/coreos/bare_metal_calico/

In conversation with @venezia the preferred configuration for Calico in K2 would be to use static pods to manage the components (see: http://kubernetes.io/docs/admin/static-pods/).  Currently Flannel CNI networking components are managed as system binaries, so this would present at least a temporary divergence in the management of the two fabrics.

**Comment by venezia** [comment]
WRT to CNI networking components, we could do something similar to how coreos handles this -> build images of hyperkube that have CNI baked in - https://github.com/coreos/kubernetes/blob/coreos-hyperkube-v1.4.0-beta.10/cluster/images/hyperkube/Makefile for example.

We would probably need this for cephfs anyway

**Comment by sostheim** [comment]
For reference, see also the discussion here: https://github.com/projectcalico/calico-containers/issues/1061  which tracks the discussion of running Calico as a static pod per on a node.

**Comment by coffeepac** [comment]
pretty sure this is done.  we're using canal which, stock, uses calico and flannel.  if this isn't complete, please re-open and we'll discuss what should be done.
