### ISSUE TITLE
cut version 1.0 of k2

### ISSUE THREAD

**Issue by coffeepac** [samsung-cnct/k2#250]
determine what the necessary features are for k2 v1.0 and then cut a release.  if the new CI system is running, build the process there.  if not, build the release process in the old CI system.

**Comment by coffeepac** [comment]
Suggested features todo:
- config file version work complete
- kubernetes templating work complete
- upgrade/downgrade kubernetes nodes

If we don't think this is enough for a 1.0, I'm happy to cut a 0.1 instead.  I'd like to cut this release by April 14th.  Can slip a bit but that's about how much longer I am willing to go with k2 being an unversioned resource.

**Comment by davidewatson** [comment]
I think this is enough for a 1.0 release and can be completed by the 14th of April. I still vote for calling it 0.1 though. Just for a bit. Semver is not forgiving.

**Comment by leahnp** [comment]
Any marketing plans? We could throw some goals in to speak about new features periodically at SIG meetings or other meetups. Or blog posts on releases. Of course I personally feel these goals should also come with a concrete consensus on branding and target demographics (who uses K2 and why/what problem are we solving). I think this is especially important when we start designing a GUI as knowing our users will be paramount to creating something easy to use and not just a confusing mess. 

What does "debugging K2 documents" mean?

Documentation goals? CI goals? 

Looking good - it's great to visualize the big picture.

**Comment by DStorck** [comment]
Since Apr has come and gone, do we want to talk about a doable date for this release? And have we decided if we are releasing 0.1 or 1.0?  If we are doing a full release of 1.0, I'd probably want to see slightly better documentation than we currently have.

**Comment by coffeepac** [comment]
@DStorck version 1.0 isn't going to be released for ages.  We're going to be hopefully hitting the 0.1 milestone in april.  that is tracking here:  https://github.com/samsung-cnct/k2/milestone/1

**Comment by coffeepac** [comment]
@leahnp I know nothing of marketing and it most regularly fails to cross my mind.  that said, yes, we should have a per-milestone release blog post somewhere.  maybe it would be a good idea to have a tracking ticket for each of the milestones which says 'at the end of every release, place the milestone tag, push to the quay repo and write up the release notes and blog post'. 

For branding/target demographic I've been considering our target audience to be cluster operators.  However, I haven't actually talked to anyone about that so we should probably start honing that.  Maybe as part of the 0.2 milestone?  It feels late to do it for 0.1

Debugging K2 Documents:  how to trace errors in K2 and kubernetes clusters that have been spun up by k2.  Ie:  what steps should you take when a `cluster up` returns with 'API Server returns EOF' or whatever that mostly useless error message is.

Documentation goals:  nothing explicit yet, but should probably start by filling in the READMEs for all of the ansible roles and staying on top of the Getting Started guides for each milestone.

CI Goals:  loads but I'm not inclined to write them up until the new CI system is running (hopefully within the next two days).  After that's done then there is a flood of blocked by CI tickets to start sorting through.  We should get a good idea for what we need to do and what our current implied expectations are.

**Comment by joejulian** [comment]
Unit testing?

**Comment by leahnp** [comment]
Sounds good, perhaps we can have a sit down next month in May when the team is together to talk marketing/branding strategy. Since we don't have a dedicated team to take care of that, I still think it's important we are all on the same page and can make engineering decisions with our 'customer' in mind.  

Aiming for a blog post in 0.2 is good I think.

**Comment by leahnp** [comment]
Let's add a K2 crash reporter to track k2 up/down/upgrade run times & failures. https://github.com/samsung-cnct/k2/issues/355

**Comment by coffeepac** [comment]
Crash reporter scoping has been added to 0.2.  If its too big for 0.2 it goes into 0.3

**Comment by coffeepac** [comment]
CI system readiness.  I'm thinking 0.4 because 0.1 is delayed, 0.2 is in flight and 0.3 is busy already.  Thoughts?  CI readiness broadly entails all components are under CI and we're mostly happy with it.

**Comment by joejulian** [comment]
Allow for the deployment and management of multiple clusters from a single configuration file (ie. separate staging and production clusters). This is a current customer want.
