### ISSUE TITLE
Add checksums to Dockerfile to verify integrity

### ISSUE THREAD

**Issue by davidewatson** [samsung-cnct/k2#256]
The k2 Dockerfile currently contains lines like this:

```
wget http://storage.googleapis.com/kubernetes-helm/helm-${K8S_HELM_VERSION}-linux-amd64.tar.gz && tar -zxvf helm-${K8S_HELM_VERSION}-linux-amd64.tar.gz && mv linux-amd64/helm /usr/bin/ && rm -rf linux-amd64 helm-${K8S_HELM_VERSION}-linux-amd64.tar.gz
```

We should follow the best practices implemented in goglide and [careen-goglide](https://github.com/samsung-cnct/careen/blob/master/container/Dockerfile) and verify the checksum of the tarball.

**Comment by coffeepac** [comment]
move to k2-tools

**Comment by davidewatson** [comment]
This issue was moved to samsung-cnct/k2-tools#100
