### ISSUE TITLE
Generate default k2 config file from schema

### ISSUE THREAD

**Issue by davidewatson** [samsung-cnct/k2#260]
# Task

The k2 schema contains well defined defaults for each property. These defaults are not used during the validation process. Therefore an ansible task must be written to write out all defaults to a file.

**Comment by coffeepac** [comment]
is blocked by #258

**Comment by coffeepac** [comment]
This is not going to be completed.  @davidewatson will update with further information

**Comment by coffeepac** [comment]
@davidewatson if there is no work to do here I'm happy to just close it get on with life

**Comment by coffeepac** [comment]
its been a month, I'm closing this.
