### ISSUE TITLE
Generate k2 documentation from schema

### ISSUE THREAD

**Issue by davidewatson** [samsung-cnct/k2#261]
# Tasks

The existing documentation does not match the implementation. This ticket is to generate current documentation based on the new schema. Changes or additions to the name and description fields of the k2 schema will be needed.

Note that there are existing tools for doing this, so we may not have to write our own.

**Comment by coffeepac** [comment]
is blocked by #258

**Comment by davidewatson** [comment]
I have used [doca](https://github.com/cloudflare/doca) to create a mock up:

![screen shot 2017-06-06 at 3 21 24 pm](https://user-images.githubusercontent.com/11819015/26892847-73af3afa-4b6e-11e7-96b2-6dc7dc561b9e.png)

This required a minimal number of modifications to the JavaScript/CSS/HTML generated by doca. My two concerns are 1) does the toolchain mesh with our other efforts (blog, etc.)? and 2) is the additional work required (e.g. fix parsing for some of our schema, change json examples to yaml, etc.) a priority? I'd really like if we had something which was simpler, perhaps only translating jsonschema to markdown, for example. Of course, then we would loose the search functionality, themes, etc.

For more references see this [list of jsonschema implementations](http://json-schema.org/implementations).

**Comment by coffeepac** [comment]
looks great:  https://samsung-cnct.github.io/k2/
