### ISSUE TITLE
Update k2 to support terraform 0.9.x

### ISSUE THREAD

**Issue by davidewatson** [samsung-cnct/k2#267]
The Terraform 0.9.x series introduces a number of backwards incompatible changes. This ticket is to update k2 to use terraform 0.9.x. Separate tickets should be opened to cover taking advantage of new features (e.g. #125 already exists and might benefit from this update).

See the [changelog](https://github.com/hashicorp/terraform/blob/master/CHANGELOG.md) for a list of changes.

**Comment by coffeepac** [comment]
checked the changelog, the backwards incompatible stuff doesn't matter to us.  its azure, GCP and AWS stuff we don't use.

**Comment by coffeepac** [comment]
closing this issue in favor of a full system version check:  samsung-cnct/issues#33

**Comment by davidewatson** [comment]
Fair enough. At this point we want to move to [0.10.x](https://www.hashicorp.com/blog/hashicorp-terraform-0-10/) anyway. One of the features this will provide is recursive module targets. This is useful for etcd initialization.
