### ISSUE TITLE
Migrate osConfig stanza

### ISSUE THREAD

**Issue by davidewatson** [samsung-cnct/k2#270]
# coreos stanza

This ticket is to remove the old stanza, ```"#/deployment/coreos”```, from ansible/roles/kraken.config/files/config.yaml  and update the dependent Ansible tasks to access ```#/deployment/clusters/{{clusterIndex}}/nodes/{{nodeIndex}}/osConfig```. instead. When doing this the k2 schema, ansible/roles/kraken.config/files/schema.json , should be updated as well.

**Comment by davidewatson** [comment]
Blocked on #276

**Comment by leahnp** [comment]
PR: #335
