### ISSUE TITLE
Migrate containerConfig stanza

### ISSUE THREAD

**Issue by davidewatson** [samsung-cnct/k2#272]
# containerConfig stanza

This ticket is to remove the old stanza, ```"#/deployment/containerConfig”```, from ansible/roles/kraken.config/files/config.yaml  and update the dependent Ansible tasks to access ```#/deployment/clusters/{{clusterIndex}}/nodes/{{nodeIndex}}/containerConfig```. instead. When doing this the k2 schema, ansible/roles/kraken.config/files/schema.json , should be updated as well.

**Comment by davidewatson** [comment]
Blocked on #276.

**Comment by coffeepac** [comment]
going to do the assembler role and re-do part of the provider role so I don't have to have separate loops for each node type (etcd, master and node).

**Comment by coffeepac** [comment]
wait, what is this.  I have to migrate and merge kraken.etcd, kraken.master and kraken.nodes.  how did I end up pulling the two largest sets of changes?

**Comment by coffeepac** [comment]
I have merged the three node roles into a single nodePools role with a selector.  This will require some refactoring soon to speed up this portion of the project as I didn't change how the underlying roles operate and each underlying role iterates through all nodePools in a given cluster.  Its a small thing but its going to bother me.  Not enough to fix it right now but it will.

**Comment by coffeepac** [comment]
ToReview:
- linked PR is merged.

**Comment by guineveresaenger** [comment]
Newbie question: If the PR is merged, does that mean someone should move this ticket to Done? Or is there more review work in this case?

**Comment by coffeepac** [comment]
@guineveresaenger should be closed and moved to done!
