### ISSUE TITLE
Migrate keyPair stanza

### ISSUE THREAD

**Issue by davidewatson** [samsung-cnct/k2#273]
# keyPair

This ticket is to remove the old stanza, ```"#/deployment/keyPair”```, from ansible/roles/kraken.config/files/config.yaml  and update the dependent Ansible tasks to access ```#/deployment/clusters/{{clusterIndex}}/nodes/{{nodeIndex}}/keyPair```. instead. When doing this the k2 schema, ansible/roles/kraken.config/files/schema.json , should be updated as well.

**Comment by davidewatson** [comment]
Blocked on #276.

**Comment by davidewatson** [comment]
When this is done, the templating should be changed. Currently we hard code the first element in the keyPair list:

```
rodin:k2 dwat$ grep -r privateKeyPath ansible
ansible/roles/kraken.ssh/kraken.ssh.aws/templates/ssh_config.jinja2:{% set privateKeyPath = kraken_config.nodepool | selectattr("name", "equalto", instance.tags['k2-nodepool']) | list %}
ansible/roles/kraken.ssh/kraken.ssh.aws/templates/ssh_config.jinja2:{% if privateKeyPath[0].keypair.privatekeyFile is defined %}
ansible/roles/kraken.ssh/kraken.ssh.aws/templates/ssh_config.jinja2:  IdentityFile {{privateKeyPath[0].keypair.privatekeyFile}}
rodin:k2 dwat$ 
```

**Comment by guineveresaenger** [comment]
^^ in the gke provider tasks, #271 and this ticket are in conflict

**Comment by yenicapotediaz** [comment]
All tasks have been covered in ticket https://github.com/samsung-cnct/k2/issues/269

**Comment by coffeepac** [comment]
@yenicapotediaz my apologies.  I didn't mind to overstep.  but yes, this has all been completed.
