### ISSUE TITLE
Migrate clusterServices to helmConfig

### ISSUE THREAD

**Issue by davidewatson** [samsung-cnct/k2#274]
# clusterServices stanza

This ticket is to remove the old stanza, ```"#/deployment/clusterServices”```, from ansible/roles/kraken.config/files/config.yaml  and update the dependent Ansible tasks to access ```#/deployment/clusters/{{clusterIndex}}/helmConfig``` instead. When doing this the k2 schema, ansible/roles/kraken.config/files/schema.json , should be updated as well.

**Comment by davidewatson** [comment]
Blocked on #276.

**Comment by DStorck** [comment]
Things are working, but I've had to move a chunk of variables out of default/main.yaml because they are now dynamically created. It has forced an unsettling bit of reduncancy into kill-services and run-services.yaml for variable creation. I'm not loving it but I don't see another way at the moment.

**Comment by DStorck** [comment]
PR is here https://github.com/samsung-cnct/k2/pull/333

**Comment by coffeepac** [comment]
PR is here and currently unmerged:  https://github.com/samsung-cnct/k2/pull/334

**Comment by guineveresaenger** [comment]
PR is closed. Seems done.
