### ISSUE TITLE
Migrate etcd, master, node and nodepool stanzas

### ISSUE THREAD

**Issue by davidewatson** [samsung-cnct/k2#275]
# etcd, master, node and nodepool stanzas

This ticket is to remove the old stanzas in the heading from ansible/roles/kraken.config/files/config.yaml  and update the related Ansible tasks to match. When doing this the k2 schema, ansible/roles/kraken.config/files/schema.json , should be updated as well.

**Comment by davidewatson** [comment]
# Notes

The nodepool stanza contains a mishmash of concepts: number of nodes, shared kube/container/os settings, provider specific volume configuration and node specific mount points. Under the k2recon, this information has been moved to the “nodes” (number of nodes and shared configuration)) and “nodeConfig” (provider and node) stanzas. Most of the configuration work should be completed by #269, #270, #271, #272, and #273 .

provider volume and node mountpoint configuration is stored in a new nodeConfig stanza. Is there any benefit to breaking these up a la k8s volume and volumeMounts stanzas?

**Comment by davidewatson** [comment]
Blocked on #276.

**Comment by davidewatson** [comment]
Looking only at etcd, this looks like it will be a fair amount of work. There are > ~80 references. Therefore I am assigning to myself until I either complete the work or figure out how to break it up into more manageable pieces.

**Comment by davidewatson** [comment]
Instead of removing the etc, master, and node roles now, first I am converting all of the templates to use the new item (cluster, node) tuple which is passed to each template task.

```
diff --git a/ansible/roles/kraken.master/kraken.master.docker/tasks/main.yaml b/ansible/roles/kraken.master/kraken.master.docker/tasks/main.yaml
index 0a26658..7cde888 100644
--- a/ansible/roles/kraken.master/kraken.master.docker/tasks/main.yaml
+++ b/ansible/roles/kraken.master/kraken.master.docker/tasks/main.yaml
@@ -1,6 +1,10 @@
 ---
 - include: service-account-key.yaml
 - include: render-manifests.yaml
+  with_subelements:
+    - "{{ kraken_config.clusters }}"
+    - nodes
+  when: item.1.apiServerConfig is defined
 - include: render-kubeconfig.yaml
 - include: render-write-files.yaml
-- include: render-units.yaml
\ No newline at end of file
+- include: render-units.yaml

This could be done more succinctly if roles allowed for with_*, and as of ansible 2.3.x, they do, so I opened a ticket to upgrade ansible in k2-tools.

**Comment by davidewatson** [comment]
So 2 things remain here:

0) The provider role requires more thought. Even though #269 was intended to handle that migration, the way things are currently written, I can't finally kill off the master node stanza from the old style config without making changes to the provider role.

1) We need to decide on what idiom we want to use to avoid {{ item }} name conflicts. {{ item }} is the default name given to loop iterations.

Since all of the include tasks list set the variable, any include which also uses iteration needs avoid name conflicts. The possible ways are here: http://docs.ansible.com/ansible/playbooks_loops.html#loop-control

a) loop_control results in less code ```- name: clean the terraform state generated prefix and other misc files.
  file:
    path: "{{ config_base | expanduser }}/{{ item.0.name }}/{{ i }}"
    state: absent
  when: kraken_action == 'down'
  with_items:
    - aws_prefix
    - terraform.tfstate
    - terraform.tfstate.backup
  loop_control:
    loop_var: i
```, but it would require less thought, and therefore be more robust if we just set facts, by convention, at the beginning of any task list. E.g., ```- set_fact:
  cluster: "{{ item.0.name }}"
  node: "{{ item.1.name }}"```. That way ```{{ item }}``` can retain it's generic use.

**Comment by davidewatson** [comment]
So, I've here's what the current code does. In each main.yaml, we use a loop_control to avoid polluting the namespace of included tasks files.

```
--
- include: service-account-key.yaml
  with_subelements:
    - "{{ kraken_config.clusters }}"
    - nodes
  loop_control:
    loop_var: outer_item
  when: item.1.apiServerConfig is defined
```

Then, at the beginning of each task file, I set to facts so that we can use descriptive, and shorter, names in any code that follows.

```
- set_fact:
  cluster: "{{ outer_item.0.name }}"
  node: "{{ outer_item.1.name }}"
```

We arguable do with just setting the facts, but then the item variable would be aliased and ansible would complain.

**Comment by davidewatson** [comment]
Another note, I don't think I will migrate the provider just yet. Not doing so just means we have to live with old style and new style configs for a bit  longer. Since we might want to do that anyway, to give people time to update their configs, I think it's more important to press on with this isolated change. Thought are definitely welcome.

**Comment by coffeepac** [comment]
PR merged:  https://github.com/samsung-cnct/k2/pull/306
