### ISSUE TITLE
Migrate fabric stanza

### ISSUE THREAD

**Issue by davidewatson** [samsung-cnct/k2#277]
This ticket is to remove the old stanza, "#/deployment/fabric”, from ansible/roles/kraken.config/files/config.yaml and update the dependent Ansible tasks to access #/deployment/clusters/fabricConfig. instead. When doing this the k2 schema, ansible/roles/kraken.config/files/schema.json , should be updated as well.

**Comment by davidewatson** [comment]
@venezia: In #276 I've changed the "provider: flannel" property to "type: canal". Is it accurate to call this,
```
  fabricConfigs:
    - &defaultCanalFabric
      name: defaultCanalFabric
      kind: fabric
      type: canal
      options:
        containers:
          kubePolicyController:
            version: v0.5.1
            location: calico/kube-policy-controller
          etcd:
            version: v3.0.9
            location: quay.io/coreos/etcd
          calicoCni:
            version: v1.4.2
            location: calico/cni
          calicoNode:
            version: v1.0.0-rc1
            location: quay.io/calico/node
          flannel:
            version: v0.6.1
            location: quay.io/coreos/flannel
        network:
          network: 10.128.0.0/10
          subnetLen: 22
          subnetMin: 10.128.0.0
          subnetMax: 10.191.255.255
          backend:
            type: vxlan
```,
 canal?

**Comment by davidewatson** [comment]
Blocked on #276.

**Comment by leahnp** [comment]
@davidewatson Can you clarify this `When doing this the k2 schema, ansible/roles/kraken.config/files/schema.json`  - I don't see this file in K2 currently.

**Comment by davidewatson** [comment]
There is an incomplete PR checking in this file, but it is not ready yet. Please skip the schema for now.

**Comment by leahnp** [comment]
#331
