### ISSUE TITLE
Create static definition for kubedns

### ISSUE THREAD

**Issue by coffeepac** [samsung-cnct/k2#283]
due to issues raised in #222 we need to create a pod definition for deploying a DNS solution to our kubernetes clusters.  as a first pass this solution should have the following traits:
- use the newest version of KubeDNS (which is just called DNS now, which is kind of annoying)
- be manually tested against v1.4, v1.5 and v1.6
- be installed via an ansible role before helm is installed

**Comment by coffeepac** [comment]
should also include removing kubeDNS from the default set of services

**Comment by coffeepac** [comment]
can find an example of this in kubernetes the hard way by kelsey hightower

**Comment by mikeln** [comment]
kubedns is now:
```
gcloud alpha container images list --repository=gcr.io/google_containers
:
gcr.io/google_containers/k8s-dns-dnsmasq-amd64
gcr.io/google_containers/k8s-dns-dnsmasq-arm
gcr.io/google_containers/k8s-dns-dnsmasq-arm64
gcr.io/google_containers/k8s-dns-dnsmasq-nanny-amd64
gcr.io/google_containers/k8s-dns-dnsmasq-nanny-arm
gcr.io/google_containers/k8s-dns-dnsmasq-nanny-arm64
gcr.io/google_containers/k8s-dns-dnsmasq-nanny-ppc64le
gcr.io/google_containers/k8s-dns-dnsmasq-nanny-s390x
gcr.io/google_containers/k8s-dns-dnsmasq-ppc64le
gcr.io/google_containers/k8s-dns-dnsmasq-s390x
gcr.io/google_containers/k8s-dns-e2e-amd64
gcr.io/google_containers/k8s-dns-e2e-arm
gcr.io/google_containers/k8s-dns-e2e-arm64
gcr.io/google_containers/k8s-dns-e2e-ppc64le
gcr.io/google_containers/k8s-dns-ginkgo-amd64
gcr.io/google_containers/k8s-dns-ginkgo-arm
gcr.io/google_containers/k8s-dns-ginkgo-arm64
gcr.io/google_containers/k8s-dns-ginkgo-ppc64le
gcr.io/google_containers/k8s-dns-kube-dns-amd64
gcr.io/google_containers/k8s-dns-kube-dns-arm
gcr.io/google_containers/k8s-dns-kube-dns-arm64
gcr.io/google_containers/k8s-dns-kube-dns-ppc64le
gcr.io/google_containers/k8s-dns-kube-dns-s390x
gcr.io/google_containers/k8s-dns-sidecar-amd64
gcr.io/google_containers/k8s-dns-sidecar-arm
gcr.io/google_containers/k8s-dns-sidecar-arm64
gcr.io/google_containers/k8s-dns-sidecar-e2e-amd64
gcr.io/google_containers/k8s-dns-sidecar-e2e-arm
gcr.io/google_containers/k8s-dns-sidecar-e2e-arm64
gcr.io/google_containers/k8s-dns-sidecar-e2e-ppc64le
gcr.io/google_containers/k8s-dns-sidecar-ppc64le
gcr.io/google_containers/k8s-dns-sidecar-s390x
:
```
```
mikeln-bender:.aws Mikel_Nelson$ gcloud alpha container images list-tags gcr.io/google_containers/k8s-dns-kube-dns-amd64
DIGEST        TAGS    TIMESTAMP
18ea25fea20c  1.10.1  2017-01-04T13:20:25
4713fb04fc4c  1.11.0  2017-01-13T11:58:24
6277eb50d421  1.12.0  2017-01-25T11:14:03
4f3d924ffa6a  1.12.1  2017-01-26T17:30:36
58565fd4da77          2017-02-01T14:33:45
d5d75a089c50  1.13.0  2017-02-17T11:01:52
c425ea890e91  1.14.0  2017-02-20T12:27:17
33914315e600  1.14.1  2017-02-27T11:03:56
```

Kubernetes Release Notes specify: 1.11.0 as the DNS of choice  (though there appears to be some issues that may be fixed by later version).

```
mikeln-bender:.aws Mikel_Nelson$ gcloud alpha container images list-tags gcr.io/google_containers/k8s-dns-dnsmasq-nanny-amd64
DIGEST        TAGS    TIMESTAMP
f2b30d78acdc  1.14.0  2017-02-20T12:26:46
89c9a1d3cfbf  1.14.1  2017-02-27T11:03:42

mikeln-bender:.aws Mikel_Nelson$ gcloud alpha container images list-tags gcr.io/google_containers/k8s-dns-dnsmasq-amd64
DIGEST        TAGS                  TIMESTAMP
04a995765f1a                        2017-01-04T13:20:48
238a110be222                        2017-01-05T11:04:54
0969e5ce3ec3  1.10.1,1.11.0         2017-01-13T11:58:38
437d60149353  1.12.1                2017-02-01T14:33:57
2bae9a4ac588  1.14.0                2017-02-20T12:27:56
e1eef6104071  1.12.0,1.13.0,1.14.1  2017-02-27T11:04:10
```

Looks like dnsmasq-nanny is only required after 1.14.+

**Comment by mikeln** [comment]
looks like dns 1.11.0 has been recommended since sometime before kube 1.5.0.  Release notes are somewhat lacking.

**Comment by mikeln** [comment]
I think the appropriate organization is to add a step in  roles/kraken.services/tasks/main.yaml before the Helm setup,  (vs adding a new role e.g. kraken.dns) since it is still a cluster service.

**Comment by mikeln** [comment]
```
mikeln-bender:cloud Mikel_Nelson$ gcloud alpha container images list-tags gcr.io/google_containers/exechealthz-amd64
DIGEST        TAGS    TIMESTAMP
a5c595bcc2cd  1.0     2016-03-30T18:30:59
2e2a318b5627  1.1     2016-07-28T11:49:53
503e158c3f65  1.2     2016-09-22T16:15:29
7ecf20f93a63  v1.2.0  2016-09-26T16:05:09
```

**Comment by mikeln** [comment]
Also, the deployment setup has changed from our current setup.  This may have occurred a while ago, not sure.   What we have will work, but there is a "better" or "approved" way of running... some differences in how readiness/healthcheck are done etc.  These changes should also be included, but not sure how many releases of kubernetes back may support them. (i.e. they may be using some newer, nicer features of kubernetes lifecycle).

**Comment by mikeln** [comment]
old - skydns, dnsmasq, healthz
1.4 - kubedns, dnsmasq, healthz
1.5 - kubedns, dnsmasq, dnsmasq-metrics, healthz   <-- metrics monitoring added
1.6 - k8s-dns-kube-dns, kube-dnsmasq-nanny, k8s-dns-sidecar <-- private domain ability added

**Comment by mikeln** [comment]
versions:
kube 1.4 
gcr.io/google_containers/kubedns-amd64:1.8
gcr.io/google_containers/kube-dnsmasq-amd64:1.4.1
gcr.io/google_containers/exechealthz-amd64:1.2

kube 1.5
gcr.io/google_containers/kubedns-amd64:1.9
gcr.io/google_containers/kube-dnsmasq-amd64:1.4.1
gcr.io/google_containers/dnsmasq-metrics-amd64:1.0.1
gcr.io/google_containers/exechealthz-amd64:1.2

kube 1.6
gcr.io/google_containers/k8s-dns-kube-dns-amd64:1.14.1
gcr.io/google_containers/k8s-dns-dnsmasq-nanny-amd64:1.14.1
gcr.io/google_containers/k8s-dns-sidecar-amd64:1.14.1

**Comment by mikeln** [comment]
Need to version DNS setup based on version. https://github.com/samsung-cnct/k2/issues/222

**Comment by mikeln** [comment]
Merge onto k2recon instead.

https://github.com/samsung-cnct/k2/pull/359/files

**Comment by coffeepac** [comment]
PR was merged.  Works like a charm
