### ISSUE TITLE
create check for existence of supported version of helm

### ISSUE THREAD

**Issue by coffeepac** [samsung-cnct/k2#284]
due to issues raised in #222 we may not have a valid version of helm available for a given version of kubernetes.  to work around this, if there is no version installed (/opt/cnct/kubernetes/bin/<kubernetes major.mino version>/bin/helm) then do not attempt to init helm or install any services.

**Comment by leahnp** [comment]
Is this an Ansible task or just a script? Currently when clusters come up we offer suggestions on how to use Helm with your cluster - should we output an alert instead to reinforce Helm is not available for x reason?

**Comment by coffeepac** [comment]
I *think* the best way to do this would be have a task that creates a 'helm_available' fact.  then we use that fact to gate any calls to helm.  

we should output a warning message though if we aren't going to execute the helm call or install the listed services.

**Comment by coffeepac** [comment]
I'm also thinking that we should give an option to use the closest version if desired.  ie Helm v2.5 is where official 1.6 support comes in, but Helm v2.4 mostly works so we should allow that to happen with a warning.

**Comment by coffeepac** [comment]
@guineveresaenger this issue covers some of the discussion we were having elsewhere.  you should probably pick this ticket up and do the work here instead of the other ticket.  keep things cleaner.

**Comment by guineveresaenger** [comment]
@coffeepac  yeah I was wondering about that! ok!

**Comment by guineveresaenger** [comment]
@coffeepac pasting your comments from #236: *

we're going to be hitting this issue of using a version of kubernetes without a version of helm often as we start testing beta and alpha versions of kubernetes. it would be great if you could prototype some code in k2cli for handling this. I think the best way would be:

have k2cli check to see if there is a version of helm for the version of kubernetes specified in the config file
have k2cli notify the user of this issue and offer to use the newest version of helm instead
if the user of k2cli says 'yes! use the newest version' then create an environment variable to pass into the k2 docker invocation named 'HELM_VERSION_OVERRIDE' which is set to the version of kubernetes of helm to use (that's not very clear but hopefully make sense)
update k2 to prefer the version specified in HELM_VERSION_OVERRIDE if its available (this is globally binding, if someone just wants to override helm, let 'em)
add a check in K2 that if there is no acceptable version of helm available then skip all helm commands
does that make sense? it might not. we can talk about it.

**Comment by guineveresaenger** [comment]
Also this somehow intersects with https://github.com/samsung-cnct/k2cli/issues/69

**Comment by guineveresaenger** [comment]
PR: https://github.com/samsung-cnct/k2/pull/390

**Comment by guineveresaenger** [comment]
This PR is finally ready for review.

**Comment by coffeepac** [comment]
work is complete.  go go PR
