### ISSUE TITLE
Setting global variables in Ansible

### ISSUE THREAD

**Issue by guineveresaenger** [samsung-cnct/k2#288]
Currently, the way we make a variable "globally" accessible is by setting them as a fact at the top of the first tasks that get run, in k2/ansible/roles/tasks/main.yaml.

It might be more idiomatic to declare a vars file where globally accessible variables are kept, as per suggestion in this article: https://robert-reiz.com/2014/09/03/global-variables-with-ansible/

and in the docs (the examples a bit further down are pretty good):
http://docs.ansible.com/ansible/playbooks_variables.html#variable-precedence-where-should-i-put-a-variable

Not sure how pressing/necessary this is for the way we use Ansible.

**Comment by davidewatson** [comment]
I think you are right. Let's consider this next week and agree on an ansibly idiom.
