### ISSUE TITLE
AWS API limits

### ISSUE THREAD

**Issue by coffeepac** [samsung-cnct/k2#290]
Determine which limits we are hitting and have @cwazy1 open a ticket with AWS to raise them:

http://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html

**Comment by coffeepac** [comment]
I am continuing to get conflicting information about this, however its very possible that we can't get this limit raised.

failing that we will need to push certain operators to their own regions.  what I have read leads me to believe that each region has its own set of unpublished limits.  http://docs.aws.amazon.com/AWSEC2/latest/APIReference/query-api-troubleshooting.html#api-request-rate

**Comment by coffeepac** [comment]
went through change log for terraform (#267) and kubernetes and found nothing that would help with this.  did see a bit of work around ELB stability but we weren't using any of the related features so not going to push for a move to TF v0.9 yet.

**Comment by joejulian** [comment]
One possible solution is that we don't all use the same account.

> We throttle Amazon EC2 API requests for each AWS account on a per-region basis to help the performance of the service.

**Comment by joejulian** [comment]
Another probably untenable solution is that we have a ticket server set up where every category of api call is issued tickets at an as-yet-undetermined rate. All k2 instances would have to wait for a ticket before being allowed to make the next aws api call within that category.

**Comment by coffeepac** [comment]
As a first cut, I'm going to point CI at us-east-2 (same costs as us-east-1 and us-west2).  Well, first I'm going to get the limits pumped up.  That should at least get CI unblocked even if developers are still a bit hosed.

**Comment by joejulian** [comment]
No matter what change you could make directly to k2 in order to rate limit its own attempts at the api, as you add more people bringing clusters up and down there's no way to manage the aggregate api rate.

**Comment by coffeepac** [comment]
@joejulian account rebuild:  oh bleargh.  that would work.  its a fair amount of paperwork to create the linked accounts but it would work

ticketing system:  that would work but not really something we can ship to customers.

**Comment by coffeepac** [comment]
@joejulian changes to K2:  stop using terraform and have explicit control over when APIs get hit.  Eventually we'd hit the same limits but we would have much greater visibility into what is getting hit when.  that's a really big project though.

**Comment by joejulian** [comment]
> stop using terraform and have explicit control over when APIs get hit
Among a group of 20? developers.

**Comment by joejulian** [comment]
We could just create a bunch of vpcs and just reuse them. Doesn't really test everything but that's the worst complainer.

**Comment by joejulian** [comment]
> stop using terraform ... we would have much greater visibility into what is getting hit when

Can do that now with TF_LOG=DEBUG

**Comment by coffeepac** [comment]
@joejulian there's an open ticket for reusing VPCs.  #124

**Comment by coffeepac** [comment]
as long as we're creating/destroying multiple clusters a day per dev we're going to hit this type of limit.  I suspect that we're hitting a combination of the number of developers and the work that we're doing, ie:  node management and config file work.  Hopefully opening up ohio releases enough pressure to let devs get back to work.

**Comment by coffeepac** [comment]
end of day status:
- us-east-2 limit increases made
- us-east-1 cleaned of extraneous clusters
- us-west-2 cleaned of extraneous clusters

all of these things should help reduce strain against the AWS APIs as k8s makes a pretty decent numnber of calls against the AWS APIs even when just running.  Lets see what happens!

**Comment by leahnp** [comment]
I got a cluster up first try this morning on east-1.

**Comment by leahnp** [comment]
Second `cluster up`of the day failed at: 

```TASK [/kraken/ansible/roles/kraken.provider/kraken.provider.aws : Run cluster up] ***```

**Comment by leahnp** [comment]
Ran up again on the same cluster hit:
```"Request limit exceeded."```

**Comment by coffeepac** [comment]
current notes:  we are running v1.5.2 in production which is effected by https://github.com/kubernetes/kubernetes/pull/41363  Going to upgrade to 1.5.6 (current 1.5.x head) to see if this helps.

**Comment by coffeepac** [comment]
can't use us-east-2 for CI until k2 gets upgraded to v0.5 of drunkensmee.  Will do later today.

**Comment by coffeepac** [comment]
production common-tools cluster is running kubernetes 1.5.2.  upgrading it now

**Comment by coffeepac** [comment]
CI is now running in us-east-2.

**Comment by coffeepac** [comment]
between shutting down common-tools production and moving CI to us-east-2 we seem to not be having problems anymore.  I'm going to leave this until Monday April 3rd and if still no complaints I'll close it.

**Comment by coffeepac** [comment]
by general agreement, this is now "fine"

**Comment by davidewatson** [comment]
While looking into a way to log when we hit AWS rate limits, I found this interesting ticket regarding terraform workarounds: https://github.com/hashicorp/terraform/issues/7388
