### ISSUE TITLE
Refactor misnamed and unused roles

### ISSUE THREAD

**Issue by davidewatson** [samsung-cnct/k2#302]
Rename ```ansible/roles/kraken.{etcd, master, node}/kraken.*.docker``` roles and remove ```ansible/roles/kraken.{etcd, master, node}/kraken.*.selector``` roles.

Currently we have a selector role ```ansible/roles/kraken.{etcd, master, node}/kraken.*.selector``` which unconditionally call analogous ```ansible/roles/kraken.{etcd, master, node}/kraken.*.docker``` roles. The docker roles in particular do not have anything to do with docker, so their contents should probably just be part of the top level role. Then the selector roles can be removed.

**Comment by coffeepac** [comment]
this got done at some point.
