### ISSUE TITLE
Validate the length of config file values

### ISSUE THREAD

**Issue by davidewatson** [samsung-cnct/k2#321]
As part of k2recon we are validating property types. We need to take string lengths into account as well, to avoid errors such as:

```
fatal: [localhost]: FAILED! => {"attempts": 10, "changed": true, "cmd": ["terraform", "apply", "-input=false", "-no-color", "/root/.kraken/dewFabricDebug"], "delta": "0:00:00.647511", "end": "2017-04-06 21:28:18.264357", "failed": true, "rc": 1, "start": "2017-04-06 21:28:17.616846", "stderr": "Errors:\n\n  * aws_elb.master_elb: \"name\" cannot be longer than 32 characters: \"dewFabricDebug-PCAmAzw-master-elb\"", "stdout": "There are warnings and/or errors related to your configuration. Please\nfix these before continuing.", "stdout_lines": ["There are warnings and/or errors related to your configuration. Please", "fix these before continuing."], "warnings": []}
```

This will have to be done on a per provider basis, and therefore may be implemented during the to be implemented semantic validation phase. Implementing this during JSON schema validation may cause the schema to become overly complicated. TBD.

**Comment by joejulian** [comment]
This directly relates to https://github.com/samsung-cnct/k2cli/issues/33

**Comment by davidewatson** [comment]
Actually, this is fairly easy with JSON Schema: https://github.com/json-schema/json-schema/wiki/Maxlength I think the only real "work" here will be to dutifully track down what all of the limits are.

**Comment by coffeepac** [comment]
blocked until json schema is published.

**Comment by davidewatson** [comment]
Known max lengths (chars):

Cluster name - 13 (per samsung-cnct/k2cli#33)
ELB name - 32

**Comment by DStorck** [comment]
cluster name and ELB length checks are in https://github.com/samsung-cnct/k2/pull/487 
there is another validation that might be needed for service names, but this will need to be done in a _helpers.tpl in k2-charts for helm charts

**Comment by DStorck** [comment]
as of k8s 1.4, helm has updated length of service name https://github.com/fabric8io/fabric8-maven-plugin/pull/857
I am going to walk through k2-charts and update this by changing the _helpers.tpl on all charts

**Comment by DStorck** [comment]
service name update to allow length of 63 chars done here: https://github.com/samsung-cnct/k2-charts/pull/88
