### ISSUE TITLE
Migrate kubeAuth stanza

### ISSUE THREAD

**Issue by davidewatson** [samsung-cnct/k2#330]
# kubeAuth

This ticket is to remove the kubeAuth stanza and update the dependent Ansible tasks to access. Since the kubeAuth stanza is not currently included in the default config file, it must be added there first. When adding it, we must decide where it will live (e.g. per cluster, per deployment, etc.). I think it is a per cluster setting, but I have not looked at it.

**Comment by coffeepac** [comment]
kubeAuth is a per cluster setting.   Would be bad form to share auth secrets across clusters and it is tied to services deployed to a specific cluster.

**Comment by DStorck** [comment]
Seems like this is all being covered by https://github.com/samsung-cnct/k2/pull/340

**Comment by coffeepac** [comment]
@DStorck we need kubeAuth added to the default generated config file and I know I would prefer if the kubeAuth sections were handled directly instead of as part of the final sweep (#340) as there are going to be some rough edges to it.  Auth integration is always funky, it benefits from dedicated eyes.

**Comment by DStorck** [comment]
I have been waiting for Yeni to finish up her work and move the files over so I wasn't doing redundant work. Now that the files have been moved out of main I can go take a look and get started

**Comment by DStorck** [comment]
Okay, https://github.com/samsung-cnct/k2/pull/351 has taken the kubeAuth creation away from kraken.config tasks and made it so there must be a kubeAuth stanza for the cluster to go up in the first place. I have not done any work yet on oidc

**Comment by coffeepac** [comment]
PR #351 got merged yesterday.  get lost you!
