### ISSUE TITLE
Migrate GKE k8s minor version fact to new config file

### ISSUE THREAD

**Issue by guineveresaenger** [samsung-cnct/k2#337]
K2recon branched from master before k8s minor version could be set for gke. This ticket will fix that.

**Comment by guineveresaenger** [comment]
Blocked because the new config doesn't reflect a GKE configuration yet.

**Comment by guineveresaenger** [comment]
PR #349 handles this ticket as well.

**Comment by coffeepac** [comment]
PR Merged.
