### ISSUE TITLE
migrate kraken.upgrade

### ISSUE THREAD

**Issue by DStorck** [samsung-cnct/k2#339]
update files in kraken.upgrade to reflect new configuration file

**Comment by DStorck** [comment]
this is blocked at the moment because the k2recon branch of k2 doesn't include these files.

**Comment by coffeepac** [comment]
attempt to use git checkout --patch <branch to pull stuff from>
 
this will merge files to the currently checked out branch

**Comment by coffeepac** [comment]
PR was merged
