### ISSUE TITLE
Inject kubernetes minor version into kraken_config rather than set it as a fact

### ISSUE THREAD

**Issue by guineveresaenger** [samsung-cnct/k2#345]
Setting k8s minor version as a fact no longer works when looping over multiple clusters.
The work in this ticket will set it as a part of kraken_config.
Related: #337

**Comment by guineveresaenger** [comment]
Question:
What level in the configuration should kubernetes_minor_version live in? Right below cluster? As in "cluster.kubernetes_minor_version"? Or should each node have its own minor version?
paging @coffeepac for input

**Comment by coffeepac** [comment]
@guineveresaenger its a cluster level property.  if we need to change it later we can change it later.  shouldn't be needed for ages if ever.

**Comment by guineveresaenger** [comment]
^^ PR ready for k8s minor versions fact

**Comment by coffeepac** [comment]
PR merged and being used.  Done.
