### ISSUE TITLE
Add test to see if cluster is already up when running up

### ISSUE THREAD

**Issue by joejulian** [samsung-cnct/k2#352]
Add a test for determining if a cluster is already up before applying "up" to it. Add a switch to up.sh to allow cluster changes. Fail if that switch is not set and the cluster is already up.

**Comment by blackdog0403** [comment]
@joejulian 

How about asking user before spinning up cluster with checking status.

1. check status of cluster

2. 

**if** It's true then

Ask user "A cluster has been already spinned up. Want to continue to update cluster? [ ( y ) / N ]:"
**if** user input 'y' then
Cluster update
**else** 
Cluster up canceled.
exit
**fi** 

**fi**

**Comment by blackdog0403** [comment]
Or We can set  KRAKEN_CLUSTER_UP_FORCE=false as default.

Then user can set it as true then force up.sh to spin up cluster again.

**Comment by blackdog0403** [comment]
```
#for single cluster. Need choose logic for extendability for multiple clusters.
# parsing config.yaml through bash? or using an anisible role?
CLUSTER_NAME=$(grep -A1 'clusters:' ${KRAKEN_CONFIG} | tail -n1 | awk '{print $3}')

if [ -f ${KRAKEN_BASE}/${CLUSTER_NAME}/admin.kubeconfig ] && [ -f ${KRAKEN_BASE}/${CLUSTER_NAME}/terraform.tfstate ]; then

  inf "Checking cluster status..."

  CLUSTER_NODE_COUNT=$(kubectl --kubeconfig=${KRAKEN_BASE}/${CLUSTER_NAME}/admin.kubeconfig get nodes | wc -l)
  if [ ${CLUSTER_NODE_COUNT} -ge 2 ]; then

    # show current status
    inf  "$(kubectl --kubeconfig=${KRAKEN_BASE}/${CLUSTER_NAME}/admin.kubeconfig get nodes)"

    read -r -p "[ $CLUSTER_NAME ] cluster has been already spinned up. Do you want to continue to update cluster? [ y/N ]:" response
    response=${response,,}    # tolower
    if ! [[ "$response" =~ ^(yes|y)$ ]]; then
      warn "Spinning up cluster has been canceled."
     exit 0
    fi
  fi
fi

warn "Start spinning up cluster..."
```

**Comment by coffeepac** [comment]
this should be a check in ansible and not in a shell script.  

this should follow the pattern set by the helm_override guff for how to get input from a user.  Probably should talk to @davidewatson to avoid some of the mistakes I advocated in that work though.

otherwise, the logic looks good!

**Comment by davidewatson** [comment]
IMHO, this should not be interactive. Besides making automation difficult, it's not clear to me that an operator can always make this decision safely, without first doing a non-trivial amount of work.

I agree with the logic going into an ansible role. IMO, we should follow the logic for the `--force` option used to control deprecated schema versions. The option sets a boolean variable which can be used in conjunction with the `when:` cause in ansible tasks.

But this raises the most difficult of questions (and I mean this seriously): what do we call the option? I am not crazy about the proliferation of force options, and this would be the 3rd.

0. Should we maintain the status quo and create a `--force-*` option for each action we want to force?

1. Should we reuse the `--force` option for all of our override needs?

2. Is it better to have `--force` accept a list of roles which should be forced? E.g. `./up.sh --force config,provider,services`? This would be a nice general solution, though we would need to invent (potentially very short) roles for any actions we want to be forced independently.

My inclination is to implement 1) or 2). Until this question is decided, I suggest reusing the existing `--force` option as it is. We can extend it later to differentiate between actions, if necessary, once the UX is vetted.

**Comment by davidewatson** [comment]
I almost forgot! When I was thinking about this last night, I wondered, what is the intent of this option? Is it to protect the operator from running a potentially dangerous `up.sh` action on a production cluster? Or to allow them to access features which we do not (yet) officially support?

@joejulian: ^^

**Comment by coffeepac** [comment]
having this be difficult to automate is an interesting point, but at the moment there is little reason to run `up` a second time now that `update` exists.  `update` calls the entirety of the up.yaml at the moment because we haven't been able to tease out exactly which roles are required to do the needful.  this is dangerous but there is other work afoot to mitigate the danger (etcd risks primarily).  

there is also little need to have this be fully interactive as the helm_override option is, so I'm not going to fight real hard either way.  

if we are going to add this a force option, I'm fine with either 0 or 1 with a slight preference to 1.  lets start overloading `--force` until the system screams.  yeah?

**Comment by davidewatson** [comment]
Makes sense to me.
