### ISSUE TITLE
Create K2 Crash Reporter Proposal

### ISSUE THREAD

**Issue by leahnp** [samsung-cnct/k2#355]
Crash reporter to track run times for up/down/upgrade and failures. Send metrics & failure logs to website which can aggregate and offer some type of visualization/ability to search errors.

**Comment by coffeepac** [comment]
👍 
and we should run it in the common-tools production cluster.

**Comment by coffeepac** [comment]
use this issue to define a minimal version, determine if that project can be built in 0.2, if not assign it to 0.3

**Comment by coffeepac** [comment]
metrics/data to collect:
- where did k2 fail (in ansible)
- entire log file - currently being written to STDOUT
- <add more as needed>

**Comment by venezia** [comment]
+ List of all resources (and state) in the cloud provider
+ terraform state
+ kubernetes diagnostics (describe nodes, services, pods, all namespaces)

**Comment by leahnp** [comment]
@venezia can you explain what you mean by "terraform state"?

**Comment by alejandroEsc** [comment]
i think he means the state file? give a dump of that if i remember that is in some s3 bucket? i could be wrong about this.

**Comment by coffeepac** [comment]
- cluster config with auth info redacted

**Comment by leahnp** [comment]
Proposal currently in wiki - please comment there!

**Comment by coffeepac** [comment]
Looks sane and as a MVP its great.  Onward!
