### ISSUE TITLE
1.6 support

### ISSUE THREAD

**Issue by coffeepac** [samsung-cnct/k2#361]
walk through deploying a 1.6 cluster using k2.  should include upgrading CI job as well.

**Comment by coffeepac** [comment]
careful of how we are communicating with etcd:  is it json or protobufs?

**Comment by coffeepac** [comment]
the deliverable is moving the default configs to be a 1.6 version.

**Comment by DStorck** [comment]
we can't move to 1.6 until we set up rbac for fluentd https://github.com/samsung-cnct/issues/issues/11

**Comment by coffeepac** [comment]
lets remove central-logging from the default config for now.  the rbac roles should be a part of the chart, I think, and we'll want to have a careful think about how we handle that and what tiller can actually do.

**Comment by DStorck** [comment]
before closing this, make a new issue to bring back central-logging in milestone 0.3 
```
- name: central-logging
          repo: atlas
          chart: central-logging
          version: 0.2.0
```

**Comment by DStorck** [comment]
work is done in https://github.com/samsung-cnct/k2/pulls

**Comment by coffeepac** [comment]
PR merged and good to go.
