### ISSUE TITLE
regenerate secrets for dex auth

### ISSUE THREAD

**Issue by coffeepac** [samsung-cnct/k2#374]
the secrets for common-tools github auth got checked into a public repo as a PR.  need to regenerate them.

**Comment by coffeepac** [comment]
Steps taken:
- be an owner in the Samsung CNCT org
- browse to the Oauth apps
- select 'Common Tools Production Cluster'
- click the button 'Reset Client Secret'
  - this will reset the random hash that is used for the client secret
  - this will not kick anyone who has a valid user token but will prevent the creation of any new tokens
- copy the new value and base64 encode it
  - make sure you don't have a newline in your base64 encoding input string  
     - I did.  it was annoying
- copy the file from s3://sundry-automata/k2-clusters/common-tools/atlas-dex.helmvalues to your local machine
- update the value for 'Dex-> Connector-> GitHub-> ClientSecret'
- ensure that the following helm call has access to the Samsung CNCT helm repo 'atlas'
- ensure that your default kubectl config has access to the production cluster
  - if you are unable to do either or both of these ensure prereqs, check for switches to helm to set them appropriately
- run the command 'helm upgrade dex atlas/dex -f atlas-dex.helmvalues'

You have now updated the secret for the running dex app.

Additional required bookkeeping
- copy the updated atlas-dex.helmvalues file back to s3 in the original location
- copy the file s3://sundry-automata/k2-clusters/common-tools-production.yaml to your local machine
- update the value for the github secret in the helm chart section
- copy the file common-tools-production.yaml back to s3

**Comment by coffeepac** [comment]
ToReview:
- check that the dex pod (not the dex-app pod) has a start time around the time of the time of this comment
- attempt to generate a new token from http://common-tools.kubeme.io:30080/

**Comment by leahnp** [comment]
I was able to generate a new token. Still working on re-gaining access to the prod cluster.

**Comment by leahnp** [comment]
Got into cluster (added a comment to CommonTool production cluster wiki requesting clarity around the new CA).
Dex pod:` kube-auth         dex-2194697777-ww173                                   1/1       Running   0          2d`
LGTM
