### ISSUE TITLE
check for unused loop variables in the following files and locations

### ISSUE THREAD

**Issue by coffeepac** [samsung-cnct/k2#375]
ansible/roles/kraken.config/tasks/main.yaml line 57

ansible/roles/kraken.config/tasks/setup.yaml line 4

ansible/roles/kraken.nodePool/kraken.master.docker/tasks/service-account-key.yaml line 4

**Comment by DStorck** [comment]
I'm assuming line 57 was the reference to the include for setup.yaml, recent merges have changed that file a bunch

**Comment by coffeepac** [comment]
work is complete.
