### ISSUE TITLE
do not allow multiple clusters in list 

### ISSUE THREAD

**Issue by coffeepac** [samsung-cnct/k2#409]
the config file allows for multiple clusters and the ansible roles support multiple clusters we have not tested this functionality nor is there support for this in k2cli.  

because of this, if there is a config file with multiple clusters listed k2 should immediately error out.

**Comment by DStorck** [comment]
this work is in https://github.com/samsung-cnct/k2/pull/417

**Comment by coffeepac** [comment]
work is complete.
