### ISSUE TITLE
weekly on-call version check

### ISSUE THREAD

**Issue by coffeepac** [samsung-cnct/k2#410]
Check for CVEs, new versions of kubernetes and helm and do some basic verification that things work before creating a PR to bump versions.

**Comment by coffeepac** [comment]
document the work well so it can be used as a README later.  what sites to go to, what verifications to perform, etc. etc

**Comment by davidewatson** [comment]
We should write a bot to search these sites and open tickets when in there are new issues. I think it can be done be scraping the HTML pages and searching for already opened (and possibly already closed) issues.

Kubernetes releases: https://github.com/kubernetes/kubernetes/releases

Helm releases: https://github.com/kubernetes/helm/releases

Docker CVE Search: https://cve.mitre.org/cgi-bin/cvekey.cgi?keyword=docker

Careen maintenance documentation:  https://hanjin.atlassian.net/wiki/display/AG/Careen+Maintenance+for+Docker

**Comment by coffeepac** [comment]
Steps taken:
- visit kubernetes release page and check latest versions of kubernetes 1.4, 1.5 and 1.6
  - check these against current versions in k2-tools
  - submitted PR to bring 1.4, 1.5 and 1.6 up to latest (should be fine!)
     - https://github.com/samsung-cnct/k2-tools/pull/44
- visit helm and see there is a point release for 2.4, add it
  - helm doesn't seem to have minor release trains like kubernetes does so the oldest supported k8s (1.4 and 1.5) are essentially frozen
- docker CVEs:  nothing in 2017 that affects us

**Comment by coffeepac** [comment]
ToReview:
- PR exists and is merged
- steps taken are clear and can be followed by others

**Comment by leahnp** [comment]
A few questions to make sure I was doing this right:

- When you say check latest versions of K8s against K2-tools. Does that mean looks at k2-tools/requirements.txt and see if any of those projects are listed in /kubernetes/kubernetes/blob/master/CHANGELOG.md as deprecated or non-compliant? 
- If no problems are detected and new versions are available, is it expected the person doing these checks will submit the necessary PR's to update projects? If so, what is the scope of projects that should be updated (ie, just K8s and Helm...everything in k2-tools?...)?
- where do you get a list of Docker CVE's?
- It might be useful to write a small app to email 'reminders' to the appropriate team member each week, beyond the reminder's usefulness we could run it in the Common Tools prod-cluster for the experience.

**Comment by coffeepac** [comment]
- version check of k8s is for kubectl, helm and k8s itself and not stuff in requirements.txt.  
- it is expected the person who does this will submit a PR to bring everything up to snuff, the scope is kubectl, helm and k8s
- docker CVEs:   https://cve.mitre.org/cgi-bin/cvekey.cgi?keyword=docker
- I think an app or a jenkins job on a timer that shouts in #team-tooltime would be an excellent idea.

**Comment by leahnp** [comment]
LGTM 
Ticket for reminder app/job: https://github.com/samsung-cnct/k2/issues/455

**Comment by davidewatson** [comment]
@coffeepac: Can we close this now? @mikeln has been assigned to review last weeks [ticket](https://github.com/samsung-cnct/k2/issues/456), this weeks [ticket](https://github.com/samsung-cnct/k2/issues/457) is in review and I created next weeks [ticket](https://github.com/samsung-cnct/issues/issues/2)

**Comment by coffeepac** [comment]
@davidewatson yes.  off it goes.
