### ISSUE TITLE
Move Ansible Task Hard Coded Values into Role Default Value

### ISSUE THREAD

**Issue by mikeln** [samsung-cnct/k2#426]
Some ansible tasks have hard coded values.  e.g. kraken.readiness  default timeout is 600 seconds, but that is hard coded in a task file.   Values like this should be centralized for the role and set in the role/defaults/main.yaml file instead.   If it applies to multiple roles, use a higher level global ansible default if possible.

**Comment by alejandroEsc** [comment]
is this a feature request, or a bug? also should we add the help wanted label?

**Comment by coffeepac** [comment]
this should be done as we go.  closing.
