### ISSUE TITLE
ec2_elb_facts module fails with, "'self' is not defined"

### ISSUE THREAD

**Issue by joejulian** [samsung-cnct/k2#434]
`TASK [roles/kraken.services : Wait for ELBs to be deleted]` fails with the following python error:

```
Traceback (most recent call last):
  File "/tmp/ansible_uT0Ock/ansible_module_ec2_elb_facts.py", line 267, in <module>
    main()
  File "/tmp/ansible_uT0Ock/ansible_module_ec2_elb_facts.py", line 260, in main
    self.module.fail_json(msg="{0}: {1}".format(err.error_code, err.error_message),
NameError: global name 'self' is not defined
```

This is an upstream bug fixed in devel with commit 45ac28b.

@s-hertel has cherry-picked to stable-2.3 (b99f489) and the fix will be released in 2.3.1.

**This will be fixed with https://github.com/samsung-cnct/k2-tools/issues/42**

**Comment by coffeepac** [comment]
resolved!
