### ISSUE TITLE
make kubernetes nodePools depend on etcd nodePools

### ISSUE THREAD

**Issue by coffeepac** [samsung-cnct/k2#441]
it has been observed that clusters sometimes don't come up because the kubernetes nodePools are starting up before the etcd nodePools are complete.  we can easily reduce this occurrence by making the non-etcd nodePools have a terraform `depends_on` relationship to the etcd modules.  this will not guarantee that the etcd clusters are up and running but it will prevent master nodes from being launched before all of the etcd nodes are launched.  this is an issue we have right now.

**Comment by coffeepac** [comment]
Larger/safe suggestion:  make the etcd terraform config file be separated from the rest of the cluster.  This will let us run 'terraform apply' against the non-etcd nodePools without being concerned that we might explode etcd.

its more work but safer in the long run.

**Comment by coffeepac** [comment]
I really like my second suggestion more as time goes on.  I really want the etcd nodes to be hived off into their own tfstate file so they can be easily guarded in the code and we don't surprise a user by blowing away their etcd cluster.

**Comment by davidewatson** [comment]
While looking into #553 I discovered why my etcd always appears to be created first:

```
rodin:k2 dwat$ grep etcd_dependency ansible/roles/kraken.provider/kraken.provider.aws/templates/*
ansible/roles/kraken.provider/kraken.provider.aws/templates/kraken.provider.aws.module.etcd.tf.jinja2:output "etcd_dependency" {
ansible/roles/kraken.provider/kraken.provider.aws/templates/kraken.provider.aws.tf.jinja2:  dependency = "${module.etcd.etcd_dependency}"
rodin:k2 dwat$ 
```

**Comment by coffeepac** [comment]
This is already done. Verify the `dependcies` thing exists in the tf file for generated nodePools.

**Comment by coffeepac** [comment]
This is already done.  Nuts.  Going to file another issue to be handled in 0.4 about making the master nodes wait for the etcd cluster to be up and running before getting spun up.  Will close this issue when that's done.
