### ISSUE TITLE
Up should not be killing & rebuilding tiller

### ISSUE THREAD

**Issue by NathanZook** [samsung-cnct/k2#453]
Up should be idempotent.  Update will have to kill and rebuild it, however.
See kill-services.yaml

**Comment by coffeepac** [comment]
first step investigate:
- if destroying/reinstalling tiller causes loss of access to installed charts, p1, otherwise p2

**Comment by coffeepac** [comment]
investigation complete:  removing tiller doesn't effect the installed charts and re-installing helm allows access to the previously installed charts.  

downgrading to p2
