### ISSUE TITLE
weekly on-call version check - 5/26

### ISSUE THREAD

**Issue by coffeepac** [samsung-cnct/k2#456]
Steps to take:

- visit kubernetes release page and check latest versions of kubernetes 1.4, 1.5 and 1.6
  - https://github.com/kubernetes/kubernetes/releases
- visit helm and see there is a new release
  - https://github.com/kubernetes/helm/releases
- helm doesn't seem to have minor release trains like kubernetes does so the oldest supported k8s (1.4 and 1.5) are essentially frozen
- docker CVEs
  - https://cve.mitre.org/cgi-bin/cvekey.cgi?keyword=docker
- create issue for next week, assign to next person in list

OnCall Order:
@coffeepac, @davidewatson, @leahnp, @NathanZook, @DStorck, @mikeln 

Review Order:
last week's person who did this

**Comment by coffeepac** [comment]
- no new kubernetes releases
- helm 2.4.2 released
  - PR: https://github.com/samsung-cnct/k2-tools/pull/46
- no docker CVEs recently

**Comment by coffeepac** [comment]
ToReview:
- PR https://github.com/samsung-cnct/k2-tools/pull/46 is merged

**Comment by spiffxp** [comment]
quick check for kubernetes releases:
```sh
for v in 1.4 1.5 1.6; do 
  echo $v: $(curl -s https://storage.googleapis.com/kubernetes-release/release/stable-$v.txt);
done
```
```
1.4: v1.4.12
1.5: v1.5.7
1.6: v1.6.4
```

**Comment by coffeepac** [comment]
@mikeln please review.
