### ISSUE TITLE
weekly on-call version check - 6/2

### ISSUE THREAD

**Issue by coffeepac** [samsung-cnct/k2#457]
Steps to take:

1) Visit the kubernetes [release page](https://github.com/kubernetes/kubernetes/releases) and verify the latest minor version of the last 3 major releases (e.g. 1.4, 1.5 and 1.6) are supported by [k2](https://github.com/samsung-cnct/k2/blob/master/ansible/roles/kraken.config/files/config.yaml) and [k2-tools](https://github.com/samsung-cnct/k2-tools/blob/master/Dockerfile).  If it is not, then open a ticket against the appropriate repo.
2) Visit the helm [release page](https://github.com/kubernetes/helm/releases) and see there is a new release. Since helm doesn't seem to have minor release trains like kubernetes does, the oldest supported k8s (e.g. 1.4 and 1.5) are essentially frozen (i.e. you only need to look for ).
3) Search for new docker related CVEs [here](https://cve.mitre.org/cgi-bin/cvekey.cgi?keyword=docker). If any are found, please open a ticket against the [issues repo](https://github.com/samsung-cnct/issues/issues). Please do this even if it turns out that there is no work to be done. This ensures we can track which CVEs have been reviewed or not, and will be important if we decide to automate this on-call work.
4) Visit [quay.io](https://quay.io/repository/samsung_cnct/k2-tools?tab=tags) and ensure the latest k2-tools images does not have any vulnerabilities.
5) Create issue for next week, assign to next person in list.

OnCall Order:
@coffeepac, @davidewatson, @leahnp, @NathanZook, @DStorck, @mikeln

**Comment by davidewatson** [comment]
k2-tools includes the latest [kubernetes](https://github.com/samsung-cnct/k2-tools/blob/master/Dockerfile#L20) and latest [helm](https://github.com/samsung-cnct/k2-tools/blob/master/Dockerfile#L24)

I also opened samsung-cnct/issues/#2 for next weeks duties, updated our Slack integrations to include the issues repo, and added quay.io security scan check to the on-call responsibilities.

![screen shot 2017-06-02 at 11 48 23 am](https://cloud.githubusercontent.com/assets/11819015/26740848/06bee7e6-478c-11e7-970c-043e39b15f4b.png)

**Comment by coffeepac** [comment]
WUNDERBAR!
