### ISSUE TITLE
v1.6 Statefulsets Not Fully Deleting All Pods 

### ISSUE THREAD

**Issue by mikeln** [samsung-cnct/k2#459]
Deleting an "app" that has statefulsets either via Helm (if applicable) or directly with kubectl, does not work fully in v1.6 k2.  

Run our cassandra example via helm.  Wait until it is up.  Then helm delete it.   Everything is deleted except the pods and the statefulset.  4 pods: 2 unknown state, 2 running.  Statefulset shows 2 pods up and wants 0 up.   

kubectl delete on the stateful set results in a timeout and no change.

To recover:  delete pods by hand (kubectl delete) then delete the statefulset.

Could be rbac...could be something else.

**Comment by mikeln** [comment]
Using cassandra helm chart for testing.
First issue was that the nodes in the cluster were not big enough to handle cassandra.  
Made the special nodes also "large".

Real error from tiller logs:
```017/06/14 15:55:35 storage.go:94: Listing all releases with filter
2017/06/14 15:55:45 storage.go:133: Getting release history for 'queenly-ant'
2017/06/14 15:55:45 release_server.go:985: uninstall: Deleting queenly-ant
2017/06/14 15:55:45 release_server.go:913: Executing pre-delete hooks for queenly-ant
2017/06/14 15:55:45 release_server.go:940: Hooks complete for pre-delete queenly-ant
2017/06/14 15:55:45 storage.go:53: Updating "queenly-ant" (v1) in storage
2017/06/14 15:55:45 hooks.go:86: info: manifest "manifest-0" is empty. Skipping.
2017/06/14 15:55:45 client.go:282: Starting delete for opscenter-queenly-ant Service
2017/06/14 15:55:45 client.go:354: Using reaper for deleting opscenter-queenly-ant
2017/06/14 15:55:45 client.go:282: Starting delete for cassandra-queenly-ant Service
2017/06/14 15:55:45 client.go:354: Using reaper for deleting cassandra-queenly-ant
2017/06/14 15:55:45 client.go:282: Starting delete for opscenter-queenly-ant Deployment
2017/06/14 15:55:45 client.go:354: Using reaper for deleting opscenter-queenly-ant
2017/06/14 15:55:48 client.go:282: Starting delete for cassandra Secret
2017/06/14 15:55:48 client.go:282: Starting delete for cassandra-queenly-ant StatefulSet
2017/06/14 15:55:48 client.go:354: Using reaper for deleting cassandra-queenly-ant
2017/06/14 16:00:49 release_server.go:1028: uninstall: Failed deletion of "queenly-ant": timed out waiting for "cassandra-queenly-ant" to be synced
2017/06/14 16:00:49 release_server.go:913: Executing post-delete hooks for queenly-ant
2017/06/14 16:00:49 release_server.go:940: Hooks complete for post-delete queenly-ant
2017/06/14 16:00:49 storage.go:53: Updating "queenly-ant" (v1) in storage```

**Comment by mikeln** [comment]
`uninstall: Failed deletion of`
attempting to duplicate.
no open or closed issues in kubernetes/helm about this.

**Comment by alejandroEsc** [comment]
are there any kube-dns/proxy/canal issues involved here?

**Comment by mikeln** [comment]
no

**Comment by mikeln** [comment]
On my local side, this looks like the aws timeout for an open connection (and I'm pretty sure it is ok in this case).  The tiller logs show it is doing the job.   Local helm just waits for a return status, in this case I don't care...but may be something to be aware of.

```mikeln-bender:cassandra Mikel_Nelson$ KUBECONFIG=/Users/Mikel_Nelson/dev/cloud/k2new/myconfig/.kraken/mikeln-rb1/admin.kubeconfig HELM_HOME=/Users/Mikel_Nelson/dev/cloud/k2new/myconfig/.kraken/mikeln-rb1/.helm helm delete mean-giraffe
E0614 10:37:44.827507   28195 portforward.go:175] lost connection to pod
Error: transport is closing```

**Comment by mikeln** [comment]
Wait, this could be related to the cassandra pod post-delete hooks.  An extra wait is performed, so the cassandra node run in the pod can drain and exit gracefully.  This may be that added time per-pod is exceeding the maximum wait time for the tiller reaper.  The only thing left on the cluster is the statefulset set to 0:0 pods.

**Comment by mikeln** [comment]
That is the issue.   When I set the pod lifecycle hook delay much lower, then everything gets deleted (i.e. tiller does not timeout waiting for the statefulset to finish deletion).

Not sure how to specify the timeout value for tiller.   Passing it in on the helm delete command --timeout=<seconds>  does not seem to do anything.  --debug does not seem to show anything.   I suspect this deserves an issue in helm/tiller.

**Comment by mikeln** [comment]
opened helm issue: https://github.com/kubernetes/helm/issues/2578
