### ISSUE TITLE
Document motivation to start K2 project after Kraken

### ISSUE THREAD

**Issue by somejfn** [samsung-cnct/k2#46]
Hi,

It would be great if you could share the motivations behind starting K2 and what lead you to start from scratch after Kraken.  

regards,

Jean-Francois

**Comment by coffeepac** [comment]
@somejfn sorry for the long wait on this.  We have updated the README for this project and included the motivations for the rebuild.  

if you have any further questions please open up an issue.  We will be more responsive going forward.
