### ISSUE TITLE
helm override cleanup

### ISSUE THREAD

**Issue by coffeepac** [samsung-cnct/k2#461]
the helm override environment variable needs two additional pieces of work:
1. a new, optional cluster-level key in the config file that allows for overriding
   - this is in addition to the current env variable
   - needs to include an update to the schema spec
2. documentation about this feature
   - a new heading with "Handling unsupported versions of Helm" with a quick description of what this is for and how to set either the env var or the config flag

Prior PR: https://github.com/samsung-cnct/k2/pull/390/files
Prior Issue: https://github.com/samsung-cnct/k2/issues/284

**Comment by mikeln** [comment]
Also,  not sure the current check is valid on a ./down.sh.   I don't think down should abort out if the flag is missing.

**Comment by coffeepac** [comment]
helm cleanup may be doing something specific with hooks or something.  we would want to notify that that may fail.

**Comment by mikeln** [comment]
perform the attempt, but warn it may have issues. yes that would be ok.

**Comment by guineveresaenger** [comment]
So I'm hearing the env variable should be left in? What about making it a proper flag instead (I only just learned how to do this on my current ticket)? 
@mikeln can you explain the circumstances under which the process shorts out on ./down.sh? I imagine this could be handled with a `when` statement.
I'm a little bit uncomfortable with having both an optional key in the config file as well as an env variable. The logic feels really bloated as it is already.

**Comment by mikeln** [comment]
yes, leave the env var in.   add a check for a flag on the cluster...  like `cluster.helm_override`

The helm override check needs to work differently on "down".  Right now it errors out, but it should print a warning and let it keep running.     If you run version 1.6.x  you'll see it.

**Comment by guineveresaenger** [comment]
Ha. I'm looking into this, and I finally understand what you two were talking about earlier @mikeln @coffeepac . Yes, we do need helm on cluster down, in order to kill services. If we had helm on cluster up, that is. It is confusing to me. Would an env variable not go away if you started a different terminal session? This does seem to indicate, that, yes, we do want to prompt for helm override on cluster down as well. What is the advantage of a warning? And what would need to be cleaned up if services were running but no helm was available or specified?

**Comment by mikeln** [comment]
The idea is to use whatever helm is available to bring down all the services...that is the most important part.  The fact that the wrong helm version may be the only one available, doesn't matter.  Just tell the user that perhaps things may not get deleted correctly.   

Also, helm really has to be used to bring down services started with helm...so it keeps its DB clean.

**Comment by guineveresaenger** [comment]
Okay, so you're saying down should default to using helm - any helm - always. This makes snese. I can do that.

**Comment by davidewatson** [comment]
Is it possible to specify helm_override using a command line option? Should there be? If so, does it make sense to fold this option into the existing --force option? This is already used to continue even if the schema is deprecated, so maybe I am mixing use cases here, but I like the simplicity of it. I worry about the proliferation of temporary or rarely used options...

**Comment by guineveresaenger** [comment]
PR: #473
