### ISSUE TITLE
show_post_cluster giving wrong helm command

### ISSUE THREAD

**Issue by DStorck** [samsung-cnct/k2#462]
currently after running `up` , we are displaying info about how to run various commands, one of which is : 
```
To use helm:
------------

    KUBECONFIG=/root/.kraken/ds-may-31/admin.kubeconfig helm \
      HELM_HOME=/root/.kraken/ds-may-31/.helm \
      helm <helm command>
```
this doesn't appear to actually work, and should show something like :
```
KUBECONFIG=${KRAKEN_BASE}/<your cluster name>/admin.kubeconfig helm <helm command> --home ${KRAKEN_BASE}/<your cluster name>/.helm
```

**Comment by DStorck** [comment]
there is an extra `helm` in the example command, and since i always have to edit the `root` to be `$HOME`, cutting and pasting that command into a terminal is not user friendly at all

**Comment by coffeepac** [comment]
MERGED
