### ISSUE TITLE
change default aws region to us-east-1

### ISSUE THREAD

**Issue by coffeepac** [samsung-cnct/k2#465]
default region is currently us-east-2 for keeping CI stuff siloed.  However, this means as people on our team regenerate their configs they will end up in the CI region.

We should:
- change the default to us-east-1 (or us-west-2, either one)
- alter the CI process to use us-east-2 instead by re-writing the config file after generation
  - just a couple of sed one-liners will do

**Comment by joejulian** [comment]
Covfefe

**Comment by davidewatson** [comment]
+1 for us-east-1 over us-west...
