### ISSUE TITLE
RBAC Kubernetes v1.6 Round 2

### ISSUE THREAD

**Issue by mikeln** [samsung-cnct/k2#479]
Follow on to: #184 

How to De-escalate the initial cluster user? (or let kubectl "in pods" be elevated, but external user kubectl be lesser?).

External RBAC auth server functionality validation.

**Comment by mikeln** [comment]
This needs to updated for the newer k2recon and v1.6: https://github.com/samsung-cnct/k2/tree/3211cfc96fb21bb71115b94b93a4380ad3dfd054/Documentation/security

**Comment by mikeln** [comment]
Joe has been running OIDC/rbac/1.6 successfully, so I will call that good.

**Comment by mikeln** [comment]
Back to this. 
How to create a limited privilege user?
Looks like: 
1) create another certificate with `/O=<some user rbac group name> /CN=kraken-ca`
1.1) assume we would generate a cert for each user potentially defined in the config.yaml.  We should use the `group` in the cert `/O` entry.   Currently it is hard coded.
2) add nopriv user to generated admin.config ... or probably better, create a separate nopriv.config file for distribution.  In this way, they end user will not have incidental access to the admin.config info, and the ability to change to the admin user.
2.1) config.yaml could potentially have more entries for user/pw... however it looks like the ansible code uses the first entry it finds as the default user (and assumes it will be the admin).  This would need to change...or explicitly state this assumption.  
3) distribute the admin.config to the nodes as usual.  distribute the nopriv config to the user.  However, for development we would want all configs distributed to the user, we need the admin to do anything meaningful with the cluster.

**Comment by coffeepac** [comment]
re: 2.1 there is a `default_basic_user` key and it seems to be getting used in `generate-admin-kubeconfig.yaml` or am I misreading that?

**Comment by mikeln** [comment]
you are correct.  that label would become a misnomer, or we will need to add `default_admin_user:`
and use that to generate the admin config vs a nonpriv user config.

**Comment by mikeln** [comment]
Looking at this from another non-rbac POV.   Do we want to generate key pairs for all users that may be defined in our config users.  i.e. every user has their own key pair and kube.config file?

My first though was creating a non-priveleged access based on our current `admin.kubeconfig` file.  This includes creating a key pair with the correct rbac group encoded within.   However, our config file setup allows for multiple users, and each user has to specify an access group (which is that user's rbac info). 

So, to answer my own question, yes... we will have to create keypairs for each user in the config file, because of the possibility that the user's rbac group is different.

we would rename the admin to `default_admin_user:`.  which would create: `admin.kubeconfig` with the  appropriate keypair and rbac.

but also, for each user in the config we would need to create:  `<username>.kubeconfig` with their own keypair/rbac.   And the default context in each one would be their own user.

Actually, the `default_admin_user` could point at any user (but would only really be valid is the user had the `system:master` rbac group).   I guess we could leverage a "convention" that that user has to be named "admin"... or we could take whatever user and create `admin.kubeconfig` with that data.  (probably a better idea).

I don't think we want a single `xxxx.kubeconfig` with all the users within.  Then anyone who has access to it could just become the `superuser` for the cluster.

**Comment by mikeln** [comment]
So, initial testing with a nopriv user... not sure when you would use that one.  You can only get access to info on your own things in the cluster (but not create new things)...so you can't user it to create anything in the first place to see...

**Comment by mikeln** [comment]
The next question.. what is the intent of the users definition in the config file?

**Comment by mikeln** [comment]
experiment.  use defined user/passwords since basic auth is running.
```mikeln-bender:k2 Mikel_Nelson$ kubectl --kubeconfig=/Users/Mikel_Nelson/dev/cloud/k2new/myconfig/.kraken/mikeln-rb6/admin.kubeconfig get all --all-namespaces --user mikeln-rb6_nopriv
Error from server (Forbidden): User "system:anonymous" cannot list pods at the cluster scope. (get pods)
Error from server (Forbidden): User "system:anonymous" cannot list replicationcontrollers at the cluster scope. (get replicationcontrollers)
Error from server (Forbidden): User "system:anonymous" cannot list services at the cluster scope. (get services)
Error from server (Forbidden): User "system:anonymous" cannot list statefulsets.apps at the cluster scope. (get statefulsets.apps)
Error from server (Forbidden): User "system:anonymous" cannot list horizontalpodautoscalers.autoscaling at the cluster scope. (get horizontalpodautoscalers.autoscaling)
Error from server (Forbidden): User "system:anonymous" cannot list jobs.batch at the cluster scope. (get jobs.batch)
Error from server (Forbidden): User "system:anonymous" cannot list deployments.extensions at the cluster scope. (get deployments.extensions)
Error from server (Forbidden): User "system:anonymous" cannot list replicasets.extensions at the cluster scope. (get replicasets.extensions)

mikeln-bender:k2 Mikel_Nelson$ kubectl --kubeconfig=/Users/Mikel_Nelson/dev/cloud/k2new/myconfig/.kraken/mikeln-rb6/admin.kubeconfig get all --all-namespaces --user mikeln-rb6_disc
Error from server (Forbidden): User "system:anonymous" cannot list pods at the cluster scope. (get pods)
Error from server (Forbidden): User "system:anonymous" cannot list replicationcontrollers at the cluster scope. (get replicationcontrollers)
Error from server (Forbidden): User "system:anonymous" cannot list services at the cluster scope. (get services)
Error from server (Forbidden): User "system:anonymous" cannot list statefulsets.apps at the cluster scope. (get statefulsets.apps)
Error from server (Forbidden): User "system:anonymous" cannot list horizontalpodautoscalers.autoscaling at the cluster scope. (get horizontalpodautoscalers.autoscaling)
Error from server (Forbidden): User "system:anonymous" cannot list jobs.batch at the cluster scope. (get jobs.batch)
Error from server (Forbidden): User "system:anonymous" cannot list deployments.extensions at the cluster scope. (get deployments.extensions)
Error from server (Forbidden): User "system:anonymous" cannot list replicasets.extensions at the cluster scope. (get replicasets.extensions)
```
Note the response is incorrect.   `system:anonymous` means the cluster did not pickup the rbac group from the basic auth file based on the username/pw alone.

Next will use a different cert.

**Comment by mikeln** [comment]
As opposed to a nopriv user with a separate cert:
```
mikeln-bender:k2 Mikel_Nelson$ kubectl --kubeconfig=/Users/Mikel_Nelson/dev/cloud/k2new/myconfig/.kraken/mikeln-rb6/nopriv.kubeconfig get all --all-namespaces
Error from server (Forbidden): User "kraken-ca" cannot list pods at the cluster scope. (get pods)
Error from server (Forbidden): User "kraken-ca" cannot list replicationcontrollers at the cluster scope. (get replicationcontrollers)
Error from server (Forbidden): User "kraken-ca" cannot list services at the cluster scope. (get services)
Error from server (Forbidden): User "kraken-ca" cannot list statefulsets.apps at the cluster scope. (get statefulsets.apps)
Error from server (Forbidden): User "kraken-ca" cannot list horizontalpodautoscalers.autoscaling at the cluster scope. (get horizontalpodautoscalers.autoscaling)
Error from server (Forbidden): User "kraken-ca" cannot list jobs.batch at the cluster scope. (get jobs.batch)
Error from server (Forbidden): User "kraken-ca" cannot list deployments.extensions at the cluster scope. (get deployments.extensions)
Error from server (Forbidden): User "kraken-ca" cannot list replicasets.extensions at the cluster scope. (get replicasets.extensions)
```

**Comment by mikeln** [comment]
These are the users I have defined in my cluster.  You see that basic auth has the rbac groups associated.

```
cat /etc/kubernetes/basicauth.csv
      FlusterFools,admin,1,"system:masters"
      FlusterFoolers,nopriv,2,"system:basic-user"
      FlusterFoolers,user2,3,"system:discovery"
```

**Comment by mikeln** [comment]
ok.  Just for fun.  I turned off basic auth, but left in the generation of the basic auth file.  Switched to keypair only access. 
Changed kraken.access to create a new keypair and kubeconfig for each user defined in the k2 authn section.   The key here is to generate the keys with: `sub=\CN=<username>\O=<group/rbac group>`, and use the k2 cluster CA.  Kubernetes uses the `\CN` value as the username.

**Comment by alejandroEsc** [comment]
awesome, what did you find out?

**Comment by mikeln** [comment]
seems to work fine....but far from a thorough test.   What I can validate is that the username is pulled from the key CN value.

**Comment by mikeln** [comment]
so for fun.. added a user in our config `user2`. with a undefined group of `user2`.
(incidentally created a user2 serviceaccount by hand also).
```
mikeln-bender:k2 Mikel_Nelson$ kubectl --kubeconfig=/Users/Mikel_Nelson/dev/cloud/k2new/myconfig/.kraken/mikeln-rb6/user-user2.kubeconfig get serviceaccount
Error from server (Forbidden): User "user2" cannot list serviceaccounts in the namespace "default". (get serviceaccounts)
```
```
Then via kubectl (admin user), added:
```
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: user2-clusterrolebinding
subjects:
- kind: User
  name: user2
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: ""
```
```
mikeln-bender:k2 Mikel_Nelson$ kubectl --kubeconfig=/Users/Mikel_Nelson/dev/cloud/k2new/myconfig/.kraken/mikeln-rb6/user-user2.kubeconfig get serviceaccount
NAME      SECRETS   AGE
default   1         44m
user2     1         10m
```

**Comment by mikeln** [comment]
or some other fun..

```
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: user2-role
  namespace: default
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["pods", "serviceaccounts"]
  verbs: ["get", "list", "watch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: user2-rolebinding
subjects:
- kind: User
  name: user2
roleRef:
  kind: Role
  name: user2-role
  apiGroup: ""
```
```
mikeln-bender:k2 Mikel_Nelson$ kubectl --kubeconfig=/Users/Mikel_Nelson/dev/cloud/k2new/myconfig/.kraken/mikeln-rb6/user-user2.kubeconfig get all
NAME         READY     STATUS    RESTARTS   AGE
po/busybox   1/1       Running   0          24s
Error from server (Forbidden): User "user2" cannot list replicationcontrollers in the namespace "default". (get replicationcontrollers)
Error from server (Forbidden): User "user2" cannot list services in the namespace "default". (get services)
Error from server (Forbidden): User "user2" cannot list statefulsets.apps in the namespace "default". (get statefulsets.apps)
Error from server (Forbidden): User "user2" cannot list horizontalpodautoscalers.autoscaling in the namespace "default". (get horizontalpodautoscalers.autoscaling)
Error from server (Forbidden): User "user2" cannot list jobs.batch in the namespace "default". (get jobs.batch)
Error from server (Forbidden): User "user2" cannot list deployments.extensions in the namespace "default". (get deployments.extensions)
Error from server (Forbidden): User "user2" cannot list replicasets.extensions in the namespace "default". (get replicasets.extensions)
```

**Comment by mikeln** [comment]
Some conclusions:
- Using key/cert auth, the \O=<> value is used as the user rbac.
- However, defining a binding for the user overrides that key/cert rbac.
- Possible security hole..(maybe)..  If a restricted user has the cluster CA, and generates a new key with \O=system:master  (superuser).. the user should supposedly be upgraded to superuser.  However, if a rolebinding is added for the user, it appears possible to restrict that user.
- If this is true, then you could also "accidentally" downgrade the cluster admin user...and render your admin unusable. (another thing to test).

**Comment by mikeln** [comment]
Experiments: 1) unable to downgrade admin user (with Role, RoleBinding).  Was able to install the role, but didn't seem to affect the ability of admin user.

**Comment by mikeln** [comment]
Conclusion Action/Questions:

1) Do we want to allow config disable of BasicAuth?
2) Do we want to allow config enable of User Cert Auth, with separate <user>.kubeconfig files generated?
3) Do we want to include all users (defined in the config) in the admin.kubeconfig file (with either auth method?).

**Comment by coffeepac** [comment]
I would say yes, yes and no.  

1. security conscious people are going to want to disable this.  This seems fairly important.
2. generating or importing certs for non-admin users and creating separate admin.kubeconfig files would be a good way to let K2 manage the user creation portion.  is there an easy way to invalidate and regenerate these certs?  This seems important but something to maybe file an issue on and handle later.
3. I don't see the benefit of this, other then having a master list of users outside the cluster.

**Comment by mikeln** [comment]
as for the cert thing... I was wondering that also:
1) Generate the user keys with an outside cert.
2) Use a given user key, and a given user cert would need to be known also in the system.
Will need another issue for this.

For now, generating each user's key is easy first step.

**Comment by coffeepac** [comment]
okay, sounds good.  

for the follow on issue for certs can you make sure to label it with 'The Certificate Management Experience'?  We have a bunch of security work to do in that label.
