### ISSUE TITLE
Support Weave CNI

### ISSUE THREAD

**Issue by alejandroEsc** [samsung-cnct/k2#485]
Requesting new feature: Allowing to use the weave cni fabric to k2.

**Comment by alejandroEsc** [comment]
currently working on this, fyi, prelim PR coming soon.

**Comment by sostheim** [comment]
Thanks for creating the issue to track your work.
cc: @coffeepac

**Comment by alejandroEsc** [comment]
I will be moving the readme items soon, and they are not necessarily part of this issue, so we can close this. @sostheim @davidewatson  @coffeepac are you ok with this?

**Comment by coffeepac** [comment]
good bye, dear issues.
