### ISSUE TITLE
helm permission denied

### ISSUE THREAD

**Issue by davidewatson** [samsung-cnct/k2#493]
I am running k2 version 65c9194b86b61c5b0f2b194c9e2e49b45c2aa2c5 "rbac 16 hotfix", using a config generated by a previous version of k2, and receiving this error:

> fatal: [localhost]: FAILED! => {"changed": false, "cmd": "/opt/cnct/kubernetes/v1.5/bin/helm init", "failed": true, "msg": "[Errno 13] Permission denied", "rc": 13}

**Comment by davidewatson** [comment]
May be related to #491

**Comment by mikeln** [comment]
you are running v1.5.x  so v1.6 rbac should not be a concern.  Unless you specifically turned on rbac.

**Comment by coffeepac** [comment]
seems to have resolved itself.  away.
