### ISSUE TITLE
helmOveride not defined

### ISSUE THREAD

**Issue by davidewatson** [samsung-cnct/k2#496]
helmOverride needs a default in ansible, and if not already done, it should be added as an _optional_ property in the schema.

>TASK [kraken.config : Set overall helm_override to env var if it has been set, config var if not] ***
fatal: [localhost]: FAILED! => {"failed": true, "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'dict object' has no attribute 'helmOverride'\n\nThe error appears to have been in '/workspace/ansible/roles/kraken.config/tasks/helm-versioning.yaml': line 8, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Set overall helm_override to env var if it has been set, config var if not\n  ^ here\n"}

**Comment by coffeepac** [comment]
helmOveride should have no default.  it should be marked optional

**Comment by blackdog0403** [comment]
Yes, it should be marked optional but, up.sh doesn't not work without setting up helm_override_xxx env or set key helmOverride in schema at the moment 

It doesn't looks good to me that users cannot run without setup things.

That would better have helmOverride = false default or it needs some excetional process that user don't set value for helmOverride

**Comment by davidewatson** [comment]
Fixed by #497.
