### ISSUE TITLE
Add a valid_config command

### ISSUE THREAD

**Issue by NathanZook** [samsung-cnct/k2#498]
Anything which reads the config file needs to 1) interpret it the same way, and 2) be certain that the configuration is valid.  ~~3) The validation step must not create a race condition.~~

The valid_config command will resolve the configuration, and will succeed of fail.

**Comment by davidewatson** [comment]
I like it! Can we use our active voices by renaming the option --validate (for k2/k2cli), and validate_config for internal ansible use? Good English makes for good code (maybe).

**Comment by NathanZook** [comment]
Right now, this feels like validate_config.sh

**Comment by davidewatson** [comment]
I'd prefer `k2/up.sh --validate --config dewMagic.yaml` over `k2/hack/validate_config.sh`, but ¯\_(ツ)_/¯.

**Comment by alejandroEsc** [comment]
--validate-config IMHO.

**Comment by blackdog0403** [comment]
—IMHO, “k2/up.sh —validate —config xxx.yaml” looks good to me for consistency : )

**Comment by NathanZook** [comment]
Sticking this in the review pile for Common Tools.

**Comment by coffeepac** [comment]
downgraded to wait for config file package export from k2 to its own repo

**Comment by coffeepac** [comment]
being done as part of a onboarding golang project.
