### ISSUE TITLE
Implement Deis workflow on K2

### ISSUE THREAD

**Issue by cwazy1** [samsung-cnct/k2#51]
From jira- 7/13/16

docker 1.11 doesn't get along well with deis at present
make sure we're either running with coreos pinned to something earlier than 1097.0.0, or that this issue has been addressed in a later version of coreos
https://github.com/deis/registry/issues/60

**Comment by bacongobbler** [comment]
Just a heads up: deis/registry#64

We currently target Kubernetes v1.3.4+ which uses Docker v1.10.3

**Comment by coffeepac** [comment]
this has been resolved upstream
