### ISSUE TITLE
convert dashes to underscores for cluster names in helmOverride code path

### ISSUE THREAD

**Issue by coffeepac** [samsung-cnct/k2#513]
dashes are not available to be used in the identifiers for environment variables but dashes need to be allowable in the cluster names.  underscores are not available for use in cluster names as we use the cluster name as part of a DNS entry.

this issue should:
- update the helmOverride environment variable ansible task to convert any dashes to underscores when creating or looking for an environment variable (make sure to update the help text as well)
- update the json schema for clusterName to disallow underscores

**Comment by yenicapotediaz** [comment]
PR: https://github.com/samsung-cnct/k2/pull/733
