### ISSUE TITLE
Should we move all these shell scripts into bin?

### ISSUE THREAD

**Issue by NathanZook** [samsung-cnct/k2#525]
We seem to be accumulating shell scripts in the root of k2.  This gets trashy.  We could move them into bin, and then add /kraken/bin to the path.

**Comment by coffeepac** [comment]
👍

**Comment by guineveresaenger** [comment]
PR: #718

**Comment by leahnp** [comment]
LGTM closing due to similarity of: https://github.com/samsung-cnct/k2cli/issues/124
