### ISSUE TITLE
Wait for API Server Superfluous

### ISSUE THREAD

**Issue by mikeln** [samsung-cnct/k2#540]
The reorganization of ansible role order needed for RBAC should always guarantee that the kubernetes apis server is available.  The startup has to wait for kubectl to be viable (hence that the api server is available) to install the needed system RBAC before anything else can occur.   

The api server should be available for anything after that step.

The 'Wait for API server' tasks after that step should be able to be removed.

**Comment by mikeln** [comment]
plus all of these steps where broken during k2recon, and not fixed.  The current do nothing.

**Comment by davidewatson** [comment]
A list of existing apiserver waits:
```
rodin:k2 dwat$ grep -ir 'wait for api' ansible
ansible/roles/kraken.rbac/tasks/build-access.yaml:- name: Wait for api server response before continuing
ansible/roles/kraken.readiness/tasks/do-wait.yaml:- name: Wait for api server to become available in case it is not
ansible/roles/kraken.services/tasks/run-dns.yaml:- name: Wait for api server to become available in case it is not already
ansible/roles/kraken.services/tasks/run-services.yaml:- name: Wait for api server to become available in case it's not
rodin:k2 dwat$
```

**Comment by davidewatson** [comment]
For reference, role dependency ordering [documentation](http://docs.ansible.com/ansible/playbooks_roles.html#role-dependencies).
