### ISSUE TITLE
Move *.pyc declaration from filter_plugins directories to root

### ISSUE THREAD

**Issue by NathanZook** [samsung-cnct/k2#551]
Safer & cleaner.  

This is for .gitignore files

**Comment by alejandroEsc** [comment]
This change should include:

- cleanup 
- organization
- and additional items as defined by the team.

Please make sure  to add commonly ignored items to the solas repository. Even if the project does not implement such artifacts its good to have the full list of ignorable items we do not expect. Each project can customize if they so wish to remove any items they do not feel are necessary. You can create a ticket there if you want, and reference it back here.
