### ISSUE TITLE
add $$target link to k2/schemas/config/v1/weaveFabricNetwork.json

### ISSUE THREAD

**Issue by coffeepac** [samsung-cnct/k2#555]
in the interest of getting a critical feature merged, we allowed a doc fix to slip. this needs to be addressed.

the jsonSchema file k2/schemas/config/v1/weaveFabricNetwork.json does not have the required $$target link.  Please see [this comment](https://github.com/samsung-cnct/k2/pull/538/files/6cc93c896b746e505a386ecf21dc18730e73b9a7#diff-05181d85a4ba37419eed246b4afa9ba9) for the exact change to make

**Comment by alejandroEsc** [comment]
I believe I have since resolved this. closing the ticket.

**Comment by coffeepac** [comment]
ahh, yeah.  if you had said 'fixes #555' in the linked PR when the PR was merged this issue would have been auto-closed.

**Comment by alejandroEsc** [comment]
oh i didnt know! awesome :)
