### ISSUE TITLE
Disc full errors on clusters 4+ days old

### ISSUE THREAD

**Issue by leahnp** [samsung-cnct/k2#56]
'Overlay' filesystem at 100% capacity, not allowing new pods to spin up on clusters 4+ days old. 
<img width="1016" alt="screen shot 2016-10-14 at 9 32 31 am" src="https://cloud.githubusercontent.com/assets/13352646/19395190/38222cc2-91f1-11e6-9ddc-73f8c9d6d25d.png">

**Comment by l337ch** [comment]
we're going to need to remount the rkt volumes on the extended storage disk @venezia

**Comment by coffeepac** [comment]
was resolved awhile ago:  /var/lib/docker now has its own 100GB EBS volume.
