### ISSUE TITLE
Security Example Updates for General Use

### ISSUE THREAD

**Issue by mikeln** [samsung-cnct/k2#567]
The security example and files is specific to Keyolk,  and should be made generic.
(e.g. namespace, quay.io images, etc).

**Comment by DStorck** [comment]
@joejulian @coffeepac Can I do an overhaul of this to have it refer to [this](https://github.com/samsung-cnct/chart-dex/blob/master/dex/README.md) instead? The config in this is seriously out of date.

**Comment by DStorck** [comment]
https://github.com/samsung-cnct/k2/pull/723
