### ISSUE TITLE
k2 etcd cluster names and tokens may not be unique

### ISSUE THREAD

**Issue by davidewatson** [samsung-cnct/k2#574]
Each etcd instance is started with a cluster token set within `ansible/roles/kraken.nodePool/kraken.etcd.docker/templates/etcd.units.etcd.part.jinja2 `:

```
     --discovery-srv {{cluster_node_tuple.1.name}}.{{cluster_node_tuple.0.name}}.internal \
...
     --initial-cluster-token {{cluster_node_tuple.1.etcdConfig.clusterToken}} \
```

Since the clusterToken is fixed, two k2 clusters with the same name could attempt to form an etcd cluster together. Note that this might not affect our CI, because, at least for the k2 PR job, the job number is included in the cluster name (e.g. `sed -i -e s/- name:[[:space:]]*$/- name: master-138/ cluster/aws/config.yaml`).

For more information on etcd discovery, see the [Clustering Guide](https://coreos.com/etcd/docs/latest/v2/clustering.html#dns-discovery) and the [Discovery Service Protocol](https://coreos.com/etcd/docs/latest/v2/discovery_protocol.html).

This is related to https://github.com/samsung-cnct/k2/issues/353 and https://github.com/samsung-cnct/k2/pull/351 (which introduced the problem). It may or may not be fixed by the solution to https://github.com/samsung-cnct/k2/issues/559.

**Comment by joejulian** [comment]
Two k2 clusters will be in two independent networks. There should be no way for the two etcd clusters to discover each other.

**Comment by coffeepac** [comment]
This will be a possible problem after we make it allowable to use an existing VPC.  That work is slated for the current sprint.

**Comment by coffeepac** [comment]
blocked by a k2-tools issue RE: bunch of stuff happens twice in the dockerfile build and its weird.

**Comment by coffeepac** [comment]
@davidewatson are you working on this?  if so, please assign it to yourself.  if not I'll chuck it back to ToDo
