### ISSUE TITLE
Check-clusters-lock runs on update when it shouldn't (and thus prevents update)

### ISSUE THREAD

**Issue by guineveresaenger** [samsung-cnct/k2#581]
Currently the update functionality breaks on cluster update due to check-clusters-lock.yaml running even though the kraken action should be update.
Possibly the defaults in kraken.config/defaults/main.yaml override?

**Comment by guineveresaenger** [comment]
I am having trouble duplicating this error today.

**Comment by blackdog0403** [comment]
k2cli version: 1.0.3-alpha+git.sha.5e06aeda22c43c62ef0e7808723339b091ffa260

```
$ k2cli cluster update ~/.kraken/mochalatte.yaml
...
TASK [kraken.config : Fail when cluster.status.lock file exists] ***************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Spinning up  mochalatte cluster has been canceled due to its already completed."}
...

**Comment by blackdog0403** [comment]
My k2cli was out of dated. I installed it through brew.

**Comment by guineveresaenger** [comment]
Hm. Can you try with locally built ./k2cli?

**Comment by guineveresaenger** [comment]
right

**Comment by guineveresaenger** [comment]
Closing this because error could not be reproduced.
