### ISSUE TITLE
e2e tests failing with apparent usage error

### ISSUE THREAD

**Issue by coffeepac** [samsung-cnct/k2#585]
it appears that the e2e job in our K2 pipeline is failing with an error about flag usage.  that's unfortunate and needs to be fixed.

**Comment by coffeepac** [comment]
fatal error shows up in master build after merging CoreOS pinned version.  the error is present in the prior run that uses 'latest'  instead of a pinned version.  going to try and use the newest CoreOS version and see if that sorts it out.

**Comment by coffeepac** [comment]
bumping to latest version of CoreOS did not work.  going to see if a new version of Kubernetes was released for this.

**Comment by mikeln** [comment]
what is the error?

**Comment by coffeepac** [comment]
> + go run hack/e2e.go --v --test '--test_args=--ginkgo.v=true --ginkgo.noColor=true --ginkgo.focus=\[Conformance\] --ginkgo.skip=\[Serial\] --e2e-output-dir=/home/jenkins/workspace/K2_PR-587-RH4TIYZNYTMJQ3ZZQ2KEQGYYIXXXHXX5SJVG66XF5ECFDBC4BQWQ/output/artifacts --report-dir=/home/jenkins/workspace/K2_PR-587-RH4TIYZNYTMJQ3ZZQ2KEQGYYIXXXHXX5SJVG66XF5ECFDBC4BQWQ/output/artifacts' --check_version_skew=false
flag provided but not defined: -v
Usage of /tmp/go-build252246307/command-line-arguments/_obj/exe/e2e:
  -get
    	go get -u kubetest if old or not installed (default true)
  -old duration
    	Consider kubetest old if it exceeds this (default 24h0m0s)
2017/06/29 16:47:19 e2e.go:54: NOTICE: go run hack/e2e.go is now a shim for test-infra/kubetest
2017/06/29 16:47:19 e2e.go:55:   Usage: go run hack/e2e.go [--get=true] [--old=24h0m0s] -- [KUBETEST_ARGS]
2017/06/29 16:47:19 e2e.go:56:   The separator is required to use --get or --old flags
2017/06/29 16:47:19 e2e.go:57:   The -- flag separator also suppresses this message
2017/06/29 16:47:19 e2e.go:146: Updating kubetest binary...
2017/06/29 16:47:24 e2e.go:76: Calling kubetest --v --test --test_args=--ginkgo.v=true --ginkgo.noColor=true --ginkgo.focus=\[Conformance\] --ginkgo.skip=\[Serial\] --e2e-output-dir=/home/jenkins/workspace/K2_PR-587-RH4TIYZNYTMJQ3ZZQ2KEQGYYIXXXHXX5SJVG66XF5ECFDBC4BQWQ/output/artifacts --report-dir=/home/jenkins/workspace/K2_PR-587-RH4TIYZNYTMJQ3ZZQ2KEQGYYIXXXHXX5SJVG66XF5ECFDBC4BQWQ/output/artifacts --check_version_skew=false...
flag provided but not defined: -check_version_skew
Usage of /home/jenkins/workspace/K2_PR-587-RH4TIYZNYTMJQ3ZZQ2KEQGYYIXXXHXX5SJVG66XF5ECFDBC4BQWQ/go/bin/kubetest:
  -build
    	Rebuild k8s binaries, optionally forcing (release|quick|bazel) stategy
  -charts
    	If true, run charts tests
  -check-leaked-resources
    	Ensure project ends with the same resources
  -check-version-skew
    	Verify client and server versions match (default true)
  -deployment string
    	Choices: none/bash/kops/kubernetes-anywhere (default "bash")
<SNIP>

what's weird is the 'flag provided but not defined' error occurs in other, successful jobs.

**Comment by coffeepac** [comment]
attempting a run while removing the listed offending flag.  going to try and find the RCA for what might of done this.  

the latest K2 merge to master seems benign and this is affecting PRs so this suggests k2-tools change.

**Comment by mikeln** [comment]
there 2 flag errors...   `-v` and `-check_version_skew`
the second should be: `-check-version-skew`  (not underscores)

**Comment by coffeepac** [comment]
the e2e tester image has an env var which looks suspicious in general:

`KUBERNETES_VERSION=v1.3.2`

if flag removal, or as @mikeln has pointed out, flag correction doesn't work I'll start working on the e2e tester image.

**Comment by mikeln** [comment]
Ahh, I see... hack/e2e.go doesn't like `-v`.    kubetest doesn't like `-check_version_skew`

**Comment by mikeln** [comment]
looks like we need to also add `--` per the `e2e.go` usage line.  e.g. `e2e.go -- --v --test ... `

**Comment by coffeepac** [comment]
oh, right.  okay.  I'll toss that in as well then.

**Comment by coffeepac** [comment]
@mikeln PR is ready to go. Can you check it out?   Aws stuff passed.  Waiting on GKE.

**Comment by davidewatson** [comment]
Is https://github.com/samsung-cnct/k2/pull/587 backwards compatible with previous k8s releases? Mainly just curious if we need to follow up on the fix, post p0...

**Comment by coffeepac** [comment]
@davidewatson I'm not sure why this started happening, but the issues have been present since I forklifted this code from pipelet during the 1.5 days.
