### ISSUE TITLE
Should be able to specify kubernetes node labels per node pool.

### ISSUE THREAD

**Issue by maratoid** [samsung-cnct/k2#59]
As a k2 user i should be able to specify kubernetes node labels in my k2 configuration file.

**Comment by blackdog0403** [comment]
Memo For easy following 
### Related files

#### config file : config.yaml, gke-config.ymal

https://github.com/blackdog0403/k2/blob/master/ansible/roles/kraken.config/files/schema/v1alpha.json
https://github.com/blackdog0403/k2/blob/master/ansible/roles/kraken.config/files/config.yaml
https://github.com/blackdog0403/k2/blob/master/ansible/roles/kraken.config/files/gke-config.yaml

#### role : render-units.yaml
https://github.com/blackdog0403/k2/blob/master/ansible/roles/kraken.nodePool/kraken.node.docker/tasks/render-units.yaml

#### jinja2 template : units.kubelet.part.jinja2
https://github.com/blackdog0403/k2/blob/master/ansible/roles/kraken.nodePool/kraken.node.docker/templates/units.kubelet.part.jinja2

```
(...)
--node-labels=nodepool={{node.name}} \
(...)
```

**Comment by blackdog0403** [comment]
User can specify kubernetes labels per node pool.

**Comment by blackdog0403** [comment]
modify document for "Node Configurations fort node on AWS"

**Comment by blackdog0403** [comment]
PR: [PR-452] (https://github.com/samsung-cnct/k2/pull/452)

**Comment by coffeepac** [comment]
BY GROUP DEMAND.  WORK DONE WELL.
