### ISSUE TITLE
Add helm app repository support

### ISSUE THREAD

**Issue by joejulian** [samsung-cnct/k2#594]
With our charts moving to the [quay app repository](https://quay.io/application/), add config support for utilizing them via the helm repository plugin.

**Comment by coffeepac** [comment]
why is this in TCME?

**Comment by joejulian** [comment]
Originally I was looking at this in the context of kube-lego. It's far less appropriate now.

**Comment by DStorck** [comment]
This has been taken care of, right? https://github.com/samsung-cnct/k2/pull/613
