### ISSUE TITLE
Check path to k2-crash-app logfile exists

### ISSUE THREAD

**Issue by leahnp** [samsung-cnct/k2#595]
Check path to k2-crash-app logfile exists, in common.sh. For the case that someone is not using k2-tools and does not have that path, so it will not crash on them.

**Comment by davidewatson** [comment]
Note that this can also cause an error when the developer is using an older version of k2-tools:

```
bash-4.3# ./up.sh --config ~/.kraken/dewThinkDifferently.yaml 
WARNING: --output not specified. Using /root/.kraken as location
WARNING: all not specified. Using 'all' as tags
tee: /k2-crash-app/logs: No such file or directory
```

**Comment by mikeln** [comment]
I would recommend adding `if [ -f "$log_file" ];then`  tee'd version `else` non-tee'd version `fi`
in up/down/upgrade

**Comment by mikeln** [comment]
Ugg, but you need the "initial file" there hmm... maybe just execute `touch $log_file` no matter what...won't change the file if it is already there (though it will update the timestamp on it...which shouldn't matter as we will be adding to it right away also), but will create a zero length one if missing.

The return ( `$?` ) should be non zero if the file couldn't be created, in which case you would want to avoid running `|tee`...

**Comment by leahnp** [comment]
To review, check the following PR's address the concerns and are merged:

https://github.com/samsung-cnct/k2/pull/601
https://github.com/samsung-cnct/k2-tools/pull/81

**Comment by mikeln** [comment]
everything is in and is working.
