### ISSUE TITLE
Update k8s to 1.6.7 for GKE

### ISSUE THREAD

**Issue by davidewatson** [samsung-cnct/k2#606]
Kubernetes version 1.6.7 is not yet supported on GKE. Verify when it is by checking https://cloud.google.com/container-engine/release-notes, and when it is, update `ansible/roles/kraken.config/files/gke-config.yaml` as was originally done in https://github.com/samsung-cnct/k2/pull/605

**Comment by coffeepac** [comment]
I am considering having the gke version lag the aws version for CI reasons.  If we specify a non-default version of k8s for gke it takes 45+ minutes to create the cluster.  If we use the default version it takes 3 minutes.  

I would like the default behavior for k2 to be fast to spin up. 

Thoughts?

**Comment by davidewatson** [comment]
Seems reasonable. If you are using GKE, you have already decided to let Google manage your control plane...

**Comment by coffeepac** [comment]
@coffeepac to add this to weekly version check:  if GKE CI is taking more then 5 minutes to spin up a cluster, chang ethe default in K2
