### ISSUE TITLE
ERROR! 'loop_control' is not a valid attribute for a Task

### ISSUE THREAD

**Issue by davidewatson** [samsung-cnct/k2#609]
Most of our uses of `loop_control` are for playbooks or roles. Some of them are for individual tasks though. These must be converted before this deprecated feature is removed.

```
[DEPRECATION WARNING]: Specifying include variables at the top-level of the task is deprecated. Please see:

http://docs.ansible.com/ansible/playbooks_roles.html#task-include-files-and-encouraging-reuse

 for currently supported syntax regarding included files and 
variables. This feature will be removed in a future release. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
ERROR! 'loop_control' is not a valid attribute for a Task

The error appears to have been in '/Users/dwat/workspace/k2/ansible/roles/kraken.config/tasks/main.yaml': line 97, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- name: Ensure each nodePool corresponds to exactly one of the node roles (i.e. etcd, master, or node)
  ^ here
```

**Comment by coffeepac** [comment]
Whats the ansible depreciation timeline?  A year?

**Comment by davidewatson** [comment]
Yes, a year. "Ansible is on a 'flexible' 4 month [release schedule](https://docs.ansible.com/ansible/dev_guide/developing_releases.html). This bug report was in err, however. Looking at the [Porting Guide](https://docs.ansible.com/ansible/porting_guide_2.0.html) it appears this warning was removed in version 2.2, and k2-tools uses contains 2.3.
