### ISSUE TITLE
GKE CI jobs failing with authentication errors

### ISSUE THREAD

**Issue by coffeepac** [samsung-cnct/k2#616]
The GKE CI stages are failing CI with errors in the authentication verification task:

`TASK [/home/jenkins/workspace/K2_PR-615-GPZOHJHM7X3Z4J6HRBZZ5N6B72ILPG2YASNOKFKPUGSANKVZAV4Q/ansible/roles/kraken.ssh/kraken.ssh.gke : Get current authentication] ***
fatal: [localhost]: FAILED! => {"changed": true, "cmd": ["gcloud", "auth", "list", "--filter=status:ACTIVE", "--format=value(account)"], "delta": "0:00:00.758554", "end": "2017-07-11 16:52:31.608186", "failed": true, "rc": -11, "start": "2017-07-11 16:52:30.849632", "stderr": "", "stderr_lines": [], "stdout": "patrickrobot@k8s-work.iam.gserviceaccount.com", "stdout_lines": ["patrickrobot@k8s-work.iam.gserviceaccount.com"]}`

**Comment by coffeepac** [comment]
the GKE cluster gets created and then the auth fails.  *me boggles*

**Comment by mikeln** [comment]
maybe the command line args have changed?

**Comment by coffeepac** [comment]
I'm wondering if running the `gcloud auth` multiple times throws a wobbly now.  it used to be idempotent.

**Comment by coffeepac** [comment]
next idea:  the repeated calls to `gcloud auth` change something locally (ansible says so).  My guess is an effective no-op of some gcloud auth statefile.  if this file is busy (some other part of k2 isn't closing it) then we may get an error.  the only '-11' I can find that's at all interesting in this respect is this line:

> lib/googlecloudsdk/core/console/console_attr_os.py:  # stdout handle is -11

Which is pretty thin to support my idea but there we go.  Oh, this is happening on the down as well, I wonder if a first auth call succeeds on down.

**Comment by coffeepac** [comment]
oh hey, I've been looking at the wrong command.  the failing command is `gcloud auth list --filter=status:ACTIVE --format="value(account)"`  And its dumping core (running manually in a CI pod)

**Comment by coffeepac** [comment]
removed the last change to k2-tools, adding the appr install, but that fixed nothing.  going to try and muck with the custom jnlp image.

**Comment by coffeepac** [comment]
cycling through things now:
- changing jnlp image to use 1.6.6 instead of 1.6.1 did nothing
- using /bin/bash instead of /bin/sh in the kubesh function did nothing
- change doesn't appear to have been brought about by any external update (k8s version, helm version, other)
- using `gcloud beta auth list` instead of `gcloud auth list` is currently running

**Comment by mikeln** [comment]
fyi..gcloud sdk just updated to 1.6.2

**Comment by coffeepac** [comment]
ahh nice, it had been about two weeks.  I'll try it out.

**Comment by coffeepac** [comment]
gah.  got a build to go through using gcloud v 128 (accidentally went back too far).  trying again with 162.

although, if 162 fails, I'll just peg it to 128 and be done.

**Comment by coffeepac** [comment]
162 fails.  going to kick it back to 159 and start walking backwards until I find one that works then pin it.

**Comment by coffeepac** [comment]
list of failed versions:
- 162
- 161
- 160
- 150

**Comment by coffeepac** [comment]
reverting all the way back to 128 worked.  going with it.

**Comment by joejulian** [comment]
wait
