### ISSUE TITLE
Add a way for any user to create a simple, non-HA Kubernetes cluster

### ISSUE THREAD

**Issue by lostlivio** [samsung-cnct/k2#621]
A developer using K2 should be able to spin up a simple, non-HA Kubernetes implementation on a single node.  This would be for quick testing or development purposes when a full High Availability Cluster would be overkill in terms of time, complexity, and cost.

**Comment by coffeepac** [comment]
a K2 developer can create a non-HA cluster across three nodes right now: one for etcd, one for the control plane (apiserver, master controller, scheduler) and one node for running kubelet (application pods).  to do this the developer would need to edit a generated config to do this, it doesn't take long.  we could write up some directions for it.

I am not sure we want to invest the time and effort to collapse this further to running all parts of the cluster on a single node.  This would require a large amount of refactoring for a use case we have been intentionally avoiding.

Is the first option sufficient where we have an article for how to convert a generated config to be really simple?

**Comment by leahnp** [comment]
Hey! My fav topic: Who is our target demographic :)

I feel like we have decided out target demographic is a user who needs a HA production-ready cluster and there are better products for spinning up smaller k8s clusters. I will slack you some wikis on this subject if you're interested. I think a decent solution for your needs would be to create a down-sized config, like what @coffeepac described above.

**Comment by lostlivio** [comment]
The target demographic is a Dev who is running tests.  I don't need to stand up a full HA environment.  @coffeepac I would like to understand why we are avoiding this scenario. Are there because there are other options, like kops, that give me this.  As a dev, i want a single tool that gets me from just starting out dev\testing to full production readiness.  We can discuss more with @jandrake as well, but i think we want the option of doing easy to complex at some point.

My line of thinking is that we want developers starting with K2 from the ground floor...as there project grows, we can grow with it.  This is how you get Devs to start using K2 (instead of alternatives) and get them familiar with it and making it their defacto tool for installing kubernetes of all sizes.

**Comment by lostlivio** [comment]
@leahnp The scenario to avoid is...kops handles the easy, but not the complex.  K2 handles the complex but not the easy.  This means Devs are starting with kops and then later on are forced to jump to K2 as the complexity of a project increases.  What happens when kops starts doing easy and complex?  Then there is no reason for them to jump to K2 and we are left with a product that nobody starts with or ends with.

**Comment by coffeepac** [comment]
minikube exists and is far, far better than us, kops or anyone else at getting a kubernetes instance running locally.  if you are going to be spinning things up in a cloud environment you are probably okay with using three servers for a minimal install.  

is three servers too much for a simple thing?  if asking a user to read an article and edit a generated config is too much then we can talk about adding a 'minimal' option to the generate subcommand.

**Comment by lostlivio** [comment]
@coffeepac +1. Agreed, i thought there were some limitations with minikube in terms of feature sets (networking, security, other random thought i can't remember, etc) but I think 3 servers might be a good "getting started with k2" compromise that tackles some of the cost, complexity issues.

**Comment by coffeepac** [comment]
would be okay with that config (1 etcd, 1 master, 1 worker) as something the dev hand crafts from the generated config or do you think its best if we have a 'minimal' option for the config generation command?

**Comment by lostlivio** [comment]
@coffeepac i think its simple enough to just modify the yaml.

**Comment by coffeepac** [comment]
Requirements for this issue:
- add a section to the K2 and/or K2Cli readme that describes exactly what to edit in the default config file to get a minimally viable cluster:  1 etcd node, 1 master node and 1 worker node.
