### ISSUE TITLE
Increase cluster name character limit

### ISSUE THREAD

**Issue by lostlivio** [samsung-cnct/k2#624]
We should increase the cluster name character limit to the max allowed for each cloud provider (or the max of the shortest one if a simpler, faster solution suffices).  The schema check is currently capped at 13 chars which causes an exception to be thrown.

_An exception occurred during task execution. To see the full traceback, use -vvv. The error was:     'TheMotherOfAllClusters'
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_UvKuR3/ansible_module_jsonschema.py\", line 184, in <module>\n    main()\n  File \"/tmp/ansible_UvKuR3/ansible_module_jsonschema.py\", line 180, in main\n    module.fail_json(changed=False, msg=\"Validation failed\", result=result)\n  File \"/tmp/ansible_UvKuR3/ansible_modlib.zip/ansible/module_utils/basic.py\", line 1993, in fail_json\n  File \"/tmp/ansible_UvKuR3/ansible_modlib.zip/ansible/module_utils/basic.py\", line 1973, in _return_formatted\n  File \"/tmp/ansible_UvKuR3/ansible_modlib.zip/ansible/module_utils/basic.py\", line 414, in remove_values\n  File \"/tmp/ansible_UvKuR3/ansible_modlib.zip/ansible/module_utils/basic.py\", line 414, in <genexpr>\n  File \"/tmp/ansible_UvKuR3/ansible_modlib.zip/ansible/module_utils/basic.py\", line 414, in remove_values\n  File \"/tmp/ansible_UvKuR3/ansible_modlib.zip/ansible/module_utils/basic.py\", line 414, in <genexpr>\n  File \"/tmp/ansible_UvKuR3/ansible_modlib.zip/ansible/module_utils/basic.py\", line 425, in remove_values\nTypeError: Value of unknown type: <class 'jsonschema.exceptions.ValidationError'>, 'TheMotherOfAllClusters' is too long\n\nFailed validating u'maxLength' in schema['properties']['deployment'][u'properties'][u'clusters'][u'items'][u'properties'][u'name']:\n    {u'description': u'Name of this cluster.',\n     u'maxLength': 13,\n     u'minLength': 1,\n     u'type': u'string'}\n\nOn instance['deployment'][u'clusters'][0][u'name']:\n    'TheMotherOfAllClusters'\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 0}_

**Comment by yenicapotediaz** [comment]
PR: https://github.com/samsung-cnct/k2/pull/733

**Comment by mikeln** [comment]
fixed by pr
