### ISSUE TITLE
Expose debug logs

### ISSUE THREAD

**Issue by DStorck** [samsung-cnct/k2#63]
I have been having trouble for about a week bringing down a k2 cluster using down.sh  

I usually get stuck here:
 👍 TASK [/kraken/ansible/roles/kraken.provider/kraken.provider.aws : Run terraform destroy] ***
FAILED - RETRYING: TASK: /kraken/ansible/roles/kraken.provider/kraken.provider.aws : Run terraform destroy (10 retries left).
FAILED - RETRYING: TASK: /kraken/ansible/roles/kraken.provider/kraken.provider.aws : Run terraform destroy (9 retries left).
FAILED - RETRYING: TASK: /kraken/ansible/roles/kraken.provider/kraken.provider.aws : Run terraform destroy (8 retries left).

At this point in the down.sh process, I always have things are alive from the cluster on AWS, usually Load Balancers and a VPC, sometimes a subnet.

**Comment by coffeepac** [comment]
@alejandroEsc fixed this.  you can add '-v v[v[v]]' for more verbosity
