### ISSUE TITLE
Ensure user taints are settable when provider is GKE

### ISSUE THREAD

**Issue by coffeepac** [samsung-cnct/k2#631]
Make sure that if a user selects the GKE provider and they set taints for a given nodepool that these taints are applied.

**Comment by DStorck** [comment]
I'm trying to figure out if [this](https://github.com/samsung-cnct/k2/blob/2ab10e227d12e7e2e16664a4c24480afe28f9261/ansible/roles/kraken.provider/kraken.provider.gke/templates/deploymentmanager-create.yaml.jinja2) is the right place to start digging around

**Comment by DStorck** [comment]
fixed with https://github.com/samsung-cnct/k2/pull/693

**Comment by leahnp** [comment]
LGTM
