### ISSUE TITLE
AWS API Threshold Limit Violation Exceeded On Every Run of `down.sh`

### ISSUE THREAD

**Issue by sostheim** [samsung-cnct/k2#635]
As a Cluster Operator on AWS Cloud Provider infrastructure, every time I try to run `./down.sh` on my K2 managed Kubernetes cluster, I experience a API threshold limit violation when the script begins the teardown of AWS ELB.

This may be a duplicate of, or artifact of, #268

**Comment by sostheim** [comment]
Currently, only resolution is to tear down cluster components from AWS CLI, or Console, by hand.

**Comment by coffeepac** [comment]
downgrading from p0 to p1.  this is annoying but it does not cause anyone to wake up at 2am to resolve.

**Comment by coffeepac** [comment]
@sostheim can you please get the output from a down run that explodes?  We don't see this anywhere else on the regular like that.

**Comment by joejulian** [comment]
Asked for logs privately

**Comment by sostheim** [comment]
Will repro and capture logs.  Any specific advice on how best to capture a useful log?

👍 on the p1 status.

**Comment by coffeepac** [comment]
`./down.sh <whatever flags get used> 2>&1 > down-log.<date>.log`  should do it

**Comment by sostheim** [comment]
[down-log.7-18-17_standard_output.txt](https://github.com/samsung-cnct/k2/files/1157169/down-log.7-18-17_standard_output.txt)

Log file attached from attempting to bring down a cluster that exhibits this error.

I have a verbose log as well that I'll attach as soon as I'm done scrubbing to ensure that there isn't any sensitive information in the log.

**Comment by sostheim** [comment]
Verbose output log, same error:
[down-log.7-18-17_verbose_output.txt](https://github.com/samsung-cnct/k2/files/1157200/down-log.7-18-17_verbose_output.txt)

**Comment by sostheim** [comment]
Courtesy of research by @twilfong, potentially related issues from Ansible:
https://github.com/ansible/ansible/issues/13796
https://github.com/ansible/ansible-modules-core/issues/143

**Comment by coffeepac** [comment]
just realized that k2 down is going to try and delete every ELB in the VPC as a cleanup mechanism.  this is a throwback to K2 assuming everything in the VPC must go.

that seems like a thing that needs to be fixed sooner than later.

**Comment by alejandroEsc** [comment]
So I have seen this issue when working from home. Friday evening in particular was harsh as I had been working on bringing up a cluster for a while and doing checks on aws console etc.. As soon as I decided to bring down a cluster things got bad with errors saying I exceeded the rate limit. I had issues from then on: looking at pages (most issues in the vpc aws ui) in the console, and performing subsequent ups. I only see this happening at my home, and have observed it on multiple occasions.

**Comment by coffeepac** [comment]
good intel.  I've been struggling to reproduce it.  

thanks.

**Comment by coffeepac** [comment]
I have been able to recreate this locally by creating a bunch (50+) ELBs in us-west-2 and then running down against the same cluster twice concurrently.  this causes an API limit failure immediately.  

going to make sure I can replicate this with a BYO setting then I'll push my change.

**Comment by coffeepac** [comment]
this should do it:  https://github.com/samsung-cnct/k2/pull/677
