### ISSUE TITLE
Kraken replacement?

### ISSUE THREAD

**Issue by cgswong** [samsung-cnct/k2#64]
Two very interesting projects here with Kraken and K2 (Kraken 2), with some awesome work being done. It seems that K2 is the replacement for the original Kraken based on the title, correct? If so, then the repo to use and follow would be K2, correct?

I'd recommend a brief snippet or two on both repos on which to use, or maybe it is either depending on use case, just to make things clearer. If one (Kraken?) is deprecated I think that should be stated as well.

Thanks

**Comment by maratoid** [comment]
Thank you for your interest, and that is an excellent point. We'll be addressing this (and https://github.com/samsung-cnct/k2/issues/46) ASAP.

**Comment by coffeepac** [comment]
@cgswong sorry for the delay on this!  we have updated the README for k2 and included the whys and wherefores.

if you have any further questions or comments please open an issue and we'll be much more responsive going forward.
