### ISSUE TITLE
Create an optional bastion instance.

### ISSUE THREAD

**Issue by alejandroEsc** [samsung-cnct/k2#659]
to support private topologies, we should create a public facing bastion object that:

- has ssh authorized public keys for the user (initially 1)
- No running kubenertes services, and not managed by k8s
- launched in defined subnets 
- optional entry in the cluster config.
- should be  of instance type t2.micro? but we should agree on this
- should be managed by an asg
- OS should be coreos

any additional requirements to be discussed on this ticket.

**Comment by coffeepac** [comment]
t2.micro seems fine.

I am unsure why it should be coreOS, we plan to support other OSes in the near to medium term.
why should the bastion be in an ASG?

**Comment by alejandroEsc** [comment]
- coreos because that is what we are using, doesnt have to be you are right, but figure we do that since we already use it. Let me know if you are considering something else. ASG is because a bastion should always work if that is the only way we can get access the nodes directly, one per AZ  would be ideal. you dont need an asg, but i think it would be nice to make the bastion at least always reliably there, if costs are incurred due to it, i suppose just having to run the up/terraform apply should do i guess.

**Comment by coffeepac** [comment]
OS:  okay.  it doesn't matter much, but was curious if there was a hard reason for it.  the bastion node should have an osConfig field which can be whatever.

ASG:  one per AZ?  ahh, for continued access in the face of AZ failure.  Okay, now I get it.  Sounds good.

**Comment by coffeepac** [comment]
@alejandroEsc are you doing this?

**Comment by alejandroEsc** [comment]
working on it since yesterday afternoon.
