### ISSUE TITLE
Update default version of k8s for GKE to 1.6.7

### ISSUE THREAD

**Issue by davidewatson** [samsung-cnct/k2#665]
It is currently at 1.6.6, which is unavailable according to the [release notes](https://cloud.google.com/container-engine/release-notes) for new clusters. This is causing CI runs to take ~45 minutes.

**Comment by coffeepac** [comment]
according to those notes, the default is 1.6.4.  

I suspect you need to rebase a PR to pick up the change back to 1.6.4 and 1.6.4 is the current default in K2 master

**Comment by davidewatson** [comment]
You are right!
