### ISSUE TITLE
ssh_config does not contain all nodes created by k2

### ISSUE THREAD

**Issue by davidewatson** [samsung-cnct/k2#67]
I created a k2 cluster using the default config created by

```
./up.sh --generate
```

I noticed that the generated ssh_config does not all of the nodes created by k2

```
rodin:k2 dwat$ grep Host\  ~/.kraken/dew/ssh_config 
Host etcd-1
Host etcd-2
Host etcd-3
Host etcd-4
Host clusterNodes-1
Host clusterNodes-2
Host clusterNodes-3
rodin:k2 dwat$ 
```

Was this a conscious design choice? Or is it a bug? While I agree that in principle there should be no reason to log on to the etcEvent or master nodes, in practice it can be very useful to be able to do so for debugging purposes.

**Comment by keyolk** [comment]
in my case it container only 2of special Nodes.
I get the config with default config which generated by k2.

```
Host specialNodes-1
  HostName ec2-54-245-20-219.us-west-2.compute.amazonaws.com
  Port 22
  User core
  IdentityFile /root/.ssh/id_rsa
Host specialNodes-2
  HostName ec2-54-200-233-94.us-west-2.compute.amazonaws.com
  Port 22
  User core
  IdentityFile /root/.ssh/id_rsa
```

and in my second try it only contains ETCDs

I think there are some problem when generating ssh_config

**Comment by mikeln** [comment]
I only see the etcd, etcdEvents, clusterNodes, specialNodes

Where are the Masters, and APIServers? (or whatever setup we are using for the control plane?)

**Comment by coffeepac** [comment]
two issues:
- master nodes aren't being found (unsure why)
- etcd nodes aren't being found (they are no longer autoscaled so the filter is wrong.

will continue to investigate this tomorrow.

**Comment by coffeepac** [comment]
PR available ^^
