### ISSUE TITLE
ec2_elb_facts can cause API rate limit issues

### ISSUE THREAD

**Issue by coffeepac** [samsung-cnct/k2#676]
there is no way to throttle the ansible module nor does the ansible module provide a way to back off/retry if an API limit is hit.  we should either:
a. make an update to the module so it does do back off/retry
b. re-write this task to not use this module. 

using this module is a bit problematic for another reason:  #563

**Comment by alejandroEsc** [comment]
we should watch this: https://github.com/ansible/ansible/issues/13796

**Comment by sostheim** [comment]
@coffeepac - just checking, did you want this ticket to remain open to track the long term resolution to #677 I believe the "fix:" text in the description caused this to automatically close on merge.

**Comment by coffeepac** [comment]
I do not want this to remain open.  We have another issue open to stop using this module entirely.
