### ISSUE TITLE
Save plan for apply

### ISSUE THREAD

**Issue by davidewatson** [samsung-cnct/k2#689]
We need to use the out parameter to plan to ensure we apply the same plan we print.

```
            "Note: You didn't specify an \"-out\" parameter to save this plan, so when", 
            "\"apply\" is called, Terraform can't guarantee this is what will execute.", 
```

**Comment by DStorck** [comment]
work is done https://github.com/samsung-cnct/k2/pull/740
for now the plan is being saved to a dir called `tf_plan`.  super creative.
