### ISSUE TITLE
ssh to intances

### ISSUE THREAD

**Issue by keyolk** [samsung-cnct/k2#69]
I'm not sure whether it is intended working.
and I use the image "quay.io/samsung_cnct/k2:latest"

there is no ssh client in image,
so I use laptop host's ssh client.

problem is ...
  1) owner of RSA key is root, not not mine.
  2) IdentityFile path in ssh_config is under root's home, not my home.

So I just manually edit the ssh_config under .kraken
and try ssh with root account.

is there other convenient way for it ?

below is my host info

```
Linux keyolk-book 4.4.2-6ph #1 SMP Mon Jun 13 20:01:22 KST 2016 x86_64 GNU/Linux
```

```
Containers: 24
 Running: 2
 Paused: 0
 Stopped: 22
Images: 1
Server Version: 1.12.2
Storage Driver: overlay
 Backing Filesystem: xfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null bridge host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.2-6ph
Operating System: Apricity OS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.61 GiB
Name: keyolk-book
ID: AKMT:LO4B:TAXU:M6K3:RYEQ:GE5B:GLZ6:ISBQ:WBN7:FYKF:CMN6:TN2W
Docker Root Dir: /home/keyolk/mount/flash/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

**Comment by coffeepac** [comment]
@keyolk this is an issue with using the k2 image directly.  the k2 image doesn't have visibility into where the key lives on the host system.  k2cli will perform this update for you but its not quite ready yet.  

so for now you'll need to either edit the file manually or add '-i <path to your ssh key>' each time you try to ssh to a node

**Comment by coffeepac** [comment]
this will be fixed elsewhere.  not tracking here anymore
