### ISSUE TITLE
Dogfood: Internal Production Clusters

### ISSUE THREAD

**Issue by jandrake** [samsung-cnct/k2#691]
When speaking to customers, we promote best practices, such as:

- Fewer, larger clusters
- Cluster promotion: Dev, QA, Prod
- Separate CI Cluster Interacting with Dev, Qa, Prod
- Right-Sized clusters
- Use of virtual clusters

We need to operate in the same manner that we recommend to our customers.  This issue is intended to be a top-level issue incorporating the collection of capabilities needed to meet this goal.

Success Criteria:
- Single set of operating clusters for CNCT. At least CI, DEV, PROD.
- Cluster operations toolsets hosted on virtual clusters
- All changes to clusters done on DEV and promoted to other clusters
- CI chain automating promotion of virtual clusters across physical clusters
- CI chain automating promotion of applications across physical clusters
- Health and performance reporting on clusters

Comments welcome.

**Comment by leahnp** [comment]
What of these criteria do you think our current common-tools production cluster meets?

**Comment by coffeepac** [comment]
moved to appropriate repo: https://github.com/samsung-cnct/issues/issues/31
