### ISSUE TITLE
Generate Compute Cost Analysis

### ISSUE THREAD

**Issue by jandrake** [samsung-cnct/k2#695]
As a cluster planner, I would like an estimate on compute instance costs based on cluster configuration.

Success Criteria:

- Provide estimate monthly compute costs based on infrastructure provider
- Provide estimate using dedicated compute infrastructure on the same provider
- Bonus points:
  - Compare estimates across providers

**Comment by davidewatson** [comment]
We could probably implement this for AWS using [Cost Allocation Tags](http://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/cost-alloc-tags.html).

Other stop gap measures include the:

 - [AWS Simple Monthly Calculator](https://calculator.s3.amazonaws.com/index.html) for simple manual queries.
 - [TCO service](https://aws.amazon.com/tco-calculator/) for more comprehensive reports.

**Comment by alejandroEsc** [comment]
Probably belongs in another repo, maybe k2cli? or could be another tool.

**Comment by coffeepac** [comment]
move to issues repo

**Comment by coffeepac** [comment]
moved to: samsung-cnct/issues#34
