### ISSUE TITLE
Heapster Pull Error

### ISSUE THREAD

**Issue by mikeln** [samsung-cnct/k2#730]
killing CI and local clusters:

> TASK [roles/kraken.services : Install charts from registry] ********************
> failed: [localhost] (item={u'chart': u'samsung_cnct/heapster', u'version': u'0.1.0-0', u'namespace': u'kube-system', u'registry': u'quay.io', u'name': u'heapster'}) => {"changed": true, "cmd": ["/opt/cnct/kubernetes/v1.7/bin/helm", "registry", "install", "quay.io/samsung_cnct/heapster@0.1.0-0", "--", "--name", "heapster", "--namespace", "kube-system", "--values", "/home/jenkins/workspace/K2_PR-729-K2T2U34K2ZDGBAWG7N5R6UBRQ6FEWUSVK6VK37TGL72BDAABAZGQ/cluster/aws//pr-729-2/quay.io-heapster.helmvalues"], "delta": "0:00:00.883611", "end": "2017-08-09 18:40:32.403388", "failed": true, "item": {"chart": "samsung_cnct/heapster", "name": "heapster", "namespace": "kube-system", "registry": "quay.io", "version": "0.1.0-0"}, "rc": 1, "start": "2017-08-09 18:40:31.519777", "stderr": "usage: appr [-h]\n            {run-server,show,inspect,logout,plugins,helm,pull,list,delete-package,version,push,login,config,channel}\n            ...\nappr: error: \nmessage: '500 Server Error: Internal Server Error for url: https://quay.io/cnr/api/v1/packages/samsung_cnct/heapster/0.1.0-0/helm/pull?format=json'\nresponse: \"<html>\\n  <head>\\n    <title>Internal Server Error</title>\\n  </head>\\n  <body>\\n    <h1>Internal Server Error</h1>\\n    \\n  </body>\\n</html>\\n\"\n\nError: plugin \"registry\" exited with error", "stderr_lines": ["usage: appr [-h]", "            {run-server,show,inspect,logout,plugins,helm,pull,list,delete-package,version,push,login,config,channel}", "            ...", "appr: error: ", "message: '500 Server Error: Internal Server Error for url: https://quay.io/cnr/api/v1/packages/samsung_cnct/heapster/0.1.0-0/helm/pull?format=json'", "response: \"<html>\\n  <head>\\n    <title>Internal Server Error</title>\\n  </head>\\n  <body>\\n    <h1>Internal Server Error</h1>\\n    \\n  </body>\\n</html>\\n\"", "", "Error: plugin \"registry\" exited with error"], "stdout": "", "stdout_lines": []}
>

**Comment by mikeln** [comment]
`quay.io/samsung_cnct/heapster`  is completely missing (looking at our quay.io repo online).

**Comment by venezia** [comment]
coincidentally I have an open issue with quay support about this.

They have acknowledged it and escalated it.

**Comment by venezia** [comment]
Try now - quay indicates they fixed the issue and it is working for me

**Comment by mikeln** [comment]
yes, CI worked on that step now... fixed.
