### ISSUE TITLE
Required: Thematic Easter Egg

### ISSUE THREAD

**Issue by jandrake** [samsung-cnct/k2#748]
The newly renamed from k2cli kraken interface needs an easter egg that is thematic...

kraken --release-me

or

kraken --release-the

Should result in an easter TBD and modified from time to time by internal kraken contributors.

Please note: must adhere to all Samsung proprieties, within reason.

**Comment by DStorck** [comment]
that is excellent.

**Comment by joejulian** [comment]
I totally agree!

Please refile in https://github.com/samsung-cnct/k2cli/issues

**Comment by joejulian** [comment]
This issue was moved to samsung-cnct/k2cli#132
