### ISSUE TITLE
running k2 images swallows kill signals

### ISSUE THREAD

**Issue by coffeepac** [samsung-cnct/k2#77]
when running the k2 image as follows:

```
docker run -v ... quay.io/samsung_cnct/k2 /kraken/up.sh
```

I am unable to Ctrl-C out of that command.  I have to run `docker ps` and then `docker kill <id>` to stop the script.

**Comment by maratoid** [comment]
how about docker -it .. ?

**Comment by coffeepac** [comment]
yeah okay, that worked.  fiiiiine.
