### ISSUE TITLE
Security Group gets reset (sometimes) on cluster update - undesirable

### ISSUE THREAD

**Issue by venezia** [samsung-cnct/k2#817]
It appears that if you add and remove a nodepool, some times (but not always) security groups for nodepools are reset to their original intention through the configuration.

This does not sound bad, but can have a disastrous impact on an existing cluster.  k8s aws integration creates a security group for each load balancer and adds this security group to the whitelist of traffic in security groups that nodes are using.

Once reset, k8s aws integration does not reconcile the missing whitelist entries.  In effect the services are cut off from their corresponding ELB.  New ELBs can be created and linked correctly.

What may be desirable is to tell terraform _not_ to to reset this security group.  This also means communicating to the user that any security group ingress/egress rules will need to be handled manually. :(

**Comment by joejulian** [comment]
This bug only affects AWS.

Until this bug is addressed, it can be worked around by adding a "from 0/0" rule with the allowed ports to the node's security groups.

**Comment by coffeepac** [comment]
first attempt:
- create cluster
- manually add rule to security_group
- run `terraform apply` from cli
- manually added rule removed

**Comment by coffeepac** [comment]
second attempt, using pre-existing cluster (from first attempt):
- manually add rule to security_group
- modify existing nodePool (change node count from 1 -> 2)
- manually added rule removed

**Comment by coffeepac** [comment]
third attempt, using pre-existing cluster (from first attempt):
- manually add rule to security group
- modify running kraken-lib to ignore changes to ingress/egress rules for security group
- modify existing nodePool (change node count from 2 -> 1)
- manually added rule ...

**Comment by coffeepac** [comment]
have a fix for an existing cluster, things to sort out still:
- does this work for a new cluster (ie do the initial rules get created then we effectively hand over control to k8s for long-term maintence
- why do I keep seeing that the route table wants to be updated by a raw `terraform plan` but kraken isn't updating it

**Comment by coffeepac** [comment]
it appears there is a similar situation with the vpc route table.  making the same fix there and testing.

fourth attempt, using pre-existing cluster (from first attempt):
- manually add route to route table
- modify running kraken-lib to ignore changes to routes for vpc route table
- modify existing nodePool (change node count from 1 -> 2)
- manually added route (in progress)

**Comment by coffeepac** [comment]
last check:  destroy/create cluster and ensure that cluster is created correctly.  if this works I'll open a PR and get CI after it.

**Comment by coffeepac** [comment]
PR open, need to open an issue to fix this at some point.  It would be best if modifying the config file's ingress/egress rules modified the existing rules without destroying the kubernetes created assets.  But that's a bigger problem then this.
