### ISSUE TITLE
way to launch some part of tasks ? 

### ISSUE THREAD

**Issue by keyolk** [samsung-cnct/k2#94]
let say I created kraken clusters on AWS,
and if I want to just change some of configuration on kube-apiserver.
How I can try this with k2 ? 
Is there a way to launch only part of tasks ?

**Comment by coffeepac** [comment]
@keyolk not right now, now.  issue to handle this exists though:  https://github.com/samsung-cnct/k2/issues/85

**Comment by coffeepac** [comment]
punting this to after we have a self hosted discussion/implementation.

**Comment by coffeepac** [comment]
its possible but we may have to rebuild the control plane in a self-hosted manner.  stop having the apiserver be a static pod.

**Comment by coffeepac** [comment]
closed via update.sh
