### ISSUE TITLE
More Specific New User How To

### ISSUE THREAD

**Issue by mikeln** [samsung-cnct/k2#95]
There should be an obvious step-by-step first time usage document that should be the first thing listed in the README.

That doc should spell out exactly things that need to be done, values that need to be set to something meaningful for the user, etc... (e.g. Set your cluster name - here, use that same name - here, look in AWS (or whatever) for that name as a prefix ...

**Comment by coffeepac** [comment]
@mikeln is the Getting Started guide in k2cli sufficient?  https://github.com/samsung-cnct/k2cli

Probably need to add aws account requirements, but other then that?

**Comment by mikeln** [comment]
yeah, that looks better.

**Comment by coffeepac** [comment]
thanks!  opened up https://github.com/samsung-cnct/k2cli/issues/26 to specify AWS cred requirements.
