### ISSUE TITLE
Specifying a /root Mount that Is not $HOME Does Not Work.

### ISSUE THREAD

**Issue by mikeln** [samsung-cnct/k2#96]
In my first start of K2, I wanted to isolate my machine from any files that might be created by the startup.  So I created a k2wrap directory, and specified that as my /root mount.  This work for some items, but there are many assumptions that  there will be other $HOME directories available there.  e.g. .ssh, .aws.  This was not spelled out in the documentation.

Also, there may also be some other hard coded assumptions that ~/ is the mount.

Please document this better, and if it is not allowable to use a mount other than $HOME say that!
I would advocate allowing the /root mount to be wherever the user wants.

**Comment by coffeepac** [comment]
this is a documentation issue.  k2 needs to have ~/.aws and ~/.ssh available in the running container's root user directory.  how the user gets those directories into the running container can take many forms.

docs will be updated for this.

**Comment by coffeepac** [comment]
may be done already.  check out hte k2 readme.

**Comment by coffeepac** [comment]
this is partially done.  Going to try and knock it out while conformance tests run.

**Comment by joejulian** [comment]
Just to add my $0.02, this _is_ a purely documentation thing. I have tested using a `mktemp -d` directory with the .aws/credentials file and an id_rsa file (properly referenced in the config.yaml) and it worked fine.
