### ISSUE TITLE
K2 Up Creates Subdirectories That May Cause Problems

### ISSUE THREAD

**Issue by mikeln** [samsung-cnct/k2#97]
When the system comes up, it creates files and subdirs in the mounted /root filesystem.

When this mount is $HOME (as given in the README), you have the potential to have unexpected .dot files added to your account, and potentially changed/deleted.

Anecdotal observations:
files created: .rnd, .srl
directories created: .terraform.d
directory created and deleted: .ansible
directory updated: .kube, .kraken

It would be "safer" to contain any changes to a subdirectory.  Or else warn the user what files/dirs will be modified and how, so they can take action to protect whatever they have before k2 does something to them.

**Comment by coffeepac** [comment]
I agree whole heartedly.

**Comment by coffeepac** [comment]
this may be fixed already in the README for k2.  see if $HOME is still being suggested as a docker mount.

**Comment by joejulian** [comment]
> files created: .rnd, .srl
> directories created: .terraform.d
> directory created and deleted: .ansible
Should be handled in https://github.com/joejulian/k2/tree/97_k2_up_stomps_on_user_files

`.kraken` already has a warning
`.kube` shouldn't be touched. Still looking in to this.
