### ISSUE TITLE
[WIP] Get rid of etcd autoscaling and SRV record creation based on AWS lambda

### ISSUE THREAD

**Issue by maratoid** [samsung-cnct/k2#99]
A bit of background:

Currently, we use SRV discovery for our etcd clusters. 
etcd autoscaling groups send lifecycle events to an SNS topic
A lambda function subscribes to the SNS topic and based on the data from lifecycle event and a tag from the autoscaling group creates and destroys route 53 records.

This has been proven to not be 100 percent reliably and is hard to debug. I propose we do the following:

1)  In [aws provider etcd module template](https://github.com/samsung-cnct/k2/blob/master/ansible/roles/kraken.provider/kraken.provider.aws/templates/kraken.provider.aws.module.etcd.tf.jinja2) - instead of autoscaling group, use a fixed number of EC2 instances
2)  In [aws provider etcd module template](https://github.com/samsung-cnct/k2/blob/master/ansible/roles/kraken.provider/kraken.provider.aws/templates/kraken.provider.aws.module.etcd.tf.jinja2) - get rid of lambda creation, SNS topic creation and associated IAM objects
3)  In [aws provider etcd module template](https://github.com/samsung-cnct/k2/blob/master/ansible/roles/kraken.provider/kraken.provider.aws/templates/kraken.provider.aws.module.etcd.tf.jinja2) - add creation of SRV record per etcd instance (work currently being done by the lambda code). Per etcd cluster:

One A record (etcd-cluster-name.k2-cluster-name.internal.) with all etcd private IP addresses

One A record per etcd cluster VM instance-id.etcd-cluster-name.k2-cluster-name.internal. pointing at the VM's private ip.

One SRV record per etcd VM instance _etcd-client-ssl._tcp.etcd-cluster-name.k2-cluster-name.internal. 0 0 client-port instance-id.etcd-cluster-name.k2-cluster-name.internal. 

One SRV record per etcd VM instance _etcd-server-ssl._tcp.etcd-cluster-name.k2-cluster-name.internal. 0 0 server-port instance-id.etcd-cluster-name.k2-cluster-name.internal. 

(_etcd-client._tcp and _etcd-server._tcp for non-SSL deployments)

4) Clean up all lambda-sns-etcd-service-discovery.py / lambda-sns-etcd-service-discovery.zip packaging

**Comment by maratoid** [comment]
@venezia suggests we actually assign static private IP addresses to etcd nodes.

**Comment by coffeepac** [comment]
@venezia what is the rationale for assigning static ip addresses?

**Comment by maratoid** [comment]
That'll let us setup DNS entries before any of the etcd nodes are actually up.

**Comment by coffeepac** [comment]
too much work for me to figure out how to create an ENI and make sure the ip it gets assigned to is part of the correct subnet.  that's also something easily split out.  will probably create a new ticket to handle that.

**Comment by coffeepac** [comment]
allmost done.  the etcd node isn't getting any tags but its coming up properly.  will sort out the tags tomorrow.
